### ISSUE TITLE
[Bug] App theme, characters and moon-button

### ISSUE THREAD

**Issue by Splike** [xanderfrangos/twinkle-tray#1]
Hi! Saw the app mentioned by you on reddit and thought I'd give it a try. I installed the app from your github releases page (v1.6.3) and I have the following issues.

1. The app doesn't respect my system app theme. (See Image)
2. The app can't handle all characters (See monitor name in image)
3. After installing the app, I clicked the moon button because I thought that would make it dark. But my screen just turned off, which had my heart skip a beat. I think you should explain what this button does during setup or when first used.

![Screenshot 2020-01-13 10 28 51](https://user-images.githubusercontent.com/7159527/72244946-a03c8c80-35ef-11ea-9507-2c53ada16f94.png)

**Comment by jordi-7** [comment]
I can confirm #1. Setting dark theme manually is broken too, the background is still white but the text gets even darker.
For #2, hovering above an icon shows its description.

**Comment by xanderfrangos** [comment]
@Splike @jordi-7 Do you mind trying out v1.6.2 and let me know if the theme is still wrong there? https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.6.2

**Comment by jordi-7** [comment]
It is still broken, this time the light theme doesn't correctly switch the background color:
![image](https://user-images.githubusercontent.com/7353995/72283244-a73ebb80-363e-11ea-9782-631405cc2ade.png)

**Comment by Splike** [comment]
I Downloaded v1.6.2. I have the same issues as before.

With regards to @jordi-7 comment above, explicitly setting the app theme to light or dark will change the tray pop-up accordingly for me.

I'm running 

![Screenshot 2020-01-13 20 58 58](https://user-images.githubusercontent.com/7159527/72287557-8af34c80-3647-11ea-9eb0-8bed7664b100.png)

**Comment by xanderfrangos** [comment]
Thanks for the info on the theme bugs! They should be resolved in the next update. I'm looking in to the monitor text bugs now.

**Comment by jordi-7** [comment]
Awesome! Looking forward to the next release

**Comment by xanderfrangos** [comment]
@Splike @jordi-7 v1.6.4/v1.6.5 should resolve both the theme bugs and monitor name bug. Give the latest version a go and let me know if it's all good now: https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.6.5

**Comment by jordi-7** [comment]
Just installed 1.6.5 and it works perfectly! Thank you

**Comment by Splike** [comment]
The theme bug and text display bug are both fixed for me. Thanks a lot @xanderfrangos
