### ISSUE TITLE
Make it not allowing multiple instances

### ISSUE THREAD

**Issue by HO-COOH** [xanderfrangos/twinkle-tray#100]
I accidentally make one instance freeze, and want to restart it and found out that it can allow multiple instances to run at the same time. There is really no reason for it.
![image](https://user-images.githubusercontent.com/42881734/97775054-4f206980-1b2b-11eb-95c4-f3be35ade0df.png)

**Comment by xanderfrangos** [comment]
I do need it for development, but I'll disable multiple instances in production builds. 👍

**Comment by xanderfrangos** [comment]
Thanks for the suggestion! Multiple instances are no longer allowed as of v1.13.0. 

Multiple tray icons may still appear if the process was terminated and then started again (ex. update). That's just a Windows bug. Hovering over the tray icon will make the duplicate disappear.
