### ISSUE TITLE
Brightness tray change slider and brightness change OSD are showed for internal monitor when the internal monitor is disabled

### ISSUE THREAD

**Issue by notuxius** [xanderfrangos/twinkle-tray#105]
I have a windows setting to disable completely the internal monitor when I'm plugging in the external one, but brightness slider and OSD are displayed also for the internal monitor when it's disabled

**Comment by pranavg189** [comment]
This is reproducible on my Surface Laptop 2 as well. Would be great if we can display the OSD only for the screens which are enabled. We can detect this using the inbuilt windows 10 display settings, maybe.

![Display Settings](https://i.imgur.com/Cn8lgI5.png)

Moreover, we can also add the option to manually disable the OSD for each of the individual displays.

**Comment by xanderfrangos** [comment]
Closing this issue, as the requested feature is available as of v1.14.0. This features is listed as `Hide Internal Display` in the Monitor Settings menu.
