### ISSUE TITLE
Can It Auto Refresh the Brightness Setting when PCs come back from Sleep or Reboot?

### ISSUE THREAD

**Issue by womeimingzi11** [xanderfrangos/twinkle-tray#107]
My Monitors are Skyworth 27X1Q and AOC U2477WM, of which firmwares and OSD setings are not as fancy as ViewSonic or Dell. When I wake up my PC from sleeping or just reboot it, the brightness will reset to a default level. I have to set the brightness to a comfortable level from Twinkle Tray manually. 

I just wander if it is any possible to add a option which refresh monitor's brightness after waking up or rebooting automatically?

**Comment by xanderfrangos** [comment]
@womeimingzi11 Thanks for the suggestion! I've released v1.13.0 with a partial implementation of this. Twinkle Tray will now attempt to restore brightness when waking from sleep/hibernation. I'll add an option to restore the last known brightness on reboot in a future update. 👍

**Comment by womeimingzi11** [comment]
Whoa! What a great improvement! I have upgraded twinkle-tray to v1.3.0, it looks there is no switch of this feature?

**Comment by xanderfrangos** [comment]
Restoring brightness after sleep/hibernation is automatic. The option for restoring brightness after a reboot will come in a future update. 👍

**Comment by womeimingzi11** [comment]
That's great! Can't wait for the next upgrade! 😂

Xander Frangos <notifications@github.com> 于2021年2月7日周日 上午12:53写道：

**Comment by xanderfrangos** [comment]
v1.13.2 is out now on GitHub (Windows Store version to follow). The new option to restore the last brightness on reboot is included. It's enabled by default. 👍

**Comment by womeimingzi11** [comment]
It's me again. I find restore the last brigtness on reboot works well for my PC. But after waking from sleep/hibernation, the brightness did not restore. 

What kind of any other information should I supply?

Here are my two monitors.
![Snipaste_2021-02-17_21-48-33](https://user-images.githubusercontent.com/10340253/108213372-e9073300-7169-11eb-9e27-88de091d31c9.png)
