### ISSUE TITLE
Animations disabled based on Windows setting

### ISSUE THREAD

**Issue by DanielHerr** [xanderfrangos/twinkle-tray#112]
It would be nice if the tray would not play the entrance animation if the user had requested so in the system settings.

https://web.dev/prefers-reduced-motion
https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetanimationsettings

![Screenshot 2020-12-23 174731](https://user-images.githubusercontent.com/7622517/103042481-c2e95c00-4547-11eb-914b-2e4b507b8ae8.png)

**Comment by xanderfrangos** [comment]
Shouldn't be a big deal to implement. I'll toss it on my to-do list. 👍

**Comment by xanderfrangos** [comment]
@DanielHerr Thanks for the suggestion! This feature has been implemented in v1.13.0.
