### ISSUE TITLE
When resuming from Hibernation monitor does not update according to time adjustments

### ISSUE THREAD

**Issue by mattkerrison** [xanderfrangos/twinkle-tray#116]
Time adjustments work great when the computer is running (Win10, Dell Display with supported DDC/CI), however say I'm using the computer past 10pm, therefore a rule sets the brightness to 25%.

I put the computer to hibernate at 11pm and then power it back on at 7:30am following morning, for which there is a rule at 6:30am to set brightness to 100%. I can barely see the screen as it's still on the 25%. sometimes after a few minutes it refreshes and goes to 100%, sometimes I have to manually change it.

Apart from this it works awesome. Just wondering if any logic can be added in for coming back from sleep / power / hibernation to check all rules asap and apply.

**Comment by xanderfrangos** [comment]
@mattkerrison Thanks for the suggestion! This feature has been implemented in v1.13.0.
