### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by gferreroferri** [xanderfrangos/twinkle-tray#122]
Please add support for volume control on LG 27UL850-W

**Comment by xanderfrangos** [comment]
Thanks for the suggestion! I will be including this as part of a larger feature in a future update. You can read more about it [here](https://github.com/xanderfrangos/twinkle-tray/issues/123). If anyone has suggestions/feedback about volume control over DDC/CI, please leave a comment there. Thanks!
