### ISSUE TITLE
Additional DDC/CI Features (ex. Contrast)

### ISSUE THREAD

**Issue by xanderfrangos** [xanderfrangos/twinkle-tray#123]
The next major feature planned for Twinkle Tray is access to additional DDC/CI features. I plan to include the following:

- Contrast
- Volume
- Color temperature (maybe)
- Power state

All of these DDC/CI features will be off by default, as to not clutter the flyout's UI. If a display supports any of the above features, they can be turned on from the "DDC/CI Features" section of the Settings window.

Based off of user feedback, I plan to allow users to either adjust contrast independently or link it to the brightness (using optional min/max contrast values). I will also include an option to replace the brightness slider with a contrast slider.

I don't have a timeline yet, but I encourage anyone who is interested to follow this Issue, as I'll be sharing updates and early builds for feedback here.

If you have any suggestions or feedback regarding these DDC/CI features (or DDC/CI features not mentioned), feel free to share them here.

**Comment by xanderfrangos** [comment]
Here's a first try at a UI for managing multiple DDC/CI features from the flyout. The sliders displayed are for "brightness", "contrast", and "volume".

![ddcci-features-1](https://user-images.githubusercontent.com/33106561/108283312-10053b00-7151-11eb-84c2-19107b90d51d.jpg)

I'm not crazy about the "contrast" icon. I'm pulling from the [MDL2 icons](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font) used in Windows. If someone sees a better icon for contrast in that list, let me know.

**Comment by itsforrest** [comment]
Would it be possible to override the global volume control so that I can use my keyboard volume buttons?

**Comment by xanderfrangos** [comment]
@itsforrest Unfortunately no. Certain keys like brightness and volume adjustment can't be hooked. Some apps like Modern Flyouts are able to replace the volume/brightness UI by hiding the native Windows UI and detecting brightness/volume changes, but cannot replace the actual functionality. The keyboard volume will always adjust whatever your default Windows sound device is set to.

**Comment by rendalltrinanes** [comment]
is the contrast control going to be released anytime soon?

**Comment by xanderfrangos** [comment]
Hi all, I've posted a beta version of Twinkle Tray [here](https://github.com/xanderfrangos/twinkle-tray/issues/296) with an initial version of the new DDC/CI features. Not all features listed in this issue have made it in yet.
