### ISSUE TITLE
Hotkeys not working with v1.13.0 

### ISSUE THREAD

**Issue by djsavvy** [xanderfrangos/twinkle-tray#124]
Thanks for making twinkle tray!

I have the hotkeys `Alt+F1` and `Alt+F2` assigned to decrease and increase the brightness, respectively. These hotkeys work on v1.12.3, but do not work on v1.13.0. I tested by installing both versions a few times, and when I went back and forth between the versions the problem was 100% reproducible. 

Would any other information/configuration info help?

**Comment by xanderfrangos** [comment]
Whoops! Guess I forgot to test the hotkey for "all displays". Thanks for reporting the bug. I've rolled out v1.13.1 with a fix.

**Comment by djsavvy** [comment]
Thanks for fixing this so quickly! Just dropped you a couple coffees on Ko-Fi :)
