### ISSUE TITLE
Brightness change popup doesn't appear when changed via command-line. 

### ISSUE THREAD

**Issue by djsavvy** [xanderfrangos/twinkle-tray#125]
It would be really nice for a brightness change popup to show up when triggered via the command-line! 

(Also, would it be possible for there to just be one popup if it's triggered for all displays, instead of a popup for each one?)

**Comment by xanderfrangos** [comment]
Already wrote some code for it: https://github.com/xanderfrangos/twinkle-tray/commit/45deae007bbcdf1b6de653e73c1fb9902929a489 😉

It's the same overlay that's shown for hotkeys and the system tray scrolling shortcut. This will be out in v1.13.2. If you want to update your script(s) to be ready for it, just add the `--Overlay` flag.

**Comment by djsavvy** [comment]
Awesome, thank you! Love to see it. 

By the way, from browsing through the code it doesn't look like there's support for just a single popup if the brightness change is triggered for all displays --- is there support planned for that?

**Comment by xanderfrangos** [comment]
Not sure I follow. When the overlay is triggered, it shows the brightness for all displays (in the same order as the displays are in the flyout, left to right).

![overlay-example](https://user-images.githubusercontent.com/33106561/107160839-acb42580-6966-11eb-95c5-da0be6a6ae2c.jpg)

It looks like this whether you're adjusting one or all displays at once.

**Comment by djsavvy** [comment]
Thanks for clarifying. 

I'm thinking of the following use case --- all displays' brightnesses are synchronized. In that case, if I change the brightness (via command-line, or scrolling on the tray icon), it would be reasonable to have just a single overlay pop up.

**Comment by xanderfrangos** [comment]
Oh I see. Yeah, if "link levels" is on that would make sense. I've considered combining all of the sliders into one "All Displays" slider when it's on. That would apply to both the overlay and flyout.

**Comment by xanderfrangos** [comment]
I've now added the above feature in https://github.com/xanderfrangos/twinkle-tray/commit/7b6c53b1941a3600a7dc83119cbc1853eeb44c13. So if you've synchronized the displays, they'll only show up as a single slider.

**Comment by djsavvy** [comment]
Awesome, thank you :)

Excited for the next release!!

**Comment by xanderfrangos** [comment]
v1.13.2 is out now, including the `--Overlay` command-line flag and combined sliders when "link levels" is active. 👍
