### ISSUE TITLE
Toggle button issue in v1.13.2

### ISSUE THREAD

**Issue by rp1231** [xanderfrangos/twinkle-tray#129]
"Launch at startup" and "Apply at startup" toggle seems to have broken.
If I remember correctly, I tried toggling the "Apply at startup" first and then toggled "Launch at startup".
Now both of them seem to be stuck and not toggling.

**Comment by rp1231** [comment]
All the other toggles seem to be working fine.

**Comment by xanderfrangos** [comment]
Thanks for the bug report! I'll check it out.

**Comment by xanderfrangos** [comment]
I've re-uploaded v1.13.2 with a fix for users who haven't yet downloaded the update. I'll upload a proper v1.13.3 in a little bit.

**Comment by rp1231** [comment]
Yes it works fine now.
Thanks for the quickfix!
