### ISSUE TITLE
Normalize brightness feature doesn't work at all + small bug

### ISSUE THREAD

**Issue by Leon422** [xanderfrangos/twinkle-tray#13]
I'm experiencing 2 bugs with the normalize brightness feature.

My settings are:
Internal display: Min: 0, Max: 100
External display: Min 0, Max 70

First of all, whenever I open the Twinkle Tray UI, the brightness of the internal display resets to 70 inmediately if it was over 70 previously.

Second, and more importantly, the feature doesn't work at all. If I set the brightness of the internal display to more than 70, it should raise the brightness of the internal display ONLY, without changing the brightness of the external display, since it's capped to 70. However, it ignores the limit and sets the brightness of the external display to 100 anyways. (and the UI lies about it saying that it's capped to 70). So the feature isn't working at all, really. It just makes the UI glitchy without acomplishing its goal.

Here's a video which shows both issues. You can see that I set the brightness of the internal display to 100 and then I check the brightness of the external display from the display's interface and it changes to 100 despite the limit. After that, I open the Twinkle Tray UI and the brightness of the internal and external displays inmediately drops to 70

https://streamable.com/xappd

The video might look like I set the brightness limit for the wrong screen but that's not the case. In fact, you can see that the internal display, which is the one that is set to uncapped, is properly recognized by the program as an internal laptop display.

**Comment by xanderfrangos** [comment]
Thanks for the detailed bug report. I should be able to recreate the bug and fix it when I get home. It looks like you have "Link Levels" enabled. Is that correct?

**Comment by Leon422** [comment]
@xanderfrangos yep that's correct, the idea is to be able to control both screens at the same time while also limiting the external display to 70 so that it isn't more bright than the internal display

**Comment by xanderfrangos** [comment]
Yeah, what you're expecting is how it's supposed to work. I did a quick test with my DDC/CI-only setup and it worked just fine. I'm guessing what you're seeing is another WMI + DDC/CI bug. Should be easy to fix.

**Comment by xanderfrangos** [comment]
@Leon422 Yep, it was exactly what I thought it was. [v1.8.4](https://github.com/xanderfrangos/twinkle-tray/releases) should fix the bugs. Let me know if everything is working as expected now.

**Comment by Leon422** [comment]
@xanderfrangos Yep, seems to work fine now. Thank you so much!

**Comment by xanderfrangos** [comment]
@Leon422 Awesome! Thanks for helping with all of the WMI + DDC/CI bugs. Hopefully this is the end of them.
