### ISSUE TITLE
A javascript error occurred in the main process

### ISSUE THREAD

**Issue by KovalevArtem** [xanderfrangos/twinkle-tray#133]
![image](https://user-images.githubusercontent.com/36500228/108499858-ffbf9e00-72bf-11eb-8120-2eca186d42f5.png)
After the monitor came out of sleep mode, this error got out ...

I clicked OK. After that, the application continued to work correctly ...

**Comment by xanderfrangos** [comment]
Uuugh, Windows... how can it not find the icon...

Thanks for the bug report. I'll add some code in the next up to ignore when Windows (somehow) randomly forgets that this file exists.

**Comment by xanderfrangos** [comment]
This should be good as of v1.13.4, but feel free to re-open if this pops up again.
