### ISSUE TITLE
Twinkle tray always appears at the bottom if taskbar auto hide is enabled

### ISSUE THREAD

**Issue by zingmars** [xanderfrangos/twinkle-tray#136]
Twinkle Tray v1.13.3 - with taskbar auto hide enabled clicking the tray icon opens the window at the bottom of the screen, however I have my taskbar on the top of the screen. On a 4k screen there's quite a bit of distance between where the taskbar is and where the window opens which makes the use of this app a bit frustrating. There don't seem to be any settings to configure in Twinkle Tray's config either. If possible, it would be nice if the functionality to change  the corner in which twinkle tray is to open (or to adapt to taskbar's location) were to be added.

**Comment by xanderfrangos** [comment]
Are you using a 3rd party shell replacements (ex. Classic Shell)? Twinkle Tray already supports different taskbar positions. It should work if you're not using a 3rd party shell. Here it is at the top of my screen:

![Screenshot 2021-03-02 155015](https://user-images.githubusercontent.com/33106561/109713396-26f35680-7b6f-11eb-9c8f-8d79f84e09fc.jpg)

**Comment by zingmars** [comment]
No, I'm not using any shell replacers. I do however have auto-hide enabled. Disabling it correctly places the shell at the top. Enabling it seems to break it. I've attached a video.

https://user-images.githubusercontent.com/917126/109732079-21286000-7bc5-11eb-95d0-4ce7541708c0.mp4

**Comment by xanderfrangos** [comment]
v1.13.4 has been released with a fix for this issue. 👍

**Comment by zingmars** [comment]
Works great, thanks!
