### ISSUE TITLE
Trying to build using win10-20h1 (visual studio 2019) and Python3

### ISSUE THREAD

**Issue by J-u-n-o** [xanderfrangos/twinkle-tray#143]
Hello, being busy and step by, so will take sometime...

Here my suggestions, and things I am trying; will update when progressing:
*electron-winstore-auto-launch
2.0.3 using @nodert-win10-au
->
@kydronepilot/electron-winstore-auto-launch using @nodert-win10-rs3/windows.applicationmodel

Maybe better use next standard function instead of additional package (though do not know the consequences).
https://www.electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows
    
* Replace @nodert-win10-au by @nodert-win10-20h1
https://www.npmjs.com/package/@nodert-win10-20h1/windows.applicationmodel

* Update node-gyp in (atleast in global-mouse-events)

**Comment by xanderfrangos** [comment]
I'll try out the `@kydronepilot/electron-winstore-auto-launch`, since RS3 isn't actually too recent. I misread it as being 20H1. But this shouldn't actually change anything with building. If you're having trouble building currently, then you might be missing the Node build tools.

**Comment by xanderfrangos** [comment]
Unfortunately, `@kydronepilot/electron-winstore-auto-launch` seems to have build issues that the regular `electron-winstore-auto-launch` doesn't. I'm going to leave it as is for now, but thanks for the suggestion.
