### ISSUE TITLE
Problematic uninstallation

### ISSUE THREAD

**Issue by tja91** [xanderfrangos/twinkle-tray#144]
The regular exe program leaves config files stored somewhere which is problematic since the binded hotkeys remain in history. 

Where is the path for these files and could you fix this in the future? :)

**Comment by xanderfrangos** [comment]
The config file is located at: `%appdata%\twinkle-tray\settings.json`

I'll see about having the uninstaller remove the config file after uninstalling.

**Comment by tja91** [comment]
I appologize the problem was with another app who had default bindings. Thank you for you quick reply

>
