### ISSUE TITLE
Buggy on startup

### ISSUE THREAD

**Issue by DanielHerr** [xanderfrangos/twinkle-tray#145]
For a while, Twinkle Tray has been acting buggy.
On startup, neither the icon tooltip, top left, or bottom right views will correctly show the brightness. They brightness can be changed using the keyboard commands, but only some of the presses actually take effect, and the top left indication still shows that the monitor cannot be detecting while doing so.
If TT is closed and then reopened, most of the problems go away. Sometimes, after pressing the keyboard commands or clicking the icon about a dozen times, TT will then work fine until the next startup. The only thing that goes wrong afterwards is that the keyboard shortcut sometimes fails to work, pressed twice for example, it will only increase the brightness once.
This behavior happens since 1.13.0 but not in 1.12.3 on Windows 20H2.

**Comment by xanderfrangos** [comment]
Hi @DanielHerr,
When you say that "neither the icon tooltip, top left, or bottom right views will correctly show the brightness", do you mean that it shows the wrong information? Or is it not showing any UI at all? Or is it something else?

**Comment by DanielHerr** [comment]
The top left indicator and bottom right panel shows that the monitor is not detected. The icon tooltip shows 50% even after changing the brightness with intermittently working keyboard commands.

**Comment by xanderfrangos** [comment]
I believe this has been fixed as of v1.13.6, but let me know if you're still having problems at startup. Feel free to open a new Issue if needed.
