### ISSUE TITLE
Slider panel appears in bottom right corner of primary monitor when the taskbar is on a secondary monitor.

### ISSUE THREAD

**Issue by wengh** [xanderfrangos/twinkle-tray#147]
### How to reproduce
1. Get a second monitor
2. Turn off "Settings > Personalization > Taskbar > Show taskbar on all displays"
3. Turn off "Settings > Personalization > Taskbar > Lock the taskbar"
4. Drag the taskbar to the secondary monitor (the location doesn't matter as long as it's not on the primary monitor)
5. Click the Twinkle Tray tray icon
6. Observe the location of the slider panel

### Expected behaviour
The slider panel should appear next to the tray icon on the secondary monitor.

### Problem
The slider panel appears in the bottom right corner of the primary monitor.

### Screenshot
The larger monitor is primary.

![image](https://user-images.githubusercontent.com/16470555/111074020-9f371180-84b7-11eb-9d2a-6ad3cef2914c.png)

**Comment by xanderfrangos** [comment]
Thanks for the bug report. I should be able to fix this. 👍

**Comment by xanderfrangos** [comment]
v1.13.4 has been released with a fix for this issue. 👍
