### ISSUE TITLE
Feature request: changing the brightness of an individual display should unlink the others

### ISSUE THREAD

**Issue by 1player** [xanderfrangos/twinkle-tray#161]
Here's my use case: I have two monitors, usually with linked brightness. I have hotkeys to change the brightness of one single display, and if they're linked, the brightness of all displays, instead of just the one, is changed, which makes it quite confusing.

My suggestion is: if multiple displays are linked, and the hotkeys to control a single display are pressed, unlink them.

**Comment by xanderfrangos** [comment]
I think that's valid, but it should be optional. Not all users may want that functionality.

**Comment by xanderfrangos** [comment]
This feature is now available in v1.13.7. It's in the settings as _Hotkeys & Shortcuts_ -> _Hotkeys break linked levels_.

**Comment by 1player** [comment]
Works fine here, I'll close the issue. Thanks!
