### ISSUE TITLE
Monitor connected over USB-C to DVI cable disconnects when opening application from system tray

### ISSUE THREAD

**Issue by JacobDB** [xanderfrangos/twinkle-tray#164]
I've got the following setup:

- Acer G235H (ACR0114), connected via a [USB-C to DVI cable](https://www.amazon.com/gp/product/B07PV8QXN4)
- Acer G235H (ACR0120), connected via an [HDMI to DVI cable](https://www.amazon.com/gp/product/B014I8UQJY), through a [Dell DA200](https://www.amazon.com/Dell-Adapter-USB-C-HDMI-Ethernet-DA200/dp/B012DT6KW2) (USB-C to HDMI and USB-A adapter)
- Dell XPS 15 9500

If either monitor is connected via the USB-C to DVI cable, they refuse to work with Twinkle Tray. They do get marked with the green checkmark, but "Current Brightness" and "Max Brightness" are both "???." The monitor connected to the Dell DA200 works perfectly (well, nearly perfectly, there's some flashing when making adjustments, but it's manageable).

Considering this issue starts occurring on the ACR0120 when I plug in the USB-C to DVI cable, I suspect if I plugged in the HDMI to DVI cable to the ACR0114, it would work as expected, but it's a bit more of a pain to test that due to cable length, so I'll have to wait until tonight to give it a shot (will update this issue).

This could be an issue with my USB-C to DVI cable, and I'd be willing to buy another one if I can get some help identifying one that may work better. Otherwise, if this is indeed a bug with Twinkle Tray, I'd be happy to provide any further information or run any further tests.

**Comment by xanderfrangos** [comment]
If it gets the green check mark, but "???" for the brightness, then DDC/CI is technically working but Twinkle Tray isn't able to read the brightness VCP code from your monitor.

I recommend testing if the VCP codes can be read at all using [ControlMyMonitor](https://www.nirsoft.net/utils/control_my_monitor.html). Take a screenshot of ControlMyMonitor after you select your monitor so I can see which VCP codes show up.

**Comment by JacobDB** [comment]
Just tested the DVI-HDMI-DA200 route on the monitor I'm having issues with, and sure enough Twinkle Tray worked without issue. So there's gotta be something specific to this cable that's the issue.

As for ControlMyMonitor, when I select the monitor connected to the USB-C to DVI cable, the screen flashes black many times and then I see this:

![image](https://user-images.githubusercontent.com/1123997/113941631-17e27280-97c5-11eb-81bc-536437ca848a.png)

**Comment by xanderfrangos** [comment]
Yeah, there's something wrong with that specific cable. ControlMyMonitor should show a large list of options (brightness, contrast, etc). And it isn't because it's USB-C, as I have a USB-C to HDMI cable that works just fine.

I'll make a note of it in the wiki in case others have the same issue.

**Comment by JacobDB** [comment]
Alright, I'll see about getting another cable to try. Will report back if I have success. Thanks for the assistance.

**Comment by xanderfrangos** [comment]
Since I haven't heard back about this for a while, I'm going to assume everything is good now and close this Issue. Feel free to comment if that's not the case or open a new Issue. I hope you found a working cable. 👍
