### ISSUE TITLE
No compatible displays found

### ISSUE THREAD

**Issue by Macrox14** [xanderfrangos/twinkle-tray#167]
I have two monitors and the app works well. My issue is when I "(Windows+P)/Second Screen Only" and restart the PC. The slider doesnt appears and only say "No compatible displays found".
In the settings my monitor is detected though
![image](https://user-images.githubusercontent.com/31378074/114275148-037dc000-99e7-11eb-82ab-e114fc7b3f5b.png)

To fix this I have to: "(Windows+P)/Extend" and "(Windows+P)/Second Screen Only" and then slider appears

**Comment by xanderfrangos** [comment]
Others have reported similar issues [here](https://github.com/xanderfrangos/twinkle-tray/issues/163). Can you test [v1.13.4](https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.13.4/Twinkle.Tray.v1.13.4.exe) and [v1.12.3](https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.12.3/Twinkle.Tray.v1.12.3.exe), then let me know if either of those work better? Additionally, if you could copy/paste the information from the Debug menu (bottom left of the Settings window), that would be very helpful as well.

**Comment by Macrox14** [comment]
Here de information from Debug
``{
  "isDev": false,
  "userClosedIntro": true,
  "theme": "default",
  "icon": "mdl2",
  "updateInterval": 250,
  "openAtLogin": true,
  "brightnessAtStartup": true,
  "killWhenIdle": false,
  "remaps": {
    "\\\\?\\DISPLAY#ACI27F6#5&36261769&0&UID4353#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}": {
      "min": 70,
      "max": 100
    },
    "\\\\?\\DISPLAY#GSM5B7F#5&36261769&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}": {
      "min": 40,
      "max": 100
    }
  },
  "hotkeys": {},
  "hotkeyPercent": 10,
  "adjustmentTimes": [],
  "adjustmentTimeIndividualDisplays": true,
  "checkTimeAtStartup": true,
  "order": [
    {
      "id": "\\\\?\\DISPLAY#GSM5B7F#5&36261769&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
      "order": 0
    },
    {
      "id": "\\\\?\\DISPLAY#ACI27F6#5&36261769&0&UID4353#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
      "order": 1
    }
  ],
  "features": {
    "luminance": true,
    "brightness": true,
    "gain": false,
    "contrast": false,
    "powerState": false,
    "volume": false
  },
  "checkForUpdates": true,
  "dismissedUpdate": "",
  "language": "system",
  "settingsVer": "v1.13.5",
  "names": {},
  "analytics": false,
  "scrollShortcut": true,
  "useAcrylic": true,
  "useNativeAnimation": false,
  "uuid": "f63195d1-32ab-4569-9b5f-d141f05dc9f5",
  "branch": "master",
  "linkedLevelsActive": true
}``

Also I tried  v1.13.4 and v1.12.3:
v1.13.4: Same issue
v1.12.3: Fixed issue

If you need anything else tell me

**Comment by xanderfrangos** [comment]
@Macrox14 Would you mind testing this test version and let me know if it helps?

https://1drv.ms/u/s!AiWKFpjcSKRQhsdZbJ7d1xY4Z7PtbA?e=iF2GuF

**Comment by Macrox14** [comment]
> @Macrox14 Would you mind testing this version and let me know if it helps?
> 
> https://1drv.ms/u/s!AiWKFpjcSKRQhsdZbJ7d1xY4Z7PtbA?e=iF2GuF
Same issue :(
Here de debug info
`{
  "isDev": false,
  "userClosedIntro": true,
  "theme": "default",
  "icon": "mdl2",
  "updateInterval": 500,
  "openAtLogin": true,
  "brightnessAtStartup": true,
  "killWhenIdle": false,
  "remaps": {
    "\\\\?\\DISPLAY#ACI27F6#5&36261769&0&UID4353#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}": {
      "min": 90,
      "max": 100
    },
    "\\\\?\\DISPLAY#GSM5B7F#5&36261769&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}": {
      "min": 40,
      "max": 100
    }
  },
  "hotkeys": {},
  "hotkeyPercent": 10,
  "adjustmentTimes": [],
  "adjustmentTimeIndividualDisplays": false,
  "checkTimeAtStartup": true,
  "order": [],
  "features": {
    "luminance": true,
    "brightness": true,
    "gain": false,
    "contrast": false,
    "powerState": false,
    "volume": false
  },
  "checkForUpdates": true,
  "dismissedUpdate": "v1.13.5",
  "language": "system",
  "settingsVer": "v1.13.5-test1",
  "names": {},
  "analytics": false,
  "scrollShortcut": true,
  "useAcrylic": false,
  "useNativeAnimation": false,
  "uuid": "ae192057-0384-46fb-9de7-a266ee3311ef",
  "branch": "master",
  "linkedLevelsActive": true
}`

**Comment by xanderfrangos** [comment]
@Macrox14 Could you try this one?

https://1drv.ms/u/s!AiWKFpjcSKRQhsdb1mLs33hXO-aO3Q?e=srKoVU

**Comment by Macrox14** [comment]
Same issue, but I was doing some tests and I noticed this only happens when:
1. I have 2 monitors
2. **The monitors are linked**
3. I stop projecting in one monitor
4. After restart the machine: "No compatible displays found"

When I tried without the monitors linked, the app works well

**Comment by xanderfrangos** [comment]
I've released [v1.13.6](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.13.6) on GitHub. It should address this issue. Let me know if it helps. If there aren't any new bugs reported in the next few days, I'll roll it out to the Windows Store as well.

**Comment by xanderfrangos** [comment]
Since I haven't heard anything new, I assume everything is OK now. I'm going to close this Issue, but feel free to comment or open a new one if you're still experiencing this bug.
