### ISSUE TITLE
Brightness Slider not hiding until mousepress

### ISSUE THREAD

**Issue by Parth-Mawai** [xanderfrangos/twinkle-tray#168]
While controlling brightness through hotkeys, the brightness slider do not hide automatically until i randomly mouse press on the screen. This happens 8/10 times and i'm trying to notice any pattern but can't find one yet.
This one 👇
![image](https://user-images.githubusercontent.com/76217236/114282597-724c2f00-9a62-11eb-96ae-08096b8fd96f.png)

**Comment by xanderfrangos** [comment]
I've released [v1.13.6](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.13.6) on GitHub. It should address this issue. Let me know if it helps. If there aren't any new bugs reported in the next few days, I'll roll it out to the Windows Store as well.

**Comment by xanderfrangos** [comment]
Since I haven't heard anything new, I assume everything is OK now. I'm going to close this Issue, but feel free to open it again if you're still experiencing this bug.

**Comment by Parth-Mawai** [comment]
> Since I haven't heard anything new, I assume everything is OK now. I'm going to close this Issue, but feel free to open it again if you're still experiencing this bug.

Ya sure, sorry i forgot to close this. Thanks btw
