### ISSUE TITLE
Overlay slider sometimes stays until refocused

### ISSUE THREAD

**Issue by sandorex** [xanderfrangos/twinkle-tray#169]
Most of the time the overlay won't close on it's own when using hotkeys and i have to focus it and then focus something else for it to close

If this is not possible to fix, i would be grateful for option to disable the overlay completely

**Comment by sandorex** [comment]
I just found this is duplicate of #168

**Comment by xanderfrangos** [comment]
I've released [v1.13.6](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.13.6) on GitHub. It should address this issue. Let me know if it helps. If there aren't any new bugs reported in the next few days, I'll roll it out to the Windows Store as well.

**Comment by sandorex** [comment]
Great! Im gonna test it and if i don't see it happen in the next few days im going to close this

**Comment by sandorex** [comment]
Worked great so far! Im closing this now
