### ISSUE TITLE
Do not display the monitor at startup unless you use the scroll wheel to change the brightness

### ISSUE THREAD

**Issue by Stapxs** [xanderfrangos/twinkle-tray#170]
#### *lm not good at english，So I recorded a gif to demonstrate

After booting, the UI showed that there was no display (it showed that there was an available display in the settings), and it resumed after I used the scroll wheel to adjust the brightness.
![1](https://user-images.githubusercontent.com/42486439/114478054-061f2600-9c30-11eb-80ba-2c0f7d2899fb.gif)

(unimportant)After switching win10 theme colors, you need to click the tray to refresh the color matching.
![2](https://user-images.githubusercontent.com/42486439/114478325-8fcef380-9c30-11eb-8c47-5d4f15c6a844.gif)

**Comment by xanderfrangos** [comment]
I've released [v1.13.6](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.13.6) on GitHub. It should address the issues you've brought up. Let me know if it helps. If there aren't any new bugs reported in the next few days, I'll roll it out to the Windows Store as well.

**Comment by Stapxs** [comment]
Sorry for not paying attention to your reply.
The current latest version does not encounter the above problems, it seems that there is no problem.
Thanks for the fix.
