### ISSUE TITLE
Windows 10 Update KB5001330 caused Twinkle Tray to break

### ISSUE THREAD

**Issue by Robert-K** [xanderfrangos/twinkle-tray#174]
Since updating to KB5001330, Twinkle Tray (along with some other applications i.e. Prismatik) fails to start.
I get the following error message:

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
ReferenceError: Cannot access 'mainWindow' before initialization
    at App.handleCommandLine (C:\Users\<my name>\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:2427:34)
    at App.emit (events.js:315:20)

[OK]

**Comment by xanderfrangos** [comment]
Weird. Thanks, Microsoft.

Give this a try and let me know if it helps.
https://1drv.ms/u/s!AiWKFpjcSKRQhsdf8DNVlByZrQVVig?e=yp8y1K

**Comment by xanderfrangos** [comment]
I haven't heard back, but I assume everything is OK now. I didn't have an issue with that Windows update, but this potential fix was included with v1.13.7. I'm going to close this issue, but feel free to comment and/or open again if you're still having issues.
