### ISSUE TITLE
Propose: set custom background color

### ISSUE THREAD

**Issue by YacineBoussoufa** [xanderfrangos/twinkle-tray#178]
I'd like to change the color of the background of the app (not only with light and dark mode), to match other Windows functions, like volume or WiFi.
![Immagine 2021-04-29 130216](https://user-images.githubusercontent.com/46266665/116541046-3d0d6100-a8eb-11eb-9eb3-df827a0ffccc.png)   Twinkle Tray with Dark Mode

![Immagine 2021-04-29 130238](https://user-images.githubusercontent.com/46266665/116541061-41d21500-a8eb-11eb-9587-34a8e401992a.png)   Windows Volume with custom blue color

**Comment by xanderfrangos** [comment]
Hi @YacineBoussoufa, 
If you set the Twinkle Tray theme to "System Preference" (the default) instead of "Dark Mode", it should use a similar background color as the Windows Volume flyout.

**Comment by YacineBoussoufa** [comment]
Oh, didn't notice that xD. Thanks
