### ISSUE TITLE
the window is reduced , how to reset ?

### ISSUE THREAD

**Issue by cuibty** [xanderfrangos/twinkle-tray#180]
![image](https://user-images.githubusercontent.com/12811343/116886229-66b3e880-ac5b-11eb-94f6-10c25a2b9ee9.png)

**Comment by xanderfrangos** [comment]
Hi,
I'm not sure what's wrong here, so here are some suggestions:
- If the window is stuck in full-screen, try pressing F11.
- If everything is tiny after changing monitors, try restarting the app.
- If everything is always tiny, try changing your DPI settings.

I hope that helps! 👍

**Comment by cuibty** [comment]
tks

press Ctrl + -  the window is reduced，other qindows display normally .

![image](https://user-images.githubusercontent.com/12811343/116896111-78e75400-ac66-11eb-872c-2c7dde5a391a.png)

**Comment by xanderfrangos** [comment]
Hmm... it looks like it might be a DPI issue. It may help to set Twinkle Tray to be "Application" controlled DPI. With the Twinkle Tray settings window open, you should be able to complete the following steps:

![Screenshot 2021-05-03 113005](https://user-images.githubusercontent.com/33106561/116897815-b36bd500-ac03-11eb-9a60-1bba17b4b92f.png)

Right-click for steps 1 and 2. Restart Twinkle Tray after changing this setting. I hope that helps.

**Comment by xanderfrangos** [comment]
Since I haven't heard anything else about this issue, I'm going to go ahead and close it. Feel free to comment and/or open it again if you're still having issues.
