### ISSUE TITLE
A javaScript error occurred in the main process

### ISSUE THREAD

**Issue by YXlangran** [xanderfrangos/twinkle-tray#185]
I cannot start the application.
![Snipaste_2021-05-07_12-53-50](https://user-images.githubusercontent.com/56881023/117399554-681f3280-af33-11eb-8d47-d3f1f45dccde.png)

**Comment by xanderfrangos** [comment]
I should have an update out this weekend to fix this or at least give me more information on what's going wrong.

**Comment by YXlangran** [comment]
I can't open the main interface. When I click the tray icon, an error like a screenshot will appear. This error will appear again when I click ok.

**Comment by xanderfrangos** [comment]
I've release v1.13.8 on GitHub, and the Windows Store version should be out in 12-48 hours. Let me know if it helps at all.

**Comment by xanderfrangos** [comment]
I've release v1.13.8 on GitHub, and the Windows Store version should be out in 12-48 hours. Let me know if it helps at all.

**Comment by YXlangran** [comment]
> I've release v1.13.8 on GitHub, and the Windows Store version should be out in 12-48 hours. Let me know if it helps at all.

I have updated it and the same error

**Comment by RgazHTale** [comment]
I have encountered the same error.

**Comment by MarosMacko** [comment]
Hi guys, I have the same problem, when I start the app, the error window keeps popping up. When I click okay, it opens up again immediately and I have to stop the process manually.
```
Windows 11 Pro Insider Preview
Windows Feature Experience Pack 1000.22494.1000.0
```

**Comment by costantino2000** [comment]
I had the same problem (Windows 10). In my case it was caused by a mess I somehow caused some time ago in the windows group policies. Somehow I ended up deleting my user account from the ones listed there, and the program was trying to access the Temp folder in appdata with the "everyone" user, which has limited access to that folder. Granting all folder permissions to "everyone" allowed me to finally run the installer without opening it manually with admin rights, and it also solved the javascript error I also had in other apps.

**Comment by clothedsnake** [comment]
The issue is fixed in the latest Twinkle Tray version. Thanks.

**Comment by onehunkytenor** [comment]
I'm receiving this error regularly. Updated Windows 11, latest version of TwinkleTray. :(

**Comment by deejayreissue** [comment]
> I receive this error regularly after waking up or returning from the screensaver. Updated Windows 11, latest version of TwinkleTray. :(

Yep same here. Windows 11. It doesn't matter what version of TT I am using, I get this error when waking my laptop up from hibernate.

Incredibly frustrating.
