### ISSUE TITLE
Still can't translate.

### ISSUE THREAD

**Issue by maboroshin** [xanderfrangos/twinkle-tray#186]
The following strings have been added as new translation strings, In weblate. However, the local language part is not editable.

* "Hotkeys break linked levels" https://github.com/xanderfrangos/twinkle-tray/commit/3a572b2dcbb3b1f6dd6f4250d43fd583e197dcee#diff-d875a572fd0526bce2f921af679110b17e5fcf0736af5ad6fc311b233a02be8f
* "Turn Off Displays action" https://github.com/xanderfrangos/twinkle-tray/commit/062d25cb0c8bd6cf365ebb742894f5b7cc4c22db#diff-d875a572fd0526bce2f921af679110b17e5fcf0736af5ad6fc311b233a02be8f

If it is not a issue, please close this issue.

**Comment by xanderfrangos** [comment]
I saw this happen with another language, but I don't remember how I fixed it. Unfortunately, I'm having trouble getting on Weblate to look into this. Seems like they're having issues. Once I'm able to get in again, I'll see if I can fix the local language issue.

**Comment by xanderfrangos** [comment]
@maboroshin I think I've fixed it. You should be able to edit them now.

**Comment by maboroshin** [comment]
Thank you. I was able to edit everything.
