### ISSUE TITLE
Acrylic Flyout appears transparent

### ISSUE THREAD

**Issue by Armin2208** [xanderfrangos/twinkle-tray#191]
Since 1.13.8 the flyout pop up animation with activated acrylic has a completely transparent background.
![image](https://user-images.githubusercontent.com/32982430/118496002-05444d00-b724-11eb-846e-5852259847d0.png)
After the animation was played, it returns to the expected look.

**Comment by xanderfrangos** [comment]
Thanks for the bug report! Rolling out v1.13.9 with a fix now. Windows Store version to follow.

**Comment by Armin2208** [comment]
works great now! thanks!
and your standalone updater is awesome.
