### ISSUE TITLE
Twinkle Tray marked as CryptoMalware

### ISSUE THREAD

**Issue by HeyPapito** [xanderfrangos/twinkle-tray#193]
https://imgur.com/a/DIgQpSA

Yes i know exceptions can be added but i think the dev should reach out to Emsisoft and let them know it's not malware

**Comment by xanderfrangos** [comment]
Thanks, I've reported the false-positive to Emsisoft.

**Comment by xanderfrangos** [comment]
From Emsisoft:

> Hello,
> Many thanks for reporting this issue. The file is not detected as malware, but blocked by our Behaviour Blocker. I have checked and whitelisted the file. It should no longer be blocked after the next online update.

With that said, I'm going to go ahead a close this Issue.
