### ISSUE TITLE
MonitorID argument does not work

### ISSUE THREAD

**Issue by D-Code** [xanderfrangos/twinkle-tray#196]
I have four monitors that seem to work fine with Twinkle Tray, except for one thing: When trying to change brightness via the Twinkle Tray command using the MonitorID argument, the brightness will not change, despite the fact that it says OK after executing it.

To reproduce:

1. Lookup the internal name of a monitor
  1.  Right click the tray icon
  2. Click Settings
  3. Go to Monitor Settings Look for "Internal name"
1. Open a command prompt (cmd.exe)
1. Enter command: `"%LocalAppData%\Programs\twinkle-tray\Twinkle Tray.exe" --MonitorID="<Internal name>" --set=50 --Overlay`

Command output: OK

Expected behavior:
Brightness of monitor with specified internal name changes to 50%.

Actual behavior:
Brightness does not change.

**Comment by DeaD3R** [comment]
You have to find MonitorID in device manager. 

1. Go to Monitors, right click your monitor
2. Properties
3. Details
4. Device instance path

The last part, after the last & is the id you're looking for.
In this case it's UID4864
![image](https://user-images.githubusercontent.com/16120515/152534324-3466401e-a19f-4120-adf4-e938dc349add.png)

**Comment by D-Code** [comment]
Thank you very much! Works perfectly!

When reading the Command Line Arguments section, I thought that "internal ID" was referring to the internal name as can be seen in Twinkle Tray's Monitor Settings pane under All Displays.

Out of curiosity, I wondered if the MonitorID value could be retrieved from the command line, and so, I eventually managed to put together this PowerShell script:
```ps1
Get-PnpDevice -Class 'Monitor' -PresentOnly | Format-Table "Name",@{ Label = "MonitorID"; Expression = {($_.InstanceId -Split "&")[-1] }; Align = "Right" }
```
