### ISSUE TITLE
[Bug] Changelog is broken in-app

### ISSUE THREAD

**Issue by simonporte** [xanderfrangos/twinkle-tray#20]
Windows 10 64 bit, build 1909
All the lines of the changelog overlap :

![image](https://user-images.githubusercontent.com/32496803/77587045-77861c80-6ee7-11ea-94f4-eda93100d465.png)

Language set to french, also tested manually set english.
Scaling set to 125% in Windows, tested reverting to 100% to no avail.
Screen resolution does not matter (tested in 3440x1440 and 1920x1080).
Tested resizing the window to no avail.

**Comment by xanderfrangos** [comment]
Thanks for the bug report! I found a workaround to fix it without an update. I'll include a proper fix in the next update.

**Comment by simonporte** [comment]
The fix seems to be working great:

![image](https://user-images.githubusercontent.com/32496803/77631351-bc906a00-6f4c-11ea-9dad-15260d321f05.png)

**Comment by xanderfrangos** [comment]
As it turns out, properly fixing this is more trouble that it's worth. So I just have to make sure I properly format my update notes in the future. Thanks again for reporting the issue.
