### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by huwenhui123** [xanderfrangos/twinkle-tray#204]
### Discussed in https://github.com/xanderfrangos/twinkle-tray/discussions/203

<div type='discussions-op-text'>

<sup>Originally posted by **huwenhui123** June 19, 2021</sup>
本来能使用，更新了系统以后就无法打开了
![Snipaste_2021-06-19_00-55-10](https://user-images.githubusercontent.com/53985387/122593994-06f18f80-d099-11eb-9fab-96d51ff18a85.png)
</div>

**Comment by xanderfrangos** [comment]
Thanks for reporting the issue! Since there are several open Issues for this bug, I'm closing all duplicates. [Subscribe to this Issue for updates as I look into this.](https://github.com/xanderfrangos/twinkle-tray/issues/246)
