### ISSUE TITLE
turn off ONLY one display?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [xanderfrangos/twinkle-tray#206]
how do i turn off just a single monitor instead of both? "turn off displays" -- perhaps would say "turn off display XYZ"?

**Comment by CybaGirl** [comment]
Yes I would love to see this feature as well.

But for now and to do this I am using a program called Display Fusion in case you are interested and need something now.

**Comment by Ericvf** [comment]
Made a PR for this. Check it out here: #216

**Comment by xanderfrangos** [comment]
Closing this issue, as the requested feature is available as of v1.14.0.
