### ISSUE TITLE
Design update for Windows 11

### ISSUE THREAD

**Issue by Seo-Rii** [xanderfrangos/twinkle-tray#220]
In Windows 11, Action Center has changed as follows:

![image](https://user-images.githubusercontent.com/48939845/127770677-ced775c9-f83b-45cf-9ba7-5bd9d82a5cb3.png)

Unlike now, these adjustment panels are slightly spaced from the taskbar and have rounded edges.
Windows 11 is expected to be released in October, do you have any plans to modify the design to fit the new action panel of Windows 11?

**Comment by xanderfrangos** [comment]
While I would like to update Twinkle Tray to better align with the Windows 11 style, there are a few things blocking that right now:

1. I unfortunately haven't had the time nor energy to make any updates to Twinkle Tray as of late. The Issues section is a clear indication of that. If I'm going to do a Windows 11 update, it would be part of [implementing more DDC/CI features](https://github.com/xanderfrangos/twinkle-tray/issues/123), as both will affect the UI dramatically. I do plan to get to it eventually, but I don't have any kind of ETA.
2. I'm not personally going to use Windows 11 for a while. I've run it on my Surface Book 2 and it's a mess. After a few updates I'll consider it.
3. To my knowledge, there isn't a way for me to implement Acrylic or Mica backgrounds with rounded corners. It's just not feasible with Electron. I would have to resort to either having a solid background or an unblurred transparent one (what Twinkle Tray already does with Acrylic disabled). Perhaps if someone creates a WinUI 2/3 module it would work, but I don't have the knowledge to do so. That said, this doesn't 100% stop me from working on a W11 update. It just wouldn't have Acrylic support, which isn't great.

**Comment by xanderfrangos** [comment]
@Seo-Rii I saw you were working on adding Mica support to `electron-acrylic-window`. Have you had any luck with it? I'm thinking of faking Mica by reading the user's wallpaper, or possibly taking a screenshot of the user's desktop before opening the flyout to fake Acrylic.

**Comment by xanderfrangos** [comment]
A work-in-progress screenshot 😀

![11-ddc-preview](https://user-images.githubusercontent.com/33106561/143527022-a42bbc68-1cf2-41ab-a4fa-b408f7ccc65a.jpg)

It's not 100% true to Windows 11's UI, but it's close enough for now. Still not sure what I'll do about Acrylic or Mica.

**Comment by Seo-Rii** [comment]
@xanderfrangos Sadly, it only works when window is transparent. I couldn't find way to use it with non-transparent option.

**Comment by xanderfrangos** [comment]
Hi all, I've posted a beta version of Twinkle Tray [here](https://github.com/xanderfrangos/twinkle-tray/issues/296) with a Windows 11 UI. Give it a look and let me know your thoughts. Thanks!

**Comment by xanderfrangos** [comment]
Closing this issue, as the requested feature is available as of v1.14.0.
