### ISSUE TITLE
Setting the time of day adjustment

### ISSUE THREAD

**Issue by KovalevArtem** [xanderfrangos/twinkle-tray#23]
Implement a 24 hour time format.
![image](https://user-images.githubusercontent.com/36500228/79082928-68023280-7d33-11ea-9782-ae3b6a91851e.png)

**Comment by xanderfrangos** [comment]
I figured this would come up eventually. I haven't yet found a reliable way of detecting if the user's clock is 12 or 24 hours with Node/Electron, but I'll see what I can do.

**Comment by xanderfrangos** [comment]
This feature has been released in v1.9.0! 🎉

**Comment by ahydronous** [comment]
Where is the toggle for this in the UI?

I have 24h time in Windows but not Twinkle Tray
