### ISSUE TITLE
function getLocalization() improvement advise

### ISSUE THREAD

**Issue by wsslsy** [xanderfrangos/twinkle-tray#241]
Found that despite I've set the language setting to default, and the system language was in Chinese Simplified, twinkle-tray still displays in English.

So I check this file: `src\electron.js`, found that the function `getLocalization()` was implented with a bit improvement space.

It's all about this line:

```js
  // Detect language
  localization.detected = (settings.language == "system" ? app.getLocale().split("-")[0] : settings.language)
```

First, this split the locale string by "-" led to confusion of Simplified Chinese(zh-CN) and Traditional Chinese(zh-HK, zh-MO or zh-TW).

Secondly, the localization json file of Chinese was named `zh_Hans.json` and `zh-Hant.json`, the 'zh' splited was used to find file in `src\localization` directory, so it will never find these two.

Even if we use full length locale string to locate this file, we would still found nothing, because the the locale string read from systems that are located in China should be something like this: `zh-CN`, `zh-TW`. Not ~~`zh-Hans`~~ or  ~~`zh-Hant`~~.

I thought the only way to solve this is to rename these files to `zh-CN.json` or `zh-TW.json`, meanwhile change the implementation of `getLocalization()`, use full-length locale string while it starts with 'zh'.

**Comment by xanderfrangos** [comment]
Hey @wsslsy,
Thanks for explaining all of this. I've improved the language detection to correctly route Simplified Chinese and Traditional Chinese to the correct localization files. This will take effect as of the next update.

**Comment by wsslsy** [comment]
Good to hear that I helped, thanks!
