### ISSUE TITLE
Minimum increment for brightness level adjustment is too large

### ISSUE THREAD

**Issue by milthonian** [xanderfrangos/twinkle-tray#250]
The minimum increment for brightness level adjustment by hotkeys is 5%.
That is too large to adjust proper brightness, especially in darker room.
I would like to have an option of 1%.

**Comment by xanderfrangos** [comment]
As of v1.13.10, I've added an option for 1% brightness increments for hotkeys. 👍

**Comment by milthonian** [comment]
Works perfectly. Thanks!
It saves my eyes.
