### ISSUE TITLE
Brightness change on sunset/sunrise

### ISSUE THREAD

**Issue by DEdeVilliers** [xanderfrangos/twinkle-tray#252]
Please add a feature where you can set the brightness of the monitors to change automatically when the sun rises and sets, based on your location. This would be very similar to how windows night light works. This is particularly useful to me as the sunrise and sunset times can vary by up to 2 hours between summer and winter months, and would save me from manually changing the times every few weeks when seasons change.

**Comment by xanderfrangos** [comment]
I believe @Lee182 had once created a fork of Twinkle Tray with this feature. If he or anyone else would like to open a PR that adds an option for "Sunrise" and "Sunset" based on location, I'd be happy to include it.

**Comment by GizmoTheGreen** [comment]
This kind of seperate but would go great hand in hand with this feature or the timers, gradually apply over time. so let's say I wanna go from 100% to 0% over the span of half an hour at sunset or midnight.
right now I have to do manually 4 or more setting and go 25% at a time or something.

**Comment by xanderfrangos** [comment]
Closing this, as several options have since been added that satisfy this request. 👍
