### ISSUE TITLE
[Feature Request] Shortcut to shut screen off

### ISSUE THREAD

**Issue by simonporte** [xanderfrangos/twinkle-tray#26]
There is a button that shut down the screens.
Could you add a hotkey to do the same ?

By the way, the meaning of the moon icon in the tray menu is not very clear.
It made me think of night mode at first sight.
Somethink like this should be more understandable I think
[https://fontawesome.com/icons/lightbulb-slash?style=regular](https://fontawesome.com/icons/lightbulb-slash?style=regular)
This icon is not free, but that is just to give an idea

**Comment by xanderfrangos** [comment]
Sure, I'll add a hotkey for it. 

Regarding the icon, you aren't the first person to think it was for "night mode". Right now I'm using the built-in Windows icons. Using one source makes alignment/updates/coloring easy, so I'd like to avoid adding custom icons if possible. [These](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font) are what I have to work with. I don't see anything else that I think would work, so I may just move the feature to the right-click menu for the tray icon.

**Comment by simonporte** [comment]
Thanks.

The stop presenting would be better than quiet hour imho :
![image](https://user-images.githubusercontent.com/32496803/79512260-5d9cad00-8041-11ea-8170-b51afb691711.png)

**Comment by xanderfrangos** [comment]
Didn't see that one. Good find!

**Comment by xanderfrangos** [comment]
This feature has been released in v1.9.0! 🎉
