### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by ASEM1123** [xanderfrangos/twinkle-tray#263]
Seems like every time I try to load any sort of GUI by clicking on the tray icon, a JavaScript error happens, and keeps spamming errors every 5 seconds until I force close the program. Happened on both the Microsoft Store version and the downloaded .exe.

**Here are the errors I get:**
![javascript errors](https://user-images.githubusercontent.com/39521429/141761633-2a962656-252a-4b5b-afea-4f1ed353d4c8.png)
I'm currently on Windows 10 20H2.

**Comment by joshgermon** [comment]
Same issue here. Windows 11.

**Comment by xanderfrangos** [comment]
Thanks for reporting the issue! Since there are several open Issues for this bug, I'm closing all duplicates. [Subscribe to this Issue for updates as I look into this.](https://github.com/xanderfrangos/twinkle-tray/issues/246)
