### ISSUE TITLE
Request for merging language changes of Traditional Chinese

### ISSUE THREAD

**Issue by toto6038** [xanderfrangos/twinkle-tray#268]
Hi, the current translation for Traditional Chinese is actually of Simplified Chinese, and there are some machine translated strings. To solve the problem, I've updated the strings via Weblate. Please merge them into the next release. Thanks.

**Comment by xanderfrangos** [comment]
Great, thanks! Someone had [opened a PR](https://github.com/xanderfrangos/twinkle-tray/pull/224) a while ago for the same thing. If you don't mind, could you let me know how theirs compares to yours?

Their translation is available here: https://github.com/xanderfrangos/twinkle-tray/pull/224/commits/7af29d094e97bc0b4ab6e17d4b9643cc0e4aa035

**Comment by toto6038** [comment]
I carefully compare both versions. There are minor differences in tone and punctuation style such as English-style quotes "" or Traditional-Chinese-style 「」。My version adheres to [Microsoft's Traditional Chinese localization guide](https://docs.microsoft.com/en-us/globalization/localization/ministyleguides/mini-style-guide-trad-chinese). I updated some strings on Weblate to include @SiderealArt 's, which I think it's better than mine. Thus I believe Weblate version is pretty complete and production-ready. Please include @SiderealArt in terms of credit. Thanks.

**Comment by SiderealArt** [comment]
@toto6038 Hi there, thanks for the efforts! I think that some of the lines can still be adjusted (like line 100 or line 63). 
  `  "SETTINGS_UPDATES_VERSION": "您有 Twinkle Tray {{1}}。",`
   ` "SETTINGS_MONITORS_RATE_0": "極快的",`
Would you like me to send a pull request right away, or should we discuss it first?

And since @toto6038 combined my changes into the file, I'll close #224.

**Comment by toto6038** [comment]
Discussions for improvement are welcome. 
Which conversation method do you prefer? Email, Weblate suggestion, or just reply here is ok.

**Comment by xanderfrangos** [comment]
Weblate is the easiest for me to merge without conflicts. That's why @toto6038's work was accepted over the PR. But as long as I merge the PR before any changes for the language show up in Weblate, a PR would be OK too.

@SiderealArt should probably submit the final adjustments (Weblate or PR) so he gets added to the Contributors list. 

Feel free to use this Issue to discuss, and close it once you've settled on any remaining improvements. 

Thanks for helping with the translation!

**Comment by SiderealArt** [comment]
I'll just reply here then.
```json
"SETTINGS_HOTKEYS_DESC": "Configure hotkeys to adjust the brightness of one or all displays.",
"SETTINGS_HOTKEYS_DESC": "設定快捷鍵以調整顯示器亮度。",
```
The translation for "of one or all displays." is missing.
```json
"SETTINGS_SIDEBAR_TIME": "依照時間調整",
"SETTINGS_TIME_TITLE": "一日中的調整時間點",
```
I think `定時調整` will be much simpler.
```json
"SETTINGS_MONITORS_RATE_0": "極快的",
"SETTINGS_MONITORS_RATE_1": "快速（250 ms）",
"SETTINGS_MONITORS_RATE_2": "正常（500 ms）",
```
`極快的` -> `飛快`, and translate ms to `毫秒`.
```json
 "SETTINGS_GENERAL_RESET_DESC": "按下此按鈕以清除組態。"
```
Isn't it more common to say `設定`, rather than `組態`?
```json
"SETTINGS_GENERAL_BRIGHTNESS_STARTUP_DESC": "Twinkle Tray 啟動時，自動將螢幕亮度恢復為最後記憶的設定。",
```
`自動將螢幕亮度恢復為最後記憶的設定` -> `還原上次套用的亮度`

**Comment by toto6038** [comment]
Thanks for your suggestion. The following is the strings changed to your version and some of my ideas and explanation.

Fixed:
- `SETTINGS_SIDEBAR_TIME`
- `SETTINGS_TIME_TITLE`
- `SETTINGS_MONITORS_RATE_0`
- `SETTINGS_MONITORS_RATE_1`
- `SETTINGS_MONITORS_RATE_2`
- `SETTINGS_GENERAL_BRIGHTNESS_STARTUP_DESC`
- `SETTINGS_GENERAL_RESET_DESC`

For `SETTINGS_HOTKEYS_DESC`, I ignored "one or all" for the reason that the semantics here doesn't require strict difference on the number and it provides enough information to tell the user that the purpose of this section. In fact, the section below this description tells user whether this setting is for one or all displays. So I think it's not a problem.

For `SETTINGS_GENERAL_RESET_DESC`, my original idea was to make it clear between 'configuration' and 'settings'. But in the end I change my mind since it doesn't require strict difference between these two terms here. I change this entry to 按下此按鈕以清除設定值。.

Once again thank you for the effort on advancing Traditional Chinese localization. 😄

**Comment by SiderealArt** [comment]
> For SETTINGS_HOTKEYS_DESC, I ignored "one or all" for the reason that the semantics here doesn't require strict difference on the number and it provides enough information to tell the user that the purpose of this section. In fact, the section below this description tells user whether this setting is for one or all displays. So I think it's not a problem.

Alright. Fair enough.

> @SiderealArt should probably submit the final adjustments (Weblate or PR) so he gets added to the Contributors list.

Originally, I should submit the adjustments. Though I just signed in to Weblate and adjusted the spacing for "INTRO_TITLE", so it shouldn't make much of a difference. I would say it's fine to close this issue now.
