### ISSUE TITLE
--Set=0 not working. (Missing brightness argument.)

### ISSUE THREAD

**Issue by DeaD3R** [xanderfrangos/twinkle-tray#275]
![image](https://user-images.githubusercontent.com/16120515/142722771-f87a9be4-39fe-4df8-b4b0-ad6f2a3d219b.png)

Can set to any value with command line apart from 0, which gives this error: "Missing brightness argument."

Can set to 0 with gui without a problem, only the command line is giving me this error.

Setting any negative value will set the brightness to 0, which achieves my goal.

**Comment by xanderfrangos** [comment]
Oh, whoops, that's a dumb error on my part. I'm surprised it took this long for someone to notice. I'll have it fixed in the next update.

**Comment by xanderfrangos** [comment]
Closing this issue, as the reported bug is fixed as of v1.13.11.
