### ISSUE TITLE
apply last time brightness when new display is connected

### ISSUE THREAD

**Issue by youpie** [xanderfrangos/twinkle-tray#281]
I have a thunderbolt 3 dock which i dock my laptop to when i get home. but that means that if i for example set my monitor to dim at 9 pm and i connect my laptop to my dock at 9:30 pm, the monitor wont dim and that is kind of annoying, it would be really handy if you could turn on that it automatically changed the monitor brightness to the last set brightness when it is connected.

**Comment by xanderfrangos** [comment]
Good idea 👍

As of the next version, Twinkle Tray will attempt to re-apply the last known brightness and any Time Of Day Adjustments when connecting/disconnecting a monitor.

**Comment by xanderfrangos** [comment]
Closing this issue, as the requested feature is available as of v1.13.11 (v1.14.3 for MS Store users).
