### ISSUE TITLE
Minimum Brightness Does Not Go Below 30

### ISSUE THREAD

**Issue by afroeagle** [xanderfrangos/twinkle-tray#283]
Thank you for this tool!

Running the latest version via the Microsoft Store (1.13.10) on Windows 10 x64 latest update as of 11/28/2021. I can change the brightness via the OSD (on-screen display) to '0', but TwinkleTray can only set it down to '30'.

Do I need to edit a registry file?

Thanks

**Comment by xanderfrangos** [comment]
It sounds like either:
1. You might have the Brightness Normalization minimum set to 30 in Twinkle Tray for that display. 
2. There might be a setting enabled in the monitor OSD that's overriding the brightness. (ex. "Adaptive Color and Contrast")
3. The display's implementation of DDC/CI is incorrect. 

I'd recommend looking into those 3 potential reasons. You can test the 3rd option by trying another DDC/CI-enabled tool (ex. ControlMyMonitor or Monitorian). If those apps also only go to 30, then it's just how your monitor is.

**Comment by afroeagle** [comment]
Thank you for your response, @xanderfrangos!

1. Was not applicable
2. Was not applicable
3. This must be the issue as ControlMyMonitor indicated the Brightness value was 0 when the OSD displayed 30.

Thanks again!
