### ISSUE TITLE
[Feature request] User-controllable steps for scrollwheel adjustments over tray icon

### ISSUE THREAD

**Issue by aoleg** [xanderfrangos/twinkle-tray#290]
Currently, there is a setting in "Hotkeys and shortcuts" named "Brightness level adjustment" (How much the brightness should be adjusted using hotkeys).

My feature request is for a similar setting, but controlling how much the brightness should be adjusted using the scrollwheel over the tray icon. Currently, a single flick of the scrollwheel changes 2 levels of brightness. I prefer a more granular control (so level adjustment should be 1 for me), but on some monitors the adjustments can be very slow, and some users may prefer a larger setting.

EDIT: Please consider a simple numeric input for this as the drop-down box does not provide the required level of granularity (e.g. 1, 2, 3, 4, 5 etc.)

**Comment by xanderfrangos** [comment]
Closing this, as the feature was added a while ago. 👍
