### ISSUE TITLE
[Feature Request] Custom hotkey for gaming

### ISSUE THREAD

**Issue by Crumdidlyumshis** [xanderfrangos/twinkle-tray#295]
A feature I would love to see implemented is a custom hotkey for setting a specific custom brightness for each monitor. 

Example: I want to game late at night. The center screen is my focus and I want it 40% brightness and my other two monitors (left and right) at 0% brightness (or possibility to turn them off via software).

Let me know if further explanation is needed!

Thanks for the hard work!

**Comment by pc-v2** [comment]
Add Game Mode Detector may be the way to implement this

**Comment by xanderfrangos** [comment]
I'm considering have a "profiles" systems where you can set brightness levels for your displays, and then assign them to a hotkey, time, or simply switch from them the system tray. It would basically be an expansion of the "Time Adjustments" systems.

**Comment by xanderfrangos** [comment]
Closing this, as several options have since been added that satisfy this request. 👍
