### ISSUE TITLE
[Feature Request] Button To Wake Up External Display

### ISSUE THREAD

**Issue by pc-v2** [xanderfrangos/twinkle-tray#297]

**Comment by xanderfrangos** [comment]
Hi @pc-v2, due to how DDC/CI works, you can usually turn monitors off with it but not on. It will work on some, but not all monitors. There is no way for me to tell, so I would have a button that doesn't work for most people. Because of this, I won't be adding this as a feature. Sorry.

**Comment by pc-v2** [comment]
no problem, thanks :)
