### ISSUE TITLE
Window opens on wrong display when taskbar is on top

### ISSUE THREAD

**Issue by victorleblais** [xanderfrangos/twinkle-tray#302]
Hello, I have noticed that the window with the sliders opens on the wrong monitor when I have my taskbar on top, and another display above that.

Here's an actual screenshot of my setup (large image: 7680x2520) with the issue visible:
![image](https://user-images.githubusercontent.com/4365075/148207628-75ba0eb7-104c-4160-8432-b63119566637.png)

Here's a simpler visual explanation:
![image](https://user-images.githubusercontent.com/4365075/148211536-0367f1e0-2166-46f6-ad83-f82d9118ae9e.png)

Here are some other behaviors I tested:
- When I move the main taskbar to any side of any other display (top, left or right), the window behaves as expected.
- When I move the main taskbar to the bottom, left or right side of the center display, the window behaves as expected.
- When I keep the main taskbar at the top side of the center display, but move the top display's taskbar on all four sides, the window opens near the clock of the top display's taskbar (instead of near the main taskbar at the top of the center display)

It seems that if you have your main taskbar at the top with another display above, Twinkle Tray thinks that the main taskbar is located on the display at the top instead of the one where the actual main taskbar is located.

Note: I've seen issue #158 but I am not 100% sure this is the same issue since 158 uses only one display and has other programs interfering with the "screen size".

My system:
- Twinkle Star v1.13.11
- Windows 10 Pro N, 21H1, 19043.1415
- 3x LG 32GK850F-B monitors (32", 2560x1440, 144Hz, Freesync, HDR) at the center, left and right positions
- 1x LG 29WP60G-B monitor (29", 2560x1080, 75Hz, Freesync, HDR) at the top position

**Comment by victorleblais** [comment]
This issue was resolve in the latest version (v1.14.5) and now the Twinkle Tray panel opens correctly on the bottom monitor if there is a monitor above if the taskbar of the bottom screen is at the top of the display.

If you look at the picture I made above, the tray now opens in the expected location denoted in yellow.

**Comment by xanderfrangos** [comment]
@victorleblais Great! I had added new [settings parameters](https://github.com/xanderfrangos/twinkle-tray/wiki/Advanced-settings-parameters) to help with your issue, but I'm glad my tinkering with the taskbar code fixed it entirely. 👍
