### ISSUE TITLE
Binding the systematic brightness adjustment to the external monitor's brightness

### ISSUE THREAD

**Issue by Asiimoviet** [xanderfrangos/twinkle-tray#306]
Is it possible to bind the external monitor's brightness to the systematic brightness adjustment shortcut?
I have a keyboard from keychron that has brightness adjustment at f1 and f2, it calls something like this:
![image](https://user-images.githubusercontent.com/66727875/149657151-11336319-7742-411f-8aca-63626f6b1ef5.png)
is it possible to use this shortcut to adjust the brightness of an external monitor?

**Comment by Toxblh** [comment]
btw similar to #291
