### ISSUE TITLE
[REQUEST] Enable/Disable overlay OSD

### ISSUE THREAD

**Issue by arpaterson** [xanderfrangos/twinkle-tray#311]
I am using Twinkle Tray and HideVolumeOSD in Windows 11.

HideVolumeOSD gets rid of the upper left volume change overlay OSD, and I believe also the brightness OSD - but I cannot confirm as this is a desktop and I do not use a windows laptop.

I believe Twinkle Tray may be putting the brightness overlay OSD back.

Can this be optional? Some would prefer not to have the overlay.

**Comment by xanderfrangos** [comment]
Closing this issue, as this feature has been implemented as of v1.14.0. You can find it in the Settings window as `General -> Troubleshooting -> Disable overlay`, since most users would use this to fix issues related to fullscreen games.

**Comment by arpaterson** [comment]
I tested and it works as expected, thank you.
