### ISSUE TITLE
[Bug] Scrolling On TwinkleTray Tray Icon Not Working in Windows 11 22581 Build

### ISSUE THREAD

**Issue by pc-v2** [xanderfrangos/twinkle-tray#334]
As Microsoft Introduce new tray I can't adjust it anymore with scrolling on top of it

![image](https://user-images.githubusercontent.com/58063311/159861678-c948b34c-947b-49f4-bf06-1a7669a4b0be.png)

![image](https://user-images.githubusercontent.com/58063311/159861636-4fc29822-1ee4-45ee-9c1a-0d96a9238bd7.png)

**Comment by xanderfrangos** [comment]
It looks like build 22593 partially fixed this (the icon in the system tray flyout works again, but not the system tray itself). Microsoft broke their own APIs when updating the taskbar and appear to be adding them back.

**Comment by xanderfrangos** [comment]
Build 22598 has fully fixed this issue. @pc-v2
