### ISSUE TITLE
[Feature request] Get current contrast toggle

### ISSUE THREAD

**Issue by rp1231** [xanderfrangos/twinkle-tray#346]
![image](https://user-images.githubusercontent.com/47380919/162562340-3100a994-1e5b-49e3-86a3-213d1b99d6e2.png)

It would be nice to have a toggle for get current contrast as well for the same reason that the brightness toggle exists.

Thanks

**Comment by arpaterson** [comment]
generally supporting the same features for contrast as for brightness would be nice.

eg.
Get current contrast
Timed contrast adjustment for all/individual displays.

**Comment by mohitbhatia96** [comment]
I agree. +1 On ability to link brightness and contrast

**Comment by xanderfrangos** [comment]
Closing this, as the toggle mentioned has since been updated to get the latest VCP values (not just brightness). 👍
