### ISSUE TITLE
[FEATURE REQUEST] Custom brightness per app

### ISSUE THREAD

**Issue by fishwithfeet** [xanderfrangos/twinkle-tray#348]
Title self explantory, got to admit that this is one of the coolest apps that exist and thank you for maintaining it :)

**Comment by pc-v2** [comment]
isn't profiles has this feature? how about expanding the app trigger function? add multiple app in app(s) trigger separated with commas

![Image](https://github.com/user-attachments/assets/d49ef4cc-e54c-4e02-aafa-9d66a6f893e6)

**Comment by xanderfrangos** [comment]
It actually works that way already, but it's undocumented. I should add that to the feature description.

**Comment by pc-v2** [comment]
nice!

**Comment by xanderfrangos** [comment]
Closing this, as the feature was implemented a while ago. 👍
