### ISSUE TITLE
Scroll wheel for brightness adjustment on taskbar

### ISSUE THREAD

**Issue by linus-ha** [xanderfrangos/twinkle-tray#35]
It would be great if you could use the scroll wheel above the icon on the taskbar to change the brightness.

**Comment by xanderfrangos** [comment]
I'll see if I can make that happen. 👍

**Comment by xanderfrangos** [comment]
@linus-ha I've uploaded a beta version with the scroll wheel feature. Give it a try and let me know your thoughts.

https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.9.1-beta1/Twinkle.Tray.v1.9.1-beta1.exe

**Comment by linus-ha** [comment]
Thank you for your fast answer/reaction, but sadly this new feature isn't working on my side. 
Is there a way to provide you some more information that would be helpful for finding the problem/solution?


#### All Displays
```
S242HL
Name: S242HL
Internal name: ACR0216
Communication Method: DDC/CI 
Current Brightness: 100
Brightness Normalization: 0 - 100
Order: 0
Key: 5&2937ece8&0&UID37121
ID: \\?\\\?\DISPLAY#ACR0216#5&2937ece8&0&UID37121#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
Serial Number: LR90D0218577

HL198DPB
Name: HL198DPB
Internal name: HSD629C
Communication Method: DDC/CI 
Current Brightness: 100
Brightness Normalization: 0 - 100
Order: 0
Key: 5&2937ece8&0&UID37120
ID: \\?\\\?\DISPLAY#HSD629C#5&2937ece8&0&UID37120#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
Serial Number: 1234567890123
```
##### Settings
```
{
  "isDev": false,
  "userClosedIntro": true,
  "theme": "default",
  "updateInterval": 500,
  "openAtLogin": true,
  "killWhenIdle": false,
  "remaps": {
    "HL198DPB": {
      "min": 0,
      "max": 100
    }
  },
  "hotkeys": {},
  "hotkeyPercent": 10,
  "adjustmentTimes": [],
  "adjustmentTimeIndividualDisplays": false,
  "checkTimeAtStartup": true,
  "order": [],
  "checkForUpdates": true,
  "dismissedUpdate": false,
  "language": "system",
  "settingsVer": "v1.9.1-beta1",
  "names": {},
  "analytics": true,
  "uuid": "4fe287cf-70a7-4fbc-9813-1b42084a6f19",
  "branch": "beta"
}
```

**Comment by xanderfrangos** [comment]
@linus-ha Were you using a mouse or a trackpad? Did you happen to have another instance of Twinkle Tray running?

**Comment by keeganatorr** [comment]
Came here to create the same issue, beta did not work for me either.

**Comment by edo-2313** [comment]
It worked for me, it seems to go up/down of 3% every tick of my scroll wheel. If you need to test something just ask. :)
May I suggested adding the percentage on the tooltip that comes out when you hover over the icon?

**Comment by xanderfrangos** [comment]
The library I started with wasn't great. It has way too many dependencies. I guess I'll be writing some C++...

For now I've removed the feature. Once I have a leaner, more reliable global mouse hook I'll add it back.

**Comment by xanderfrangos** [comment]
@linus-ha @keeganatorr @edo-2313 I've uploaded a new beta for the tray icon scrolling. If you're interested, give it a tray and let me know if the tray icon scrolling works:

https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.9.2-beta1/Twinkle.Tray.v1.9.2-beta1.exe

**Comment by linus-ha** [comment]
@xanderfrangos I am using a mouse and only one instance is running. Installing the C++ Redistribute didn't help. It also has nothing to do with my antivirus software. Rebooting as well as running as administrator didn't help either. 

I even tried different PC's/laptop's and mice. Nothing worked for me so far.

**Comment by edo-2313** [comment]
@xanderfrangos Works without problems for me. Even when I put the icon in the "overflow menu" (that thing that pops up when you click on the arrow pointing up). Can I try something else for you? It's a shame it doesn't work for others...

BTW, the percentage in the tooltip is great!

**Comment by simonporte** [comment]
On the beta 3 :
- 1.9.2 beta 3 is considered as older than 1.9.1, and such Twinkle Tray proposes to update
Correct behavior should be to consider 1.9.1 < 1.9.2 beta 3 < 1.9.2 stable
- Scrolling does work with touchpad, old synaptics driver because old laptop (something like 7 years)
But the tooltip does not update when scrolling, I have to mouve mouse out and over again to see correct value

**Comment by edo-2313** [comment]
@simonporte The tooltip not updating is because tooltips don't actually support updates, they are meant to display a fixed value. Even the system volume doesn't update if I keep my mouse over it while I change the volume using my keyboard... While I was researching that to see if I could do a PR I saw that you can do that in Angular with templates, maybe there is a way?

**Comment by xanderfrangos** [comment]
@linus-ha Try this one:
https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.9.2-beta4/Twinkle.Tray.v1.9.2-beta4.exe

I've disabled error handling, so it should yell at you if the scrolling doesn't work for reasons I can control.

**Comment by xanderfrangos** [comment]
@simonporte 
Regarding updates: I have two update branches (Stable and Beta) and the default is always Stable. If you switch your branch in the debug menu (bottom left of the settings window), then you'll always have the latest beta. I don't really suggest it, as Stable versions may not make it to the beta branch. You may have old versions for a while in the Beta branch.

Regarding the tooltip: what edo-2313 said. Windows tooltips cannot be changed once visible. I do actually update it in the background, but Windows doesn't care. The only way around it is to make my own "tooltip" element from scratch, which I don't have any interest in making.

**Comment by linus-ha** [comment]
Yeah, actually my DPI settings are on 150% and 125%. With the new update (beta4) everything works fine on all DPI settings. 
Thank you very much!
