### ISSUE TITLE
Keeps stealing fullscreen focus

### ISSUE THREAD

**Issue by thejaxi** [xanderfrangos/twinkle-tray#351]
As above. Took me nearly a year to figure this out. Most of my games will/used to (disabled the app for now) automatically alt tab to the desktop when Twinkle Tray was open (in background, not open in foreground/open as is?). Is there a way to make the app stop stealin focus of exclusive fullscreen apps & games? If not... It'd be sad to give up this amazing piece of software. Helps me a ton daily....

Used the tool "Window Focus Logger" to figure this one out. I hope there's a way to get past this. I mean, the app doesn't need focus when the settings are unchanged? It only does when you actually move the sliders/value? ^-^

**Comment by TheJAXi** [comment]
Ehh... Seems like there has been the same issue for a long time now... Might just stick with monitor controls. Can you email me if you find a fix? Or DM/PM? It took me ages to figure out what was wrong (did everythin from clean windows installs to bios resets to figure out at first, ik... had to try everything. didn't realize there was an app for the focus thing before actually googling it... useful shiz... welp... at least now I know.)

**Comment by mrpenguinb** [comment]
This issue occurs constantly, a fix would be very appreciated. Finally figured out what program was causing this behaviour.

**Comment by mrpenguinb** [comment]
**Update as of Feburary 2023**
Twinkle Tray no longer _seems_ to be stealing fullscreen focus. Will keep this comment updated if that changes.

**Comment by xanderfrangos** [comment]
Closing this, as the bug was resolved a while ago. 👍
