### ISSUE TITLE
Brightness window doesn't go away after using key shortcut

### ISSUE THREAD

**Issue by functionOverlord** [xanderfrangos/twinkle-tray#353]
When setting a keyboard shortcut to adjust brightness, the brightness display below sometimes doesn't go away until I click somewhere else with my mouse.
![image](https://user-images.githubusercontent.com/23143971/164916146-3b216571-96dd-4c5b-9bb2-45859a11fe5a.png)

Other times it doesn't show up at all when increasing or decreasing brightness.

This seems to happen completely randomly, and iirc I also had this problem in my previous windows install.

**Comment by xanderfrangos** [comment]
Closing this issue, as the reported bug has been fixed as of v1.13.9.
