### ISSUE TITLE
[Feature Request] Hotkey to set specific brightness value

### ISSUE THREAD

**Issue by OneShen** [xanderfrangos/twinkle-tray#359]
A common use scenario of changing monitor brightness is switching between text reading mode (low brightness) and video/game mode which benefits from maximum monitor brightness. 

It would be great to be able to switch to a specific brightness value with a hotkey (or several for different values), or just add a hotkey to toggle between two specific brightness values that are defined by the user.

**Comment by xanderfrangos** [comment]
Closing this, as the feature was implemented a while ago. 👍
