### ISSUE TITLE
Time Of Day Adjustments firing early.

### ISSUE THREAD

**Issue by Flamebullet** [xanderfrangos/twinkle-tray#361]
Time of day adjustments is still firing early.

When a time of day setting is set, the setting is activated as soon as the time in hour is the same as the setting.

e.g. 
If time of day setting is set to activate at 7:30pm, the brightness setting will be applied as soon as it reached 7pm.

If there is multiple settings in the same hour, e.g. 7pm and 7:30pm, the setting that will be applied will be the later one, so the 7:30pm brightness will be applied.

**Comment by xanderfrangos** [comment]
Closing this, as the bug was resolved a while ago. 👍
