### ISSUE TITLE
1.9. update stopped working

### ISSUE THREAD

**Issue by olyandros** [xanderfrangos/twinkle-tray#37]
After the 1.9. update the app stopped working at all with the following error:
![2020-04-25 09_48_16-Error](https://user-images.githubusercontent.com/64303559/80274359-000bfe80-86da-11ea-8fa7-1f132b2d14d5.jpg)

**Comment by xanderfrangos** [comment]
Hmm... that's no good. Unfortunately I'm not able to get anything useful out of the error. I'll try adjusting the startup process to avoid errors like that in the future. 

I don't think you can downgrade the Windows Store version, so you'll probably want to uninstall and switch to the version here on GitHub.

Here's v1.8.6:
https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.8.6/Twinkle.Tray.v1.8.6.exe

**Comment by xanderfrangos** [comment]
@olyandros If you don't mind, could you test if this version works for you?

https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.9.1-beta2/Twinkle.Tray.v1.9.1-beta2.exe

**Comment by xanderfrangos** [comment]
@olyandros I was able to roll out an update yesterday with a potential fix. Can you confirm if everything is working again for you?

**Comment by olyandros** [comment]
Works fine here now with the new version, thanks!
