### ISSUE TITLE
[Feature Request] Time of Day Adjustment animation duration setting

### ISSUE THREAD

**Issue by WesselKroos** [xanderfrangos/twinkle-tray#370]
Currently the switch to the next brightness value in the Time of Day Adjustment schedule changes pretty harsh within ~5 seconds. I would like to adjust the animation to the next brightness value with a minimum of 0 seconds up to a maximum of 30 minutes. 

This way I don't have to create multiple times that "fake" this slow animation I want. And I also don't have to shift all 50 time values when the sunset/sunrise times change every season. (I have currently about 50 time adjustments configured.)

**Comment by xanderfrangos** [comment]
Closing this, as several options have since been added that satisfy this request. 👍
