### ISSUE TITLE
[Feature Request] WIndows 11 OSD Brightness Slider

### ISSUE THREAD

**Issue by pc-v2** [xanderfrangos/twinkle-tray#379]
keep the old for non Windows 11 users but use new insider beta osd
![image](https://user-images.githubusercontent.com/58063311/178089279-509451fd-c70a-4ad6-91af-ebd3c242009c.png)

Windows 11

![image](https://user-images.githubusercontent.com/58063311/178089289-d85b43a4-56d5-4c8a-b15d-0e99990218f0.png)

Windows 10

**Comment by sayyid5416** [comment]
Why this issue is still open?

**Comment by xanderfrangos** [comment]
Closing this, as the feature was implemented a while ago. 👍
