### ISSUE TITLE
--MonitorID no longer works with the latest update.

### ISSUE THREAD

**Issue by DeaD3R** [xanderfrangos/twinkle-tray#380]
After the update my command `"Twinkle Tray.exe"  --MonitorID="UID4865" --Set=100` No longer does anything. I get the generic Ok response but the brightness doesn't change. `--All` still works, but can't select the specific monitor.

**Comment by xanderfrangos** [comment]
@DeaD3R Thanks for the bug report! `--MonitorID` indeed appears to be broken. I'll get that fixed. In the meantime, it looks like `--MonitorNum` still works. You can use `--List` to see which is which.

**Comment by xanderfrangos** [comment]
@DeaD3R I've released v1.14.1 with a fix for this issue. 👍

**Comment by DeaD3R** [comment]
> @DeaD3R I've released v1.14.1 with a fix for this issue. 👍

Thanks for the quick fix. Can confirm it's working in v1.14.1
