### ISSUE TITLE
Brightness gets automatically changed to random values at random time intervals

### ISSUE THREAD

**Issue by dgacek** [xanderfrangos/twinkle-tray#382]
After the new update, the brightness started resetting to a random value every now and then, even when not idling. 
All time adjustments are disabled, I have 2 linked monitors.

**Comment by xanderfrangos** [comment]
@dgacek Thanks for the bug report! Do you happen to use the "Normalize Brightness" feature?

**Comment by dgacek** [comment]
@xanderfrangos yes I do

**Comment by xanderfrangos** [comment]
Okay, thanks. I'm pretty sure that's what's causing it. I'll address it in v1.14.1 (hopefully today or tomorrow). In the meantime, temporarily disabling normalization should fix it.

**Comment by xanderfrangos** [comment]
@dgacek I've released v1.14.1 which should hopefully fix the issue. Let me know if you're still experiencing it. Thanks!
