### ISSUE TITLE
Add indicator to match volume controls

### ISSUE THREAD

**Issue by kylejohnsonkj** [xanderfrangos/twinkle-tray#39]
When you adjust volume with keyboard shortcuts an indicator pops up in the top left of the screen for a few seconds. Can we get this same thing for the brightness hotkeys?

Btw, I love this app and use it all the time!

**Comment by xanderfrangos** [comment]
Thanks for the feedback, guys. I'll touch up the interface and see if I can get it to work better with fullscreen games.

It's unlikely that the overlay will ever work with "exclusive fullscreen" games. However, newer versions of Windows 10 try to pull games down to a faux "borderless fullscreen", where it should work after I futz with the code some more.

**Comment by kylejohnsonkj** [comment]
That’s fine. Borderless support would be great!

**Comment by xanderfrangos** [comment]
@kylejohnsonkj @jordi-7 @simonporte 

New beta:
https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.10.3-beta2/Twinkle.Tray.v1.10.3-beta2.exe

- Better fullscreen support in games. Borderless fullscreen is supported, exclusive fullscreen is not.
- The overlay UI is much more volume-like. It overlaps with the volume indicator if you do both at the same time, but I prefer that over moving it to a different corner.
- If you click on the overlay, it will stay active until you click off of it.
- Scrolling over the tray icon now activates the overlay as well.

The brightness values can still get janky if you update the brightness of all displays quickly, but that's an unrelated bug.

Regarding the hotkeys not working in some apps, it appears to be an issue with Electron. I might have to re-implement hotkeys with a different library to get it working in all apps. Or it could be a permissions issue. Not sure yet.

**Comment by jordi-7** [comment]
Looks great now vertically and the timeout fix works well!

**Comment by xanderfrangos** [comment]
v1.11.0 is now out on both GitHub and the Windows Store with this feature. 😁
