### ISSUE TITLE
Hotkey popup partially hidden by (left-hand) Windows 10 task bar

### ISSUE THREAD

**Issue by mscha** [xanderfrangos/twinkle-tray#393]
I have the Windows 10 task bar on the left side of the screen.  (Not being able to do that in Windows 11, is my main reason for not upgrading.)
When I change the brightness via a hotkey, the popup that shows the new brightness value, is partially hidden behind the Windows task bar.
<img width="200" alt="twinkle_tray_partially_hidden" src="https://user-images.githubusercontent.com/227365/179400528-e976869b-822c-4467-bf2c-c001c9e45d09.png">

Not a big issue, of course, but it would be nice if the popup would be shifted a bit to the right in this situation.

This is on Windows 10, with Twinkle Tray v1.13.10 from the Microsoft Store.

**Comment by xanderfrangos** [comment]
Should be fixed in v1.14.4/5 👍

**Comment by mscha** [comment]
Thanks!  Looks good in 1.14.5 for me.
