### ISSUE TITLE
[Bug] Twinkle tray applications minimize applications when you move its window

### ISSUE THREAD

**Issue by Recontaminated** [xanderfrangos/twinkle-tray#399]
Windows 10 Pro 10.0.19044
Steps to reproduce.
1) launch twinkle tray, and access the main GUI from the system tray.
2) grab window from top and move it anywhere
twinkle tray lags and other windows minify

**Comment by RobbyMeeker** [comment]
Same build, window movement in general is broken.
![220726183039_EG54fBptgw](https://user-images.githubusercontent.com/49583515/181123731-f5e255c0-8825-443b-8268-626bf17a51c2.gif)

**Comment by xanderfrangos** [comment]
Thanks for the bug report! It's a known issue from the "Acrylic" blur feature, which bleeds into non-Acrylic windows as well. I'm a bit fed up with Microsoft never fixing the core issue in Windows, so I'm just taking it out. The next version will not feature Acrylic for the Settings window. Mica will still work in the Settings window, and both Acrylic and Mica will still work on the flyout.

**Comment by xanderfrangos** [comment]
This has been fixed as of v1.14.4 👍
