### ISSUE TITLE
Is there any way to remove twinkle from alt tab menu?

### ISSUE THREAD

**Issue by thanoskat** [xanderfrangos/twinkle-tray#4]
![Capture](https://user-images.githubusercontent.com/8171250/72696611-8e09a380-3b45-11ea-8898-e10589b6b3c1.PNG)

**Comment by xanderfrangos** [comment]
It looks like it only shows up when using the traditional Alt-Tab menu. I think I've found a workaround. I should have a fix out in v1.7.3 tomorrow.

**Comment by xanderfrangos** [comment]
v1.7.3 is out with the fix. Let me know if you're still seeing the app in the Alt-Tab menu.

**Comment by thanoskat** [comment]
No more twinkle in alt-tab menu for 1.7.3. Thank you!
