### ISSUE TITLE
A javaScript error occurred in the main process

### ISSUE THREAD

**Issue by tdw46** [xanderfrangos/twinkle-tray#40]
I cannot start the application. Not sure what this error means. I've tried restarting my machine and I actually even reset the computer just to see if I can install this. Any ideas what's going on? I would really like to get this working.

![image](https://user-images.githubusercontent.com/10996763/82111396-d868ee80-96f9-11ea-8c71-4ccb0d0c249f.png)

**Comment by xanderfrangos** [comment]
@tdw46 Do you happen to be using Windows 10S (not the regular Windows 10)? It looks like Twinkle Tray can't get your "accent color" from Windows. Try selecting a new color in the _Personalization -> Color_ section of the Windows 10 settings and let me know if that helps.

**Comment by tdw46** [comment]
@xanderfrangos That seems to fix the issue! Strange that it had an issue with that. Though, I did use a theme patcher, so perhaps there were some settings that were non-standard. Thanks for your assistance!
