### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by tooomm** [xanderfrangos/twinkle-tray#400]
I would like to use this little tool without the need of installing it.

Would that be possible and do you consider such a "feature" useful?

**Comment by xanderfrangos** [comment]
I don't have any plans to release a portable version specifically, as Twinkle Tray's app updater leverages the installer. However, if you'd like to scoop out the files yourself to use as a portable version, it's easy to do. You just need to open up the EXE using an archive tool like 7-zip, open the `$PLUGINSDIR` folder, and extract the contents of the `app-64.7z` file inside. In my case, it looks like this:

![make-portable](https://user-images.githubusercontent.com/33106561/180301812-639c60c7-76b4-4c58-8e50-76b38fa9af2f.jpg)

This works for all versions of Twinkle Tray, new and old.

Be sure to turn off "Automatically check for new versions" under the "Updates" settings, so you don't accidentally update the app using the installer.

**Comment by xanderfrangos** [comment]
I'm closing this issue, as I've set up a new wiki page for other users who want to make a portable version: https://github.com/xanderfrangos/twinkle-tray/wiki/Portable-version-of-Twinkle-Tray

**Comment by A248640** [comment]
@xanderfrangos 

Hi!
Check this out: https://github.com/xanderfrangos/twinkle-tray/issues/944#issuecomment-3235667806.

I wish you add additional information to your wiki to make the program true portable, so it will write only to own folder and a user could freely use several programs with different versions without a conflict.
