### ISSUE TITLE
Time Of Day Adjustments always start at 100% Brightness

### ISSUE THREAD

**Issue by VVollmilchsau** [xanderfrangos/twinkle-tray#403]
After the new update, the brightness always starts at the "Normalized" 100% instead from the current value.
During the change, it sometimes resets back to 100% and starts over.

I also have to enable "Get Current Brightness" or else clicking the tray icon starts on 100% too.

I am using this software for a long time and before 1.14 it was working as expected ;)

**Comment by xanderfrangos** [comment]
Odd, I thought I had fixed that in v1.14.2/3. Could you share your settings? You can find them here:

![app-settings](https://user-images.githubusercontent.com/33106561/180323255-f83fad7c-600d-4488-b45a-893f29ce7b01.png)

**Comment by VVollmilchsau** [comment]
Sure :)

```
Settings
These are your raw user settings.
{
  "isDev": false,
  "userClosedIntro": true,
  "theme": "default",
  "icon": "fluent",
  "updateInterval": 500,
  "openAtLogin": true,
  "brightnessAtStartup": false,
  "killWhenIdle": false,
  "remaps": {
    "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357": {
      "min": 11,
      "max": 33
    }
  },
  "hotkeys": {
    "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357__dir1": {
      "monitor": "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357",
      "accelerator": "Shift+Home",
      "direction": 1,
      "active": true
    },
    "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357__dir-1": {
      "monitor": "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357",
      "accelerator": "Shift+End",
      "direction": -1,
      "active": true
    },
    "turn_off_displays__dir1": {
      "monitor": "turn_off_displays",
      "accelerator": "Control+Alt+Insert",
      "direction": 1,
      "active": true
    }
  },
  "hotkeyPercent": 15,
  "adjustmentTimes": [
    {
      "brightness": 40,
      "hour": 6,
      "minute": 0,
      "am": "AM",
      "monitors": {
        "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357": 40
      }
    },
    {
      "brightness": 70,
      "hour": 10,
      "minute": 0,
      "am": "AM",
      "monitors": {
        "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357": 70
      }
    },
    {
      "brightness": 40,
      "hour": 8,
      "minute": 0,
      "am": "PM",
      "monitors": {
        "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357": 40
      }
    },
    {
      "brightness": 25,
      "hour": 11,
      "minute": 36,
      "am": "PM",
      "monitors": {
        "\\\\?\\DISPLAY#AUS272F#5&158da2ac&0&UID4357": 25
      }
    }
  ],
  "adjustmentTimeIndividualDisplays": true,
  "checkTimeAtStartup": false,
  "order": [],
  "monitorFeatures": {},
  "checkForUpdates": true,
  "dismissedUpdate": "",
  "language": "en",
  "settingsVer": "v1.14.3",
  "names": {},
  "analytics": true,
  "scrollShortcut": false,
  "useAcrylic": true,
  "useNativeAnimation": false,
  "sleepAction": "ps",
  "hotkeysBreakLinkedLevels": true,
  "enableSunValley": true,
  "isWin11": true,
  "windowsStyle": "system",
  "hideClosedLid": false,
  "getDDCBrightnessUpdates": true,
  "detectIdleTime": 0,
  "disableWMIC": false,
  "disableWMI": false,
  "disableWin32": false,
  "autoDisabledWMI": false,
  "disableOverlay": false,
  "uuid": "c0582915-31c5-4154-b2b0-c85868f620f9",
  "branch": "master"
}
```

**Comment by xanderfrangos** [comment]
Perfect, thanks! I'll see if I can recreate this issue and get it fixed. 👍

**Comment by VVollmilchsau** [comment]
N1, thank you very much 👍

**Comment by VVollmilchsau** [comment]
@xanderfrangos Sadly not fixed with v1.14.5

But I think, I have a workaround:
Could you please create a toggle to disable "Made Time of Day adjustments slower/smoother (v1.14.0)"
If it jumps directly to the desired value instead of going there slowly, it should fix the issues "start at 100%" and "reset to 100%" :)

**Comment by xanderfrangos** [comment]
Yeah, I'm still working on this one. And yep I can add that.

**Comment by xanderfrangos** [comment]
@VVollmilchsau Can you give this version a try and let me know if it helps? I've adjusted the Time Of Day Adjustments code and added an "Instant" option as well. But see if it works without the "Instant" setting first. Thanks!

https://1drv.ms/u/s!AiWKFpjcSKRQhtgk7xLW2JHKCb2X3g?e=IjcPtk

**Comment by VVollmilchsau** [comment]
@xanderfrangos wow, great work ;)
both features are working as expected and your solution is nicely written into your code.

I only want to mention two negligible things that don't appear on instant-transition (obviously):
1. on app-startup, it still falls back to the old behavior and starts from 100%
2. during ToD-transition when I hover over the tray icon it sometimes resets back to 100% (only noticed it while creating this issue and does not impact normal usage)

Thanks again for your awesome software :)
