### ISSUE TITLE
Idle detection internal display 0%

### ISSUE THREAD

**Issue by provalinf** [xanderfrangos/twinkle-tray#409]
Hello,
I'm not sure if this bug is reported, but the brightness of the internal screen is not restored after being darkened by idle detection.
For this test : Lenovo T15 10th gen
![image](https://user-images.githubusercontent.com/15704455/182337556-9c84e857-13be-40da-a9e3-a96d54dd356a.png)

Thanks 🙂
(v1.14.3)

**Comment by leonknauf** [comment]
I've encountered the same problem on the internal display of my Dell Precision 5530.
![image](https://user-images.githubusercontent.com/33733814/186409417-5a8fc7d3-29f7-4336-9864-504d71e2bcfe.png)
Twinkle Tray v1.14.3

**Comment by provalinf** [comment]
Problem fixed with the build 1.14.5
