### ISSUE TITLE
Decreasing brightness on laptop display when opening twinkle tray

### ISSUE THREAD

**Issue by perlatus** [xanderfrangos/twinkle-tray#41]
Encountering some weird behavior. Saw it on v1.10.0 (from Microsoft Store) and still seeing it on v1.10.1 from the GitHub release.

Almost every time I open the tray, the brightness of my laptop's built-in display decreases, generally following this sequence with some variation: 100, 83, 68, 56, 46, 38, 31, 25, 20, 16, 13, ... 1.

This doesn't happen with my external monitor (connected over USB-C->HDMI) which works perfectly with Twinkle Tray. Only the internal monitor (eDP) is affected. I've set the minimum brightness range to 90 as a workaround and am happy with that, but I thought this bug was worth putting out there.

Video: https://i.imgur.com/szHF6RW.mp4

**Comment by xanderfrangos** [comment]
Yeah, definitely weird behavior. Does this happen when you reset the min/max values for both displays to 0/100? The number pattern looks like a brightness normalization issue, but I'm having trouble replicating it on my end.

**Comment by perlatus** [comment]
Yes.

I think I figured out the conflict. Toggling "Change brightness automatically when lighting changes" checkbox in Windows Settings->Display. For whatever reason, this is always visually checked when I open the settings page, but clicking it stops the brightness reduction in twinkle tray.

**Comment by xanderfrangos** [comment]
Ah, yeah, that option pretty much takes away brightness control from the user.
