### ISSUE TITLE
Problem with brightness on Fujitsu Display

### ISSUE THREAD

**Issue by Sundro00** [xanderfrangos/twinkle-tray#412]
Hello,

I've got a dual monitor set up with a Dell and a Fujitsu B24-8 TE display.

The brightness slider for the Fujitsu on twinkle tray changes unfortunately not the brightness, but the black level of the display, which leads to a very bad image when using it.
On the Dell I have no issue like that.

I use hardware signal over DDC/CI and the display is connected over a display port cable.
OS is Win11 21H2 build.

Is there maybe a possible fix for that bug?

**Comment by vrjohannes** [comment]
Some Fujitsu monitors use vcp code 0x6B intead of vcp code 0x10 for setting brightness in monitor, you can check this with ClickMonitorDDC, in general settings click monitorname, there is an option to use vcp code 0x6B for changing brightness. Or maybe do some tests with softMCCS.

**Comment by Sundro00** [comment]
That was exactly the issue what you stated. I tested it with softMCCS, and it also correctly declares vcp code 0x6B as "White LED backlight control"

0x10 for Luminance.

Is it possible, to manually change the vcp code for that monitor in Twinkle Tray? Or maybe a feature like a optional compatibilty mode for Fujitsu which does it?

![image](https://user-images.githubusercontent.com/73797220/184637859-d8ab8699-dbb6-4906-a958-b1c8368b850c.png)

**Comment by xanderfrangos** [comment]
@Sundro00 

There currently isn't an option to remap the brightness VCP code. However, I can add that. Also, if you can let me know the "Internal name" for the display, I can start a list of VCP code overrides for situations like this.

![internal-name](https://user-images.githubusercontent.com/33106561/184651966-44e232a5-dad2-4819-ab90-9408e0f97303.png)

**Comment by Sundro00** [comment]
That would be really great :)

And sure, the internal name is: FUS087C

![image](https://user-images.githubusercontent.com/73797220/184658485-702b0e8f-5cea-4cc6-bbea-149b37f0e859.png)

**Comment by xanderfrangos** [comment]
Perfect, thanks! I'll try to get a test build posted to this issue later.

**Comment by xanderfrangos** [comment]
@Sundro00 Here's the build. I've already added your display to the list, so in theory it should just work. Let me know if it does.

https://1drv.ms/u/s!AiWKFpjcSKRQhtggKc-uEFVqcSgMuA?e=gns3np

**Comment by Sundro00** [comment]
> @Sundro00 Here's the build. I've already added your display to the list, so in theory it should just work. Let me know if it does.
> 
> https://1drv.ms/u/s!AiWKFpjcSKRQhtggKc-uEFVqcSgMuA?e=gns3np

Wow that was fast. I just tested your build and it's working works flawless now. Changing the brightness on Twinkle Tray, changes actually the brigthness now.

Thank you for your work!
