### ISSUE TITLE
Conflict with League of Legends

### ISSUE THREAD

**Issue by jqrxjkpyjpn** [xanderfrangos/twinkle-tray#414]
After the game is loaded, it will bounce back to the desktop several times after entering the map.

win10，professional，1909

**Comment by xanderfrangos** [comment]
If you're on the most recent version of Twinkle Tray, try turning on the following option from the Settings window:
`General -> Troubleshooting -> Disable overlay`

Let me know if that helps.

**Comment by jqrxjkpyjpn** [comment]
I have already turned on the option, but it still returns to the desktop.

Xander Frangos ***@***.***> 于2022年8月15日周一 04:02写道：

**Comment by stevenya97** [comment]
Same behavior here. Have the Disable Overlay Option turned on, opening any full-screen game causes it to minimize within 5 seconds. WindowsFocusLogger indicates that Twinkle Tray is grabbing focus still. Restarted Twinkle to be sure. Only solution for me is to exit Twinkle Tray

**Comment by xanderfrangos** [comment]
@stevenya97 Could you try this version and see if it helps? 

https://1drv.ms/u/s!AiWKFpjcSKRQhtgncC0ZyobEia2uXA?e=hI2R2P

**Comment by xanderfrangos** [comment]
@stevenya97 After detected display changes (hardware or software), I would have the brightness flyout process restart. This helped with issues related to DPI changes. Unfortunately, restarting the flyout was grabbing focus even though I was not requesting it. I'm not sure how to solve both problems at the same time. I'd rather games not freak out than fix DPI issues, so for now I won't restart the flyout.

**Comment by burt-ie** [comment]
Exactly the same thing has been happening to me. This only recently started happening. Every so often any full screen game will minimise. WindowsFocusLogger shows that twinkle tray is the culprit. The disable overlay option does nothing, it still happens

**Comment by xanderfrangos** [comment]
@burt-ie v1.14.7 should resolve the issue. If you don't have it already, check for updates and it should pop up.

**Comment by burt-ie** [comment]
Seems to have fixed it thanks. I just needed to update it in the windows store

**Comment by xanderfrangos** [comment]
Closing this, as the bug was resolved a while ago. 👍
