### ISSUE TITLE
Mouse issues when cpu at 100%

### ISSUE THREAD

**Issue by tongfeima** [xanderfrangos/twinkle-tray#415]
Hello,
While  I open a software or did something let cpu at 100%,  the mouse pointer will sluggish and move not smoothly.
Sluggish will continue until the cpu usage get down..
I tried 1.10~1.14 versoion, it's the same problem,  but 1.14 verson will caused a very obviously sluggish， 1.10 is a little sluggush, not obviously.
If I quit the Twinkle Tray, this problem disappear.
I am using a HDMI cable and a normal performance of PC.
Hope someone can help me to solve this problem,
Thanks

**Comment by xanderfrangos** [comment]
Hi @tongfeima,
I've made a post over on [this Issue](https://github.com/xanderfrangos/twinkle-tray/issues/410) that's relevant to yours. Take a look and let me know if either of the builds posted there help.

Thanks!

**Comment by xanderfrangos** [comment]
This issue has been resolved as of v1.14.4. 👍
