### ISSUE TITLE
Timed adjustment doesn't work.

### ISSUE THREAD

**Issue by lidoworld** [xanderfrangos/twinkle-tray#421]
In previous versions, the timed adjustment function worked very well. In the latest version it does not work. It does not adjust automatically when the timer is reached.

> These are your raw user settings.
{
  "isDev": false,
  "userClosedIntro": true,
  "theme": "default",
  "icon": "fluent",
  "updateInterval": 500,
  "openAtLogin": true,
  "brightnessAtStartup": true,
  "killWhenIdle": false,
  "remaps": {},
  "hotkeys": {},
  "hotkeyPercent": 10,
  "adjustmentTimes": [
    {
      "brightness": 50,
      "hour": 6,
      "minute": 30,
      "am": "AM",
      "monitors": {}
    },
    {
      "brightness": 0,
      "hour": 12,
      "minute": 0,
      "am": "AM",
      "monitors": {}
    }
  ],
  "adjustmentTimeIndividualDisplays": true,
  "checkTimeAtStartup": true,
  "order": [],
  "monitorFeatures": {
    "AOC2790": {
      "powerState": true,
      "volume": true
    }
  },
  "checkForUpdates": true,
  "dismissedUpdate": "",
  "language": "zh_Hans",
  "settingsVer": "v1.14.3",
  "names": {},
  "analytics": true,
  "scrollShortcut": false,
  "useAcrylic": true,
  "useNativeAnimation": false,
  "sleepAction": "ps",
  "hotkeysBreakLinkedLevels": true,
  "enableSunValley": true,
  "isWin11": true,
  "windowsStyle": "system",
  "hideClosedLid": false,
  "getDDCBrightnessUpdates": false,
  "detectIdleTime": "0",
  "disableWMIC": false,
  "disableWMI": false,
  "disableWin32": false,
  "autoDisabledWMI": false,
  "disableOverlay": false,
  "uuid": "e04b325e-95cf-4061-8152-fdf546bc8922",
  "branch": "master"
}

**Comment by xanderfrangos** [comment]
I think I see what happened. You turned on "Set brightness for individual displays", but doing so doesn't actually set the initial values for each monitor until you move the sliders. That's a bug I need to fix.

![Screenshot 2022-08-22 102417](https://user-images.githubusercontent.com/33106561/185945252-622b9c7e-0420-41f8-8c7e-20f0bfeeee30.png)

If you either turn that setting back off, or adjust each of the sliders above that, it should start working properly.

**Comment by arpaterson** [comment]
I just noticed this too. Adding a new time adjustment seemed to work, but previously entered time adjustments did not work.

**Comment by xanderfrangos** [comment]
In v1.14.4 I've fixed the conversion of `all -> individual` displays not assigning an initial value. So future users won't have the issue. If you're on v1.14.4+, and have the bug from prior versions, you can toggle `Set brightness for individual displays` at it'll be fixed itself going forward.
