### ISSUE TITLE
Twinkle Tray loads abnormally when enabling "Automatically Hide Taskbar" on Windows 10

### ISSUE THREAD

**Issue by Aegim** [xanderfrangos/twinkle-tray#424]
When enabling "Automatically Hide Taskbar" on Windows 10, Twinkle Tray's brightness control appears at the bottom right corner of the screen at first and may appear behind overflow where it shouldn't afterwards. Both restarting or powering off then on my device will then lead to the control panel floating above the taskbar. The position of the control panel is where it would be when not enabling "Smaller Icons" but it is enabled so a gap is present. The same space in between goes for when it is at its default size as well. It loads normally for both taskbar sizes, but not when "Automatically Hide Taskbar" is enabled. It will go back to its normal position after disabling "Automatically Hide Taskbar" and restarting or powering off then on your device. Aside from this, brightness controls still function, though it sits above and not flush with the taskbar. Apologies as I am new to coding and not experienced with programming, so I am unsure as to what could be causing this. Sorry for any confusion my explanation may cause.

**Comment by Aegim** [comment]
![image](https://user-images.githubusercontent.com/111807698/186401025-e3fe1f3c-5b2a-44a5-9f56-4869086efbb6.png)

**Comment by Aegim** [comment]
![image](https://user-images.githubusercontent.com/111807698/186404022-10e8b1e7-9870-4d42-87d4-748b54e3d040.png)

**Comment by xanderfrangos** [comment]
@Aegim It appears that you're using a 3rd party taskbar app, which Twinkle Tray isn't able to interact with. Please see the new `overrideTaskbarGap` setting available in v1.14.4. Documentation is available [here](https://github.com/xanderfrangos/twinkle-tray/wiki/Advanced-settings-parameters). You'll need to figure out the right number to plug in. Base off of your screenshot, it should be `46`.

The Microsoft Store version should be available in the next few days, if you're using that.

Let me know if that resolves the issue. 👍

**Comment by Aegim** [comment]
Apologies as I am new to programming and know practically nothing. Switching out "false," with  "BOTTOM" worked for overriding the position, but when I switched the override gap from "false," to "46," it didn't work for me. Help would be greatly appreciated. 

Best regards 

![image](https://user-images.githubusercontent.com/111807698/187039769-13150026-6f4d-4932-8c88-d17631ec8a31.png)

**Comment by xanderfrangos** [comment]
@Aegim does changing the `overrideTaskbarGap` number (like to 146) and restarting Twinkle Tray do anything? If so, try playing with the number until you get it where it needs to be.

**Comment by Aegim** [comment]
It would appear that my issue happened when it recognized the bar as 46 pixels Y. That should be correct which makes it strange, but "overrideTaskbarGap": 30 cuts into the taskbar a bit, and 31 has a hair's gap in between (it's nitpicky, but it'd be nice as 30.5 bugs it out). Thank you so much for the help! Sorry for not simply playing around with the integer and have a nice day! 
("overrideTaskbarGap": 31) 
![image](https://user-images.githubusercontent.com/111807698/187045316-45c197d7-3263-4281-b902-82c533d8adb7.png)
("overrideTaskbarGap": 30) 
![image](https://user-images.githubusercontent.com/111807698/187045354-a11d8e8b-dacb-4352-8ead-c5037e822d2b.png)
