### ISSUE TITLE
Minor visual oversight

### ISSUE THREAD

**Issue by rp1231** [xanderfrangos/twinkle-tray#428]
![Twinkle_Tray_GnQC6IMpEU](https://user-images.githubusercontent.com/47380919/186665158-be26c5ff-95a6-456f-b400-043f07052008.png)
If the debug tab is activated and the window is made smaller, the debug tab text doesn't get hidden.

**Comment by xanderfrangos** [comment]
Weird, I didn't mean to close this. But I did fix the bug for the next update.
