### ISSUE TITLE
White system tray icon on windows light colour scheme hard to see.

### ISSUE THREAD

**Issue by burt-ie** [xanderfrangos/twinkle-tray#43]
If using Windows 10 light colour scheme (almost white) the Twinkle Tray system tray icon stays white which is hard to see against the background.

Would be nice to have an option to turn it black (maybe auto change) if the Windows theme colour is changed to white.

**Comment by xanderfrangos** [comment]
Well this is odd. There _was_ an icon for the light color scheme. It seems to have stopped working. I'll get that fixed and roll out an update.

**Comment by xanderfrangos** [comment]
Okay, I've rolled v1.10.2, which should restore the light theme icon. If you're using the Windows Store version, it may take up to a day or two before the update is available.

Let me know if you're seeing the icon after the update.

**Comment by burt-ie** [comment]
Excellent, thank you.
I use the windows store version and just got the update, and it's working now.
That was super fast! 

Thank you for such an excellent and much needed app! :)
