### ISSUE TITLE
1.14.5 The brightness slider is very shutter when I drag it

### ISSUE THREAD

**Issue by ForestL18** [xanderfrangos/twinkle-tray#430]
I've updated to the latest version,when I use my mouse to drag the brightness slider,it 's very slow and shutter.(when I drag it,it response after 1-2 seconds)

My PC is windows 10 19044.1889,when I'm back to 1.14.3,the slider is very smooth.

**Comment by xanderfrangos** [comment]
Can you give this version a try and let me know if it helps?
https://1drv.ms/u/s!AiWKFpjcSKRQhtgjrKLxPQHZap9BuA?e=fuR6qV

**Comment by ForestL18** [comment]
> Can you give this version a try and let me know if it helps? https://1drv.ms/u/s!AiWKFpjcSKRQhtgjrKLxPQHZap9BuA?e=fuR6qV

This version is very nice,the experience I drag the slider is as the same as the 1.14.3.

**Comment by xanderfrangos** [comment]
Great, thanks! This fix will be in v1.14.6. You can keep using the test version in the meantime. 👍

**Comment by ForestL18** [comment]
> Great, thanks! This fix will be in v1.14.6. You can keep using the test version in the meantime. 👍

👏
