### ISSUE TITLE
hide some monitor

### ISSUE THREAD

**Issue by k650dg4d2** [xanderfrangos/twinkle-tray#433]
sometime，i will not to adjust some monitor。so，can you hide it。
for example
![QQ截图20220828225151](https://user-images.githubusercontent.com/32454224/187080388-11e6bccf-36c0-4327-927d-31b90be01cbe.png)

i only adjust lf24t35. please let the top one hide。

**Comment by xanderfrangos** [comment]
As of v1.14.6 you can hide specific displays:

![Screenshot 2022-08-31 145353](https://user-images.githubusercontent.com/33106561/187759913-3fe57a7c-8652-4d40-b3c3-d836af4b21d9.png)
