### ISSUE TITLE
Installing Segoe Fluent Icons on Windows 10 causes UI to use Times New Roman

### ISSUE THREAD

**Issue by kmgallahan** [xanderfrangos/twinkle-tray#435]
As per the title - installing Segoe Fluent Icons manually on Windows 10 seems to be the reason my tray UI is using Times New Roman:

![Screenshot 2022-08-30 020207](https://user-images.githubusercontent.com/5379488/187361396-b2f15b10-eb52-4ca0-9fe1-e418a561c098.jpg)

Or at least I can't think of anything else I did that might have caused the problem.

**Comment by xanderfrangos** [comment]
Closing this issue, as this has been fixed since v1.14.7.
