### ISSUE TITLE
[Bug] Twinkle tray increase height every time when you open its window*

### ISSUE THREAD

**Issue by Fiasqo** [xanderfrangos/twinkle-tray#438]
Ye, its happens on Windows 11 when the taskbar located at the TOP of the screen.

OS: Windows 11 Pro x64.
Twinkle Tray: 1.14.6

*Looks like this:
![msedge_0IcdGOJPy3](https://user-images.githubusercontent.com/43761130/187694839-8c16c7ad-2da3-41e1-a1d8-7e5e4f82ffeb.gif)

**Comment by xanderfrangos** [comment]
That's actually kind of funny. 😅

I've fixed the bug for v1.14.7. In the meantime, if you don't use the Microsoft Store version of Twinkle Tray, you can install this beta build.

https://1drv.ms/u/s!AiWKFpjcSKRQhtgoJylaVqKpUSRN5w?e=n73t2v
