### ISSUE TITLE
Turning off monitor via VCP code doesn't work for me

### ISSUE THREAD

**Issue by KiwiMonster364** [xanderfrangos/twinkle-tray#440]
When trying to turn off monitor with VCP code via DDC/CI, nothing happens, only the "OK" message appears. Command used in PowerShell in this example, same happens in CMD tho. When changing powerstate in Twinkle Tray itself to 4 or 5 (debug section), the monitor turns off.

Specs:
Huawei AD80HW (connected via HDMI)
Windows 11 Pro
Twinkle Tray 1.14.6
(Please do not hesitate to ask for more specs if needed)
![image](https://user-images.githubusercontent.com/100710031/187761141-4c0c86c8-8716-49cd-8ded-1a7ed71ef7d4.png)

**Comment by xanderfrangos** [comment]
Whoops. Try v1.14.7.
