### ISSUE TITLE
[Request] Option to disable scroll, when hovering over icon in system tray

### ISSUE THREAD

**Issue by Splike** [xanderfrangos/twinkle-tray#46]
I use a program that lets me change the volume, by hovering the mouse anywhere in the system tray and scrolling.

When hovering over Twinkle Tray, it will change volume and brightness at the same time.

An option to disable this scroll feature would solve my issue.

**Comment by xanderfrangos** [comment]
I'll have an update out in the next few days with this option added. 👍

**Comment by Splike** [comment]
Thanks, looking forward to it!

**Comment by xanderfrangos** [comment]
v1.11.0 is now out on both GitHub and the Windows Store with the feature 😁
