### ISSUE TITLE
Monitor goes black and unresponsive, has to be power cycled

### ISSUE THREAD

**Issue by bverkron** [xanderfrangos/twinkle-tray#462]
Overall things work fine with TT but one of my monitors will go black and never come back 😆.

I _think_ it happens when the monitors go to sleep (via the typical Windows mechanism). Sometimes when I come back to my workstation and wake it the Dell monitor won't come back on or respond _at all_ I've tried the OSD, input buttons, power on / off, etc. It's totally unresponsive and I have to pull the power plug and reconnect it. If I close TT the issue doesn't happen.

These are my current settings. The Dell monitor is the one that has the issue. The HP is fine.

![image](https://user-images.githubusercontent.com/19174503/195430426-eeb5a324-30ac-4427-bc08-76202e361ac4.png)

![image](https://user-images.githubusercontent.com/19174503/195430476-04369d28-da55-4d56-ac69-52e74cd014d3.png)

![image](https://user-images.githubusercontent.com/19174503/195430492-973fa8a4-cf49-43f8-a43e-16329dc9df9f.png)

![image](https://user-images.githubusercontent.com/19174503/195430579-425d164c-cba3-477b-8dff-c7e4d70bae64.png)

![image](https://user-images.githubusercontent.com/19174503/195430609-ea636eaf-395a-42a4-a602-cd942ff6cd56.png)

![image](https://user-images.githubusercontent.com/19174503/195430630-f24fd3a2-9c1b-4da5-9fff-175c5e4b5a30.png)

**Comment by xanderfrangos** [comment]
Hi @bverkron, 

Are you using the _"Turn Off Displays"_ feature in Twinkle Tray (via the flyout or hotkey) to turn off your monitors? If so, do you have it configured to send the "hardware" or "software" signal?

**Comment by bverkron** [comment]
> Are you using the _"Turn Off Displays"_ feature in Twinkle Tray (via the flyout or hotkey) to turn off your monitors?
Nope. Just letting Windows do it's thing. Not explicitly using that feature of TT in any fashion, unless it's getting triggered without me knowing somehow

> If so, do you have it configured to send the "hardware" or "software" signal?
I did check the setting anyway and do recall reading about it in the past and I think I intentionally left it to software because of this warning
![image](https://user-images.githubusercontent.com/19174503/195447323-12776679-1639-487c-94ad-ff481399520b.png)

Even though I'm not using that feature, AFAIK, I will set it to Hardware signal to see if the issue goes away.

**Comment by xanderfrangos** [comment]
The "hardware" option can actually cause the issue, but if you're not using the feature then that's not it. 

The only other thing I can think of is that your monitor doesn't like being communicated with after wake up or power on. Can you try this version of Twinkle Tray and let me know if it helps?
https://1drv.ms/u/s!AiWKFpjcSKRQhtgy-JZsHh4QhD7vZw?e=JAT2MT

**Comment by bverkron** [comment]
I decided to just turn that feature off entirely and see if that makes a difference... even though I'm not actively using it.

I cannot seem to download that test version. Might be the policies on my work PC preventing it. Nothing happens when I hit download (tried several methods) in any of the browsers I tried (Chrome, Brave, Edge). Maybe wrapping it in a .zip would help or publishing elsewhere, not sure.

**Comment by xanderfrangos** [comment]
Does this work? https://1drv.ms/u/s!AiWKFpjcSKRQhtgzWRKsvqO5E7lewA?e=CkAcxM

**Comment by bverkron** [comment]
Same issue but managed to download it on a personal laptop and transfer it via USB. Sneaker net 😂

Installed it and will report back.

FYI disabling the "Turn off display..." feature did not work. Think I verified that it's when windows applies the display sleep not necessarily system sleep. Set the display to sleep after 1 minute and it happened when I tried to wake the displays, but the PC itself was still awake.

**Comment by bverkron** [comment]
@xanderfrangos any thoughts on this one? I found an alternative app that seems to work but I would have to pay for some added features I want like shortcut keys. I'd rather support Twinkle Tray again (donated previously). Feels a bit weird to suggest but if I'm spending money I'd rather use and support Twinkle Tray than the other app.

**Comment by xanderfrangos** [comment]
@bverkron It's difficult for me to debug the issue since it seems to be monitor specific. I've uploaded a build with more options to prevent Twinkle Tray from doing anything on wake up:

https://1drv.ms/u/s!AiWKFpjcSKRQhtg8BBzZGzMcQeUrFQ?e=ucGKfv

The new options are under **General -> Troubleshooting** as **"Disable Auto Apply"** and **"Disable Auto Refresh"**. I'm guessing the **"Disable Auto Apply"** one is more likely to help, but see if either or both resolve the issue.

![auto-apply](https://user-images.githubusercontent.com/33106561/198842700-cd1af2f4-5dee-4fd1-b947-c0d806c16dc3.png)

**"Disable Auto Refresh"** will require you to right-click the system tray icon and hit **"Refresh displays"** to get the current monitors. 

Let me know if that helps. 👍

**Comment by bverkron** [comment]
Thanks. Will give it a try over the next day or two and let you know.

**Comment by bverkron** [comment]
So far enable only "Disable Auto Apply" has worked. Although, as expected I think, it has some side effects. It seems I have to use the Refresh displays option in the system tray to get it to respond to keyboard shortcuts, I think...

Interestingly the same monitor does not have this issue on my personal PC, only on my work PC (laptop). My personal PC is only connected to the Dell display though and via Display Port not HDMI like my work PC so maybe that plays into it.

**Comment by bverkron** [comment]
Turns out neither setting made a difference. Tried them both independently and together and the lock up issue still happens. Strange it doesn't happen on my gaming PC with the same monitor. But again that's a different input and different PC.

Appreciate you trying! Will send over another "thanks" via ko-fi for your efforts.

**Comment by xanderfrangos** [comment]
Thanks, I appreciate it! Wish I had more for you to try, but if it works with another setup then there's something else at play that I'm not sure I can debug.

**Comment by lumpi2k** [comment]
Hi @xanderfrangos I have the exact same problem!

My Setup:

- LG 27GN950
- Nvidia 4080
- plugged in via Displayport
- Windows 11 22H2

I tried out your test build from before and applied these settings:

`{
  "isDev": false,
  "userClosedIntro": true,
  "theme": "default",
  "icon": "fluent",
  "updateInterval": 250,
  "openAtLogin": true,
  "brightnessAtStartup": true,
  "killWhenIdle": false,
  "remaps": {},
  "hotkeys": {
    "all__dir1": {
      "monitor": "all",
      "accelerator": "Control+Alt+.",
      "direction": 1,
      "active": true
    },
    "all__dir-1": {
      "monitor": "all",
      "accelerator": "Control+Alt+,",
      "direction": -1,
      "active": true
    }
  },
  "hotkeyPercent": 10,
  "adjustmentTimes": [],
  "adjustmentTimeIndividualDisplays": false,
  "adjustmentTimeSpeed": "normal",
  "checkTimeAtStartup": true,
  "order": [],
  "monitorFeatures": {},
  "hideDisplays": {},
  "checkForUpdates": true,
  "dismissedUpdate": "",
  "language": "system",
  "settingsVer": "v1.14.8-test2",
  "names": {},
  "analytics": true,
  "scrollShortcut": true,
  "useAcrylic": true,
  "useNativeAnimation": false,
  "sleepAction": "none",
  "hotkeysBreakLinkedLevels": true,
  "enableSunValley": true,
  "isWin11": true,
  "windowsStyle": "system",
  "hideClosedLid": false,
  "getDDCBrightnessUpdates": false,
  "detectIdleTime": 0,
  "overrideTaskbarPosition": false,
  "overrideTaskbarGap": false,
  "disableWMIC": false,
  "disableWMI": false,
  "disableWin32": false,
  "autoDisabledWMI": false,
  "disableOverlay": false,
  "disableMouseEvents": false,
  "disableThrottling": false,
  "userDDCBrightnessVCPs": {},
  "forceLowPowerGPU": false,
  "ddcPowerOffValue": 5,
  "disableAutoRefresh": false,
  "disableAutoApply": true,
  "uuid": "0941c027-97ff-40f6-a81c-bb73f83cd387",
  "branch": "master"
}`

This is the raw monitor data from the app:
`{
  "5&16d372ed&0&UID28929": {
    "id": "\\\\?\\DISPLAY#GSM5B9A#5&16d372ed&0&UID28929",
    "key": "5&16d372ed&0&UID28929",
    "num": 0,
    "brightness": 50,
    "brightnessMax": 100,
    "brightnessRaw": 50,
    "type": "ddcci",
    "connector": "displayport_external",
    "min": 0,
    "max": 100,
    "hwid": [
      "\\\\?\\DISPLAY",
      "GSM5B9A",
      "5&16d372ed&0&UID28929",
      "{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}"
    ],
    "name": "27GN950",
    "serial": "REDACTED",
    "features": {
      "luminance": [
        50,
        100
      ],
      "brightness": false,
      "contrast": [
        70,
        100
      ],
      "powerState": [
        1,
        5
      ],
      "volume": [
        30,
        100
      ]
    },
    "brightnessType": 16,
    "brightnessValues": [
      50,
      100
    ]
  }
}`

As far as I could test this, the "Disable Auto Apply" Setting does work for me, so I guess it would be nice if you could include this setting in the newer builds as well. Thanks for the awesome app!

cheers

**Comment by jdjk7** [comment]
I have the same issue. I am running Windows 10 and I'm using two Dell S272DGF monitors. One is run off internal graphics while the other is run off an Nvidia 1650. Sometimes one (either) or both will be unresponsive when returning from sleep, and won't "wake up" unless I unplug and re-plug the power cables. The issue started when I started using TT, and stops if I turn TT off. I've tried some of the solutions in this thread, but none have seemed to work.

**Comment by chrisportela** [comment]
I logged in with Remote Desktop and I noticed that for whatever reason the app says my monitor doesn't have any DDC/CI features. If I turn the display on/off it'll detect them again and show something on screen. I am going to try disabling the various detection methods and try to narrow that down as the possible cause.

I also disabled getting the brightness every time and have had the "apply brightness at startup" disabled. Also I am using a balanced power plan so my previous assumption that it wasn't working because of that was wrong.

**Comment by bverkron** [comment]
@chrisportela did you have any luck narrowing down the cause? I keep coming back to try it hoping it will magically work but no luck. Twinkle Tray is the best implementation of this kind of software for my needs but this bug makes it unusable for me :(

For context, no other software I've tried causes this issue. It seems to be something specific to TT as far as I can tell. I've tried Monitarian mostly but handful of others without this issue.

**Comment by bverkron** [comment]
This seems to be resolved by turning off the General -> Auto Apply Brightness setting.

**Comment by scanyard** [comment]
@bverkron do you mean the `Apply brightness at startup` setting?

![image](https://github.com/xanderfrangos/twinkle-tray/assets/122397995/04c8f11e-2fb9-434d-944f-e68754a0db24)

Unfortunately, I don't think this is a resolution, as I was just able to reproduce it.

**Comment by bverkron** [comment]
No I'm running the latest beta version which has the Auto Apply Brightness setting.
