### ISSUE TITLE
After sleep twinkle spawns an additional process

### ISSUE THREAD

**Issue by xevgeny** [xanderfrangos/twinkle-tray#472]
Twinkle spawns extra process after each sleep/wake-up cycle. See the picture below after multiple such cycles.

![image](https://user-images.githubusercontent.com/1928818/197579631-2acbceb2-9692-4fa2-abf0-e6eeb7156c75.png)

**Comment by GioPec** [comment]
![image](https://user-images.githubusercontent.com/48129769/198527268-9eb7f778-95ce-4c27-9dcd-291f81cf73ec.png)

I have the same issue

**Comment by benbohmer** [comment]
Same issue here. The list of processes is 4.5 times as long as in the screenshot.

![image](https://user-images.githubusercontent.com/103453816/198867981-1a26f7a8-0bb3-48a9-887a-e3ba5a96fad9.png)

**Comment by xanderfrangos** [comment]
Looking into this. Thanks for the bug report!

**Comment by xanderfrangos** [comment]
If you're not using the Microsoft Store version (meaning the version from twinkletray.com or GitHub), try this beta version and let me know if it helps:
https://1drv.ms/u/s!AiWKFpjcSKRQhtg9FAqPqY3r91G0tg?e=uzrQd0

**Comment by benbohmer** [comment]
Looks better, but only testet a couple hours so far.

![image](https://user-images.githubusercontent.com/103453816/198976703-fec2e297-72cb-404f-a2ee-be008fece8a6.png)

Thank you for the basically immediate response and fix!

**Comment by GioPec** [comment]
I believe it is fixed now, too. Thanks!
