### ISSUE TITLE
using hotkey to change brightness will miss focus from original programs

### ISSUE THREAD

**Issue by ilcpm** [xanderfrangos/twinkle-tray#479]
the focus is now at the browser
![image](https://user-images.githubusercontent.com/36830343/200346886-67cbbb5a-00ea-4f5d-865b-1a628f9cb42d.png)

use hotkey to change brightness, the slider show up, then the focus is gone
![image](https://user-images.githubusercontent.com/36830343/200347181-0ca1504e-ab22-41a0-b898-0c84b603277a.png)

the focus is gone after the slider disappear
![image](https://user-images.githubusercontent.com/36830343/200347476-29fa7887-5ad8-40fe-84c4-1386943e9429.png)

so, if I'm typing in the browser, then use hotkey to change the brightness, the focus will be gone and I can't typing in browser now.

**Comment by xanderfrangos** [comment]
Working on a fix for this. 👍

**Comment by xanderfrangos** [comment]
Closing this, as the bug was resolved a while ago. 👍
