### ISSUE TITLE
Brightness adjustment for Apple Studio Display

### ISSUE THREAD

**Issue by cdwmhcc** [xanderfrangos/twinkle-tray#489]
There is no way to control the brightness of the Apple Studio Display, the LG Ultrafine 5K with the same display panel can adjust the brightness. Hope to add support, thank you very much.

**Comment by xanderfrangos** [comment]
Hi @cdwmhcc,
If Twinkle Tray does not detect the display check if other DDC/CI apps (ControlMyMonitor, ClickMonitorDDC, Monitorian) work. If they do not, then nothing can be done on my end. Apple is not known for supporting open standards, so I'm guessing the monitor won't work with any DDC/CI app. However, I am seeing online that you can install Bootcamp drivers to enable some kind of brightness control.

**Comment by cdwmhcc** [comment]
> I am seeing online that you can install Bootcamp drivers to enable some kind of brightness control.

Thanks for your reply, installing the Boot Camp driver for Windows can indeed adjust the brightness of this monitor through the Boot Camp control panel.
But the design interaction of this panel is too old, not as convenient to use as Twinkle Tray, which I prefer to use.

![image](https://user-images.githubusercontent.com/8030134/203164809-ec82e010-0196-4ee4-835c-57b094e939e4.png)

I encountered some troubles in the process of installing the driver. For example, Apple does not directly provide the download link of Boot Camp for Windows.

I will provide the steps for Windows to install the Boot Camp driver here, hoping to temporarily help users who use this monitor.

### Guide:
1. Download brigader.exe from: https://github.com/timsutton/brigadier/releases
(Windows 11 has python 2.7 installed by default, but if your system does not have python installed, please install it first. https://www.python.org/downloads/release/python-2718/)

2. Run Windows Terminal as admin or open CMD in admin. Type `D:\downloads\brigadier.exe --model MacPro7,1`，Then press enter. 

![image](https://user-images.githubusercontent.com/8030134/203165226-9febbe8b-5ca4-452c-a583-f65bf24a2442.png)

Note: please modify `D:\Tools` to the actual path of the brigadier.exe you downloaded。
This will download the bootcamp drivers to the same directory as brigadier.exe. If not, check your user directory:`C:\Users\[nameofwindowsuser]\bootcamp-[version]`

![image](https://user-images.githubusercontent.com/8030134/203164483-99f6499b-b72f-461b-90db-ab3ac317491b.png)

3. Delete extra drivers that you don't want to install In $WinPEDriver$, i.e. all non-apple related drivers. You can also choose not to delete and keep the default:

![image](https://user-images.githubusercontent.com/8030134/203167698-436017ef-5a0a-4452-a1fa-1f2d0b389ee4.png)

and then in \BootCamp-[version]\BootCamp\Drivers, keep only `Apple` and `Promise` folders

![image](https://user-images.githubusercontent.com/8030134/203166378-5e19061a-6d81-4d74-b050-1af77295e3d0.png)

4. Run Windows Terminal as admin or open CMD in admin, Type `msiexec /i D:\Tools\BootCamp-002-34411\BootCamp\Drivers\Apple\BootCamp.msi` (Note: please modify `D:\Tools\BootCamp-002-34411` to the actual path), Then press enter install, then restart.


Note: This may modify the drive letter of your C drive. If the drive letter of the C drive changes to bootcamp, please do not modify it, otherwise you may not be able to adjust the brightness in the future.

**Comment by zywang0108** [comment]
For anyone landing here from a search: I shipped a working fix for this on the 2024+ firmware (USB PID 0x1118), which is what currently breaks every tool that hardcodes the older 0x1114.

It's a tray daemon (slider + global hotkeys + OSD) wrapping juliuszint/asdbctl — same brightness engine, no driver replacement, no Zadig, no admin once installed. One-click installer or PowerShell one-liner.

https://github.com/zywang0108/asd-tray-windows

Disclosures: not affiliated with Twinkle Tray or Apple. Source (brightness.ahk) is MIT; the shipped brightness.exe is GPL-2.0 because it embeds the AutoHotkey v2 runtime (full breakdown in the repo's License section). asdbctl is MIT; both upstream LICENSE files are bundled in the installer. Posting here because @xanderfrangos's earlier comment said this was out of scope for Twinkle Tray, in case anyone in this thread is still looking.

**Comment by cdwmhcc** [comment]
> For anyone landing here from a search: I shipped a working fix for this on the 2024+ firmware (USB PID 0x1118), which is what currently breaks every tool that hardcodes the older 0x1114.

Twinkle Tray now fully supports Apple Studio Display.
