### ISSUE TITLE
TwinkleTray doesn't detect latest brightness, need to manually refresh displays

### ISSUE THREAD

**Issue by jaintj95** [xanderfrangos/twinkle-tray#499]
Bug was present on 1.14.7 and is also present on 1.14.8
Basically, TwinkleTray is failing to auto-detect the brightness of my monitor and if I try to adjust brightness, nothing happens. I have to manually "refresh displays" everytime. 

Monitor - Gigabyte G27Q (using official HDMI cable if that matters)

**Comment by xanderfrangos** [comment]
Do you mean that you're changing the brightness outside of Twinkle Tray and the app isn't picking up those changes? If so, that's by design. You can enable `DDC/CI Features -> Get Current Brightness` in the settings to force Twinkle Tray to check the brightness every time you open the flyout.

**Comment by jaintj95** [comment]
No. What I mean is that while scrolling up and down over the tray icon, it doesn't really adjust brightness. It seems to lose connection with the monitor. I have to manually click on "refresh displays". Only after that I am able to adjust brightness again scrolling over the icon.

**Comment by xanderfrangos** [comment]
The `Get Current Brightness` option may still help if it's a flaky connection.

**Comment by jaintj95** [comment]
Thank you. That seems to have fixed the issue.
