### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [xanderfrangos/twinkle-tray#5]
I am saddened that the program is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other. Crowdin is free for Open source projects.)

**Comment by xanderfrangos** [comment]
Thanks for the suggestion. I'll look in to how the best handle localization and include support in a future version. 👍

**Comment by jordi-7** [comment]
I can translate into Spanish

**Comment by xanderfrangos** [comment]
@KovalevArtem @jordi-7 If you'd still like to help localize Twinkle Tray, I have everything ready to go. Everyone is welcome to contribute.

To contribute a localization file, do the following:

1. Modify (or create) the appropriate JSON file in [src/localization](https://github.com/xanderfrangos/twinkle-tray/tree/master/src/localization) for your language code (ex. Spanish is ["es"](https://github.com/xanderfrangos/twinkle-tray/blob/master/src/localization/es.json), Russian is ["ru"](https://github.com/xanderfrangos/twinkle-tray/blob/master/src/localization/ru.json). A full list can be found [here](https://www.w3schools.com/tags/ref_language_codes.asp).)
2. Copy the contents of [default.json](https://github.com/xanderfrangos/twinkle-tray/blob/master/src/localization/default.json) to the language file.
3. Translate all string values.
4. Open a pull request for the updated (or new) file.

All of this can be done through GitHub.com, so you don't have to download the Twinkle Tray repository if you don't want to.

If you're comfortable with running Node projects, you can run current code in the master branch to test your localization file. It'll show up in the Settings window, or auto-detect if your region in Windows is set to a country that speaks that language.

**Comment by jordi-7** [comment]
I have added the file for spanish translation.

**Comment by xanderfrangos** [comment]
Thanks for the translation! I've merged it in to the codebase.

**Comment by xanderfrangos** [comment]
[v1.8.0 has been released](https://github.com/xanderfrangos/twinkle-tray/releases) with localization for Japanese and Spanish. 😀

**Comment by jordi-7** [comment]
I spotted one label where the translation is not applied. 
![image](https://user-images.githubusercontent.com/7353995/73396589-014bac00-42e2-11ea-9303-cccbfc3ed390.png)
Everything else is fine, thanks!

**Comment by jordi-7** [comment]
One more, the "clear" label.
![image](https://user-images.githubusercontent.com/7353995/73397309-8a171780-42e3-11ea-80c2-29686268eaa2.png)

**Comment by xanderfrangos** [comment]
Good catch! I'll get those fixed.

**Comment by Leon422** [comment]
The Spanish translation isn't loading for me, the program is still in English. Perhaps you're only loading it if the Windows language is set to Latin American Spanish? I have mine set to Spanish (Spain) and it won't load the translation.

**Comment by Leon422** [comment]
forgot to mention you @xanderfrangos

**Comment by jordi-7** [comment]
I have my pc set to spanish from spain and it works fine

**Comment by Leon422** [comment]
Nevermind, it seems the Windows Store version is still 1.7.3.

**Comment by xanderfrangos** [comment]
@Leon422 Yeah, the Windows Store version always lags behind on updates by several days. It takes a while for Microsoft to approve updates. v1.8.1 is sitting in "certification" now.

**Comment by xanderfrangos** [comment]
@KovalevArtem @edo-2313 @CodeF0x @jordi-7 @Toinane 
Hey all! Thanks again for your help localizing Twinkle Tray. I have a new update (v1.9.0) just about ready. It includes a few new localization strings:
- `SETTINGS_GENERAL_ANALYTICS_TITLE`
- `SETTINGS_GENERAL_ANALYTICS_DESC`
- `SETTINGS_GENERAL_ANALYTICS_LINK`

Any chance you could update the localization files?

**Comment by KovalevArtem** [comment]
@xanderfrangos To simplify the translation process, I suggest using the Weblate service. It's free.
If necessary, I hope @comradekingu can help in setting up.

**Comment by xanderfrangos** [comment]
Thanks for the recommendation. I'll apply for a free license and see how it goes. I'm not expecting the text to change much in the future, but it would be nice to have a better process if it does.

**Comment by comradekingu** [comment]
@orangesunny is the setup guy.

**Comment by orangesunny** [comment]
Hi! 
Nice piece of software! I wish there was something like that when I was using Windows 👍 
Got the request, I will take a look at it tomorrow :)

**Comment by CodeF0x** [comment]
@xanderfrangos 
Hey! I'm happy to help, I'll have a look at it tomorrow!

**Comment by orangesunny** [comment]
Hi all,
can you just rename your `src/localization/default.json` to `en.json`? Once yes, please let me know, and we are fully set-up and ready to go wild 🚀 

Translate libre, translate happily! 😃

**Comment by comradekingu** [comment]
@xanderfrangos Like so #30?

**Comment by xanderfrangos** [comment]
Yep, thanks @comradekingu! @orangesunny, it should be ready now.

**Comment by orangesunny** [comment]
Thanks, @xanderfrangos It is done! You will receive an e-mail shortly. Check out all Weblate’s settings and addons so Twinkle Tray will have translations super polished and you won’t have much work with them.

Enjoy!

**Comment by comradekingu** [comment]
Plenty of source string optimizations to be made. Lets see if the nb_NO translation makes it in first.

**Comment by xanderfrangos** [comment]
@comradekingu Your localization loads and is user-selectable from the Settings window, but won't get automatically selected due to the file name. It should just be `nb.json`. If Weblate chose that file name, is there a way for me to set the naming scheme for new languages?

**Comment by comradekingu** [comment]
Now I remember why I don't use Windows. Every other platform uses "nb_NO", since forever. Is it possible to file a bug report?

**Comment by xanderfrangos** [comment]
@comradekingu That's actually from Electron's [app.getLocale() function](https://www.electronjs.org/docs/api/locales), which uses Chromium's `l10n_util` library. It would be the same on Linux or Mac.

I renamed it to `nb.json` and it didn't break anything with Weblate, so I just have to adjust the filenames whenever someone adds a new language. No big deal.

**Comment by comradekingu** [comment]
@xanderfrangos I think a symlink would be better. If I update nb_NO now, I think it would create nb_NO again(?)

**Comment by xanderfrangos** [comment]
@comradekingu Weblate seems to identify that nb.json is the file now. I don't think it's going to be an issue. Others have updated the existing 2-letter JSON files through Weblate just fine. Looks like it's a one-time issue per language.

**Comment by maboroshin** [comment]
Hi! I'm a Japanese translator.
Will Weblate publish my email address in the translation file?

**Comment by xanderfrangos** [comment]
@maboroshin Not in the translation file, no. However, it looks like it may show up in pull requests.

**Comment by maboroshin** [comment]
@xanderfrangos : Thankyou. I guess that means...[In commit](https://github.com/xanderfrangos/twinkle-tray/commit/4d41fb84be5aff84fca90cad04fba35bd095c5fd) : 
> Co-authored-by:...

I will create a public email address for Weblate.

**Comment by orangesunny** [comment]
@xanderfrangos Please, see https://docs.weblate.org/en/latest/admin/addons.html#squash-git-commits for the configuration of the PR you receive to the repo. There are several choices; we consider `per author` as the fairest one as we want to give translators credit they deserve.

@maboroshin, I am sorry for the inconvenience. Public mail seems reasonable and you can switch it in Weblate account anytime. :)

**Comment by orangesunny** [comment]
> @comradekingu Weblate seems to identify that nb.json is the file now. I don't think it's going to be an issue. Others have updated the existing 2-letter JSON files through Weblate just fine. Looks like it's a one-time issue per language.

Hi, Weblate doesn’t handle this so far, but there are few similar settings:
https://docs.weblate.org/en/latest/formats.html#adding-new-translations

Two issues are discussing this, so feel free to share your view or thumbs up there.
- https://github.com/WeblateOrg/weblate/issues/3246
- https://github.com/WeblateOrg/weblate/issues/3746

**Comment by xanderfrangos** [comment]
@orangesunny The issues you linked seem to be for a different language code format than what Twinkle Tray uses. I set `Language code style` to `BCP style using hyphen as a separator` and Weblate appears to be finding/editing/adding language files exactly as needed. I did some tests in [this PR](https://github.com/xanderfrangos/twinkle-tray/pull/34) and everything is working great. 👍
