### ISSUE TITLE
Amd Eyefinity setup only adjusting one display

### ISSUE THREAD

**Issue by SiPi76** [xanderfrangos/twinkle-tray#502]
Hi I have 3 identical displays that I run as one giant screen using amd Eyefinity.

When Eyefinity is enable, windows only reports 1 (giant) display and so twinkle tray only adjust 1 display of my 3. 

Is that normal ?

Thanks in advance

**Comment by xanderfrangos** [comment]
I don't use AMD graphic, but I believe this is normal for both AMD Eyefinity and NVIDIA Surround. I'm not aware of a workaround other than not using it.

**Comment by SiPi76** [comment]
That's what I thought as well 
thank you for the quick reply !
