### ISSUE TITLE
Automatically adjust the brightness of different programs

### ISSUE THREAD

**Issue by Omoinemie** [xanderfrangos/twinkle-tray#504]
Suggestion: Set different brightness values for different programs, and automatically adjust the brightness when starting the program

**Comment by xanderfrangos** [comment]
Thanks for the suggestion! This is a feature I'm considering, but have not worked on at this time. This is the same as https://github.com/xanderfrangos/twinkle-tray/issues/348, so I'm going to close this issue in favor of that one.
