### ISSUE TITLE
v1.15.0 Beta

### ISSUE THREAD

**Issue by xanderfrangos** [xanderfrangos/twinkle-tray#505]
Hi all,

I have a new update to Twinkle Tray that I would like to have beta tested before release. There are significant under-the-hood changes to the Time of Day Adjustments / Idle Detection systems, along with a Windows 11 style overlay. Time of Day Adjustments should work more reliably now. There are also some new strings that need localization.

The current release notes are:

> ### New in v1.15.0
> 
> **New features & improvements:**
> - Implemented new UI for the hotkey overlay when using the Windows 11 style. 
> - Refactored the Time of Day Adjustments code to be more reliable. 
> - Time of Day Adjustments will now use the user's transition setting under most conditions.
> - Added option to animate between the current and next Time of Day Adjustment time throughout the day.
> - Implemented CLI option to trigger current Time of Day Adjustment.
> - Refactored the Idle Detection system and UI to be more flexible and precise.
> - Added options to the system tray right-click menu for pausing Idle Detection and Time of Day Adjustments.
> - Fixed a bug that could cause excessive CPU/RAM usage at startup.
> - Updated localizations.
> 
> **Other information:**
> - The new Windows 11 hotkey overlay is not intended to be a 1:1 recreation of the native brightness/volume flyout. Please don't open an issue that it isn't exactly the same. Bug reports are welcome.
> - The new Time of Day Adjustment animation setting will more actively keep your scheduled brightness in sync. This may increase CPU usage. It will also be more difficult to manually set brightness due to the scheduled brightness kicking in every minute or so.

The beta is available here:
https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.15.0-beta2

Let me know if you encounter any new issues vs v1.14.8. Thanks!

**Comment by brogers5** [comment]
I just implemented prerelease build support for the Chocolatey package.

While smoke testing a package for beta1, I noticed the Updates page considers the latest stable build (v1.14.8) to be "newer" than the current beta build:

![LatestBuild](https://user-images.githubusercontent.com/6869577/204159789-763be673-3f18-4bca-b851-244008313269.png)

**Comment by xanderfrangos** [comment]
That's by design. The lastest stable build is always the "latest" version. Prerelease builds are only included if you select the Beta branch in the Debug settings. I generally don't want to advertise the prerelease builds in-app unless people really go looking for the option.

**Comment by xanderfrangos** [comment]
Posted beta2 with a few fixes: https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.15.0-beta2

**Comment by causelove94** [comment]
Thank you for adding a new Windows 11-style flyout. It's very nice. Not a big deal, but I have a few suggestions:
1. You should add a slide-down animation when hiding the flyout.
2. The shadow is a bit dark, you should make it lighter.
3. I feel the slide-up animation is not very smooth (like only 20fps).

**Comment by causelove94** [comment]
Thank you for adding a new Windows 11 style flyout. It's very nice. Not a big deal, but I have a few suggestions:
1. You should add a slide-down animation when hiding the flyout.
2. In light mode, the shadow of the flyout is a bit dark, you should make it lighter. (Dark mode is ok).

(I'm using v1.15.2 beta)

**Comment by xanderfrangos** [comment]
> Thank you for adding a new Windows 11 style flyout. It's very nice. Not a big deal, but I have a few suggestions:
> 
> 1. You should add a slide-down animation when hiding the flyout.
> 2. In light mode, the shadow of the flyout is a bit dark, you should make it lighter. (Dark mode is ok).
> 
> (I'm using v1.15.0 beta 2)

Thanks for the suggestions! For a number of reasons, I will not be adding closing animations at this time. I'll take a look at the light mode shadows though and update them in v1.15.1 if needed. 👍

**Comment by xanderfrangos** [comment]
@brogers5 Since several people asked about opting in to beta updates and I plan to use it again for v1.16.0, I'm making the update channel more visible. I don't imagine this will affect the Chocolately stuff in any way, but I figured I'd let you know since you asked about the behavior.

**Comment by brogers5** [comment]
@xanderfrangos, I only saw it as a presentation issue with the UI. As long as you continue to publish via GitHub releases, and mark beta builds as pre-release builds, I don't anticipate any impact to the Chocolatey package. 

Pre-release packages require an extra switch (`--pre` or `--prerelease`) with the first `install` or `upgrade` command, so users would similarly have to opt in from Chocolatey's perspective. If users would prefer to manage updates outside of Chocolatey, this would also be a situation where I'd advise they [`pin`](https://docs.chocolatey.org/en-us/choco/commands/pin) the package to prevent unintentional upgrades. Nothing you'd need to concern yourself with IMO.

**Comment by xanderfrangos** [comment]
I'm up to v1.15.2, so I think I should close this. 

I did end up tweaking the shadows. Thanks for the suggestion @causelove94. 👍
