### ISSUE TITLE
Exception Breakpoint

### ISSUE THREAD

**Issue by kstev99** [xanderfrangos/twinkle-tray#534]
recently when shutting down my computer from Start Menu I get the following Twinkle Tray error

The Exception Breakpoint
A Break Point has been reached.
(0x0000003) occurred in application at location
0x00007FF60C0BA5F8

Windows Insider Version: 22623.1077
Any Idea what is going on?  Does not happen every single time that I reboot, but I have seen the error 4 or 5 times the last week

**Comment by kstev99** [comment]
Whatever it was, I am no longer getting these errors

**Comment by bigplayer-ai** [comment]
#553
