### ISSUE TITLE
Manuel Brightness Adjustments don't stay activated when Automatic Time of Day Adjustments are enabled

### ISSUE THREAD

**Issue by sliceanddice9** [xanderfrangos/twinkle-tray#535]
Hi everyone

My automatic brightness time adjustments for morning, afternoon and evening are as follows:

From _8:00 AM to 4:30 PM_ the monitor is set at a brightness level of **52**, and then from _4:30 PM to 5:30 PM_ it is set at a brightness level of **50**. For the latter evening sessions at _8:30 PM onward_ I have the brightness level on **45.**

I have noticed that within these 'locked times' whenever I want to actually manually change the brightness to whatever level I want, after maybe 15 or 20 minutes the brightness level will always revert back to the specific 'Time of Day Adjustment' brightness level I had it set for.

For example: let's say at 11:00 AM in the morning I want to decrease the brightness level to 49 (even though I have the pre-set 'Time of Day Adjustment' brightness level to be set to **52** from between _8:00 AM to 4:30 PM_), the actual brightness level will only stay at 49 for 15 or 20 minutes before changing back to 52.

I have 'Animate Between Times'  turned to 'Off' 

So my question is: would there be a way where I can KEEP my 'Time of Day Adjustments' enabled but also have the capability of manually changing the brightness level and keeping the manually changed brightness level at the set level whenever I want to?

Using version v1.15.2

**Comment by xanderfrangos** [comment]
Hi @sliceanddice9,

If you want to temporarily pause Time of Day Adjustments, there's an option for it in the right-click menu.

![pause-time-adjustments](https://user-images.githubusercontent.com/33106561/209892279-25359ec1-9476-4e7c-99c3-ab4247b37c77.png)

**Comment by sliceanddice9** [comment]
Thank You!
