### ISSUE TITLE
Use system font?

### ISSUE THREAD

**Issue by musm** [xanderfrangos/twinkle-tray#55]
![image](https://user-images.githubusercontent.com/4319522/86538863-991f7880-bec6-11ea-81a0-43b1097d4f0c.png)

![image](https://user-images.githubusercontent.com/4319522/86538865-9c1a6900-bec6-11ea-964d-88733fb2233c.png)

It would be good if it was possible to use a system font for the tray icon for consistency sake

**Comment by xanderfrangos** [comment]
Not sure I follow. I do use the system fonts (Segoe UI for text, Segoe MDL2 for icons). Are you referring to the "Adjust Brightness" text or the actual icon in the system tray? The only thing that isn't the system font/icon is the Twinkle Tray icon in the system tray.

**Comment by musm** [comment]
I think the main issue is that the text is bolded, whereas the other native system tray text is non-bolded

**Comment by xanderfrangos** [comment]
Ah, I see. That's true. It's bold to make it visually distinct from the text in the list of monitors. I'll play around with the design and come up with something else I'm happy with. Thanks for the suggestion!

**Comment by xanderfrangos** [comment]
v1.11.3 has been released with a revised panel design that should more closely match the Windows design language.
