### ISSUE TITLE
external light sensors

### ISSUE THREAD

**Issue by wangwei8828** [xanderfrangos/twinkle-tray#550]
Hello developer. 
Could you please add a new feature to support external light sensors for automatically adjusting display brightness? Similar to Lunar on macOS?

**Comment by DRSAgile** [comment]
Not a developer, but the solution does not really require the developer to do anything.

If you have a light sensor that provides raw luminance data via virtual serial port or something like that (DIY like in the case of Lunar or with a standard smart home light sensor and a USB ZigBee adapter to insert into your PC), then you can write an automation script via AutoHotKey (AHK) or AutoIt to read the data and then use the TwintkleTray command line support to adjust the brightness accordingly.

**Comment by solomonh3** [comment]
Thumbs up for the Developer to support this directly. Would make it much easier to support external ambient light sensors like this: https://lunar.fyi/sensor

**Comment by Nico04** [comment]
This is marked as completed, but I can't find the feature anywhere ?

**Comment by wangwei8828** [comment]
> This is marked as completed, but I can't find the feature anywhere ?

Haha. Sorry for that. I just don't want to wait it.
