### ISSUE TITLE
[Feature Request] Option to change monitor input

### ISSUE THREAD

**Issue by ricardodimon** [xanderfrangos/twinkle-tray#559]
### User scenario
Working from home, for multi-pc setups, I constantly have to change from "display-port" into "usb-c" during the day.

### Details
It would be cool to be able to do it in this app, **and most importantly, bind it do a hotkey**.
I have a workarround with ControlMyMonitor.exe for now, 
`cmd> ControlMyMonitor.exe /SetValue "${DISPLAY_NAME}" 60 ${INPUT_NUMBER}`
But having multiple softwares solving a similar issue isn't ideal.
Also, In order to also bind it to a hotkey I think I would need something like [[AutoHotkey](https://www.autohotkey.com/)](https://www.autohotkey.com/)

So I would endup with 3 pieces just for managing my displays :)

**Comment by ricardodimon** [comment]
to anyone with a simiar issue, I was able to workarround the AutoHotkey with the help of windows shortcuts + hotkey.
It wasn't working for me until I discovered that only some specific folders that had support for hotkeying a windows shortcut.

[example](https://superuser.com/questions/1175405/hotkey-to-run-a-batch-file-to-hibernate-computer).

**Comment by xanderfrangos** [comment]
Hi @ricardodimon, 
I don't plan to add support for input changing at this time. However, Twinkle Tray does support arbitrary VCP manipulation through the CLI. So you could do the same thing as ControlMyMonitor using the following:

`"%LocalAppData%\Programs\twinkle-tray\Twinkle Tray.exe" --MonitorID="${DISPLAY_NAME}" --VCP="0x60:${INPUT_NUMBER}"`

**Comment by ricardodimon** [comment]
Ty for your time, that will be helpful.
