### ISSUE TITLE
Wrong translation for Language Hindi

### ISSUE THREAD

**Issue by Sahil12524** [xanderfrangos/twinkle-tray#573]
![image](https://user-images.githubusercontent.com/42999635/229470457-9ddea7fb-08d3-484c-945c-c622dc82cde1.png)

there is a typo:
अंग्रेज़ी -> हिंदी

अंग्रेज़ी means english.
change it to हिंदी, means Hindi.

**Comment by xanderfrangos** [comment]
Thanks! I'll have that fixed in the next update.

**Comment by Sahil12524** [comment]
I am closing this issue as the issue was fixed as expected.
![image](https://github.com/xanderfrangos/twinkle-tray/assets/42999635/2c0fa837-c244-44e0-ac27-9d26a55b90b4)
