### ISSUE TITLE
The Binary In Store Is Too Big

### ISSUE THREAD

**Issue by CodeForCSharp** [xanderfrangos/twinkle-tray#58]
It has 72MB. Is it has any problem?
From my personal experience, this software should not need that size.

**Comment by xanderfrangos** [comment]
Twinkle Tray uses [Electron](https://www.electronjs.org/), which includes a copy of the Chromium rendering engine. For that reason, the Store version cannot get much lower than ~70MB (~50MB for the non-Store version).

**Comment by CodeForCSharp** [comment]
Thanks~I get it.
