### ISSUE TITLE
[bug] values are changing back when running multi-user setup

### ISSUE THREAD

**Issue by Nightenom** [xanderfrangos/twinkle-tray#589]
Hi, have two online (logged in) users in Windows, both of them installed twinkle tray, try to change any value and watch it being set back immediately (sometimes the value doesnt visually change back, but monitor brightness changes back). Killing the app for other users fix the problem.

**Comment by Nightenom** [comment]
Dupe of #579

**Comment by Nightenom** [comment]
Hella annoying, I have to kill through task manager and they've to restart the app and kill mine.

**Comment by yiays** [comment]
I solved a similar issue in a project of my own. It's a trivial thing to fix, I'm not sure exactly how it would look in this NodeJS environment, but in my .NET environment, it's as simple as this;

```c#
// Add this in your form's constructor or OnLoad
Microsoft.Win32.SystemEvents.SessionSwitch += SystemEvents_SessionSwitch;

// Handler method
private void SystemEvents_SessionSwitch(object sender, Microsoft.Win32.SessionSwitchEventArgs e)
{
    if (e.Reason == Microsoft.Win32.SessionSwitchReason.SessionLock)
    {
        // The session was locked (Win+L or switch user)
        // Handle lock event here
    }
    else if (e.Reason == Microsoft.Win32.SessionSwitchReason.SessionUnlock)
    {
        // The session was unlocked
        // Handle unlock event here
    }
}
```
