### ISSUE TITLE
[Feature request?] Not recognizing all the monitors

### ISSUE THREAD

**Issue by TKoBuquicious** [xanderfrangos/twinkle-tray#59]
I have 4 monitors plugged in, three regular monitors and one tv. Only one of them is recognized by the program, however. The one that is recognized is the one plugged in through VGA into my motherboard, while the other three are connected to my graphics card. 

Is this a bug or if the program is intended to only recognize the monitors directly plugged in to the internal graphics? If it's the second, I'd like to request support for dedicated graphics card to be added in a future update.

**Comment by xanderfrangos** [comment]
Twinkle Tray does support displays across multiple GPUs (I use NVIDIA + Intel myself). It's possible that your other displays don't support DDC/CI or there's an incompatibility between your GPU and the displays. If you plug any of those 3 displays to your motherboard, does it make a difference?

**Comment by TKoBuquicious** [comment]
Displays do support DDC/CI and it's turned on for all the displays. If there was an incompatibility between the GPU and the displays, wouldn't I have already experienced much bigger problems than being unable to use Twinkle Tray to change the brightness? So far I haven't had any problems with using the monitors and they are all recognized everywhere else in Windows and third party software such as the AMD software (yes, the custom colors feature is turned off for the monitors that have the problem).

**Comment by xanderfrangos** [comment]
Plugging a monitor into a different GPU is a pretty easy way to narrow the scope of the problem. We'd at least know if it's related to GPU hardware/software or not. For instance, NVIDIA Surround and AMD Eyefinity usually break DDC/CI support. I don't have an AMD GPU to test with, so it's possible there are other driver settings that I'm not aware of which break DDC/CI support.

**Comment by tzackin** [comment]
I have 2 monitors, a landscape ACER and a portrait HP.  Only the former is recognized.

**Comment by eveneveneven** [comment]
I have a Zowie XL2540 and it was not detected. My other monitors were turned off/inactive.
When I turned on/activated the others, all 4 monitors were detected.
All monitors are connected to an Nvidia GTX graphics card.

Maybe it's worth noting: The way I turn off the other 3 monitors is usually by using the off button on only one of the monitors, then Windows seems to recognize that I want to disable the other two and only my main monitor (XL2540) is active.

**Comment by xanderfrangos** [comment]
Hi all. Sorry for taking so long to reply. 

To help anyone (now and going forward), I've put together a page outlining why you may be having monitor detection issues with Twinkle Tray: https://github.com/xanderfrangos/twinkle-tray/wiki/Display-Detection-&-Support-Issues

I'll be closing this issue in favor of the centralized, pinned issue here: https://github.com/xanderfrangos/twinkle-tray/issues/81
