### ISSUE TITLE
Level adjust via hotkeys not linked and jump around with multiple displays

### ISSUE THREAD

**Issue by musm** [xanderfrangos/twinkle-tray#60]
![2](https://user-images.githubusercontent.com/4319522/87705458-e673d380-c76b-11ea-9fb3-fd6272cfc8c6.gif)

Hitting the increase/decrease brightness keys on my keyboard, you can see that they are not adjusted equally. The levels are linked.

**Comment by xanderfrangos** [comment]
Yep, that's a bug there. Are you using the normalization feature as well?

**Comment by musm** [comment]
> normalization feature as well

nope 

![image](https://user-images.githubusercontent.com/4319522/87705819-7ade3600-c76c-11ea-9ecb-0eb32c790208.png)

**Comment by xanderfrangos** [comment]
Weird. OK, I'll look into it.

**Comment by musm** [comment]
Still happening although not as bad as before. Could still be a race issue somewhere.

**Comment by xanderfrangos** [comment]
As of v1.13.2, I've further cleaned up stutter/desync issues with the brightness sliders. I can't get them to stutter at all now. This is about as good as it'll get. Going to go ahead and close this issue.
