### ISSUE TITLE
Laptop screen disabled when connected to external monitor yet twinkle tray shows both display levels and tries to adjust them

### ISSUE THREAD

**Issue by musm** [xanderfrangos/twinkle-tray#61]
I'm running an external display with the laptop screen disabled. Yet Twinkle tray shows both screens and tries to adjust both levels under such operations such as hot key level adjustments

**Comment by xanderfrangos** [comment]
@musm I'm working on a fix that should stop the internal display from showing up when the lid is closed. If you've disabled it in Windows and the lid is open, it'll probably still show up in Twinkle Tray. Internal laptop displays are handled differently than external displays, so it's hard to track their status correctly.

**Comment by musm** [comment]
My lid is closed. It's strange, I've noticed that sometimes it shows up and sometimes it doesn't. It's pretty finicky currently.

**Comment by xanderfrangos** [comment]
Yeah, it's a race condition that happens when the full list of display names gets populated before the list of detected internal displays. I noticed it once you pointed it out. Thanks for reporting the issue! I should have an update rolling out in the next few days with the fix.

**Comment by xanderfrangos** [comment]
v1.11.3 is out for download (Windows Store version available soon). This bug should be fixed, but let me know if you're still seeing it.

**Comment by musm** [comment]
I'll reopen if I still see this but for now looks like it's fixed.
