### ISSUE TITLE
mica blur

### ISSUE THREAD

**Issue by shafayetejaman** [xanderfrangos/twinkle-tray#617]
why mica blur doesn't work on the  taskba?
![Screenshot 2023-06-29 191041](https://github.com/xanderfrangos/twinkle-tray/assets/112795252/7e85cc13-549f-4e4d-956f-bf4b79e39451)

**Comment by xanderfrangos** [comment]
It looks like it's working in the screenshot. If you're referring to the blur not reflecting a window being behind the flyout (not shown in the screenshot), that's because the blur effect is solely based on the wallpaper.
