### ISSUE TITLE
Feature Request: Control R,G,B levels individually

### ISSUE THREAD

**Issue by MrShinigamiDa** [xanderfrangos/twinkle-tray#622]
First, thanks for a great App.

Is is possible to add a feature to control RGB levels individually?

My ASUS monitor minimum(zero) brightness is too high which is an issue, I am working around this by decreasing individual RGB levels to bring down the overall brightness.
Hence this feature will be very useful to me, also hopefully for many people to calibrate their display, etc.

Alternatively, maybe a feature to indirectly decrease the brightness below 0 (by using above method) ? - This will be require user to set a preset for pre-calibrated RGB levels of course.

**Comment by MrShinigamiDa** [comment]
On Linux, I created a shell script to decrease brightness below 0 - around ddcutil.
Haven't tried this on windows using twinkle yet.

**Comment by MrShinigamiDa** [comment]
sorry, closed by mistake.

**Comment by xanderfrangos** [comment]
Adjusting additional (arbitrary) VCP codes is coming Soon™️. That said, Twinkle Tray isn't meant to be a calibration app. Something like ControlMyMonitor is better suited for exploring your display's DDC/CI features.

**Comment by MrShinigamiDa** [comment]
Thank you. For lowering brightness below 0 - Could you please suggest lowering the contrast or RGB levels?

**Comment by xanderfrangos** [comment]
v1.16.0 will allow you to link whatever you'd like to the brightness. So you will be able to have the contrast lower with the brightness, effectively doing what you're asking for. Contrast will probably work better than R/G/B levels.

**Comment by MrShinigamiDa** [comment]
Thank you.
