### ISSUE TITLE
"A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by IzayoiAster** [xanderfrangos/twinkle-tray#623]
Even if I re-install the app in microsoft store, the error still exists.
[error log and tmp file](https://github.com/IzayoiAster/TmpFiles/tree/main/error)

**Comment by IzayoiAster** [comment]
I was using the latest stable version of windows11 before. After I updated to Windows Feature Experience Pack 1000.22659.1000.0 and reinstalled twinkle tray, this error still exists😭

**Comment by IzayoiAster** [comment]
@xanderfrangos After I downloaded the release from github and installed it, although there was still an error after the installation, I found that if I stopped all the twinkle tray background processes in task manager, go to the installation folder and ran Twinkle Tray.exe as an administrator, the program started successfully without reporting an error😮

**Comment by xanderfrangos** [comment]
Yeah, that makes sense. The error appears to be that access was denied to one of the modules used by Twinkle Tray. Do you have a 3rd party antivirus, or special permissions set on your PC?

**Comment by IzayoiAster** [comment]
> Yeah, that makes sense. The error appears to be that access was denied to one of the modules used by Twinkle Tray. Do you have a 3rd party antivirus, or special permissions set on your PC?

I have "Huorong Internet Security" on my PC, but after I exit it I still can't launch twinkle tray normally. 
Btw I created a task scheduler (I'm not sure if it's called that in the English version of Windows) running with administrator privileges and turned off the software's original auto-start, so that it can run normally when PC is turned on. Maybe registering a task scheduler with administrator privileges during twinkle tray's installation could solve this problem?

![image](https://cdn.staticaly.com/gh/IzayoiAster/-@master/Other/image.2d6353kmtois.webp)
![image](https://cdn.staticaly.com/gh/IzayoiAster/-@master/Other/image.762aiwlpw4o0.webp)
![image](https://cdn.staticaly.com/gh/IzayoiAster/-@master/Other/image.582p39ghwto0.webp)

**Comment by javacty** [comment]
win 7 64bit SP1
TwinkleTray1.15.3.0
![tw](https://github.com/xanderfrangos/twinkle-tray/assets/4278216/3b59c420-bb2b-4b6e-9181-d491818d97d3)

**Comment by xanderfrangos** [comment]
@javacty Windows 7 is not supported. Only Windows 10 and 11 are supported.

**Comment by IzayoiAster** [comment]
@xanderfrangos Problem solved! When I tried to reinstall again, I found that running the installer in non-administrator mode gave an error.
 ![image](https://cdn.staticaly.com/gh/IzayoiAster/-@master/Other/image.20m1elo0h81s.webp)
According to the error report, I speculate that there is a problem with the permissions of the %TEMP% folder, so I compared it with another computer that is normally running Twinkle Tray, and found that SYSTEM, Administrators and the current user should all have "full control" permissions, while on the computer where the error occurred, the Temp folder only has the read, write and special permissions of Everyone, and the "full control" permission of Administrators (My system language is Chinese, so I'm not sure if my translation of these permissions is accurate). After I changed the permissions to be consistent with another normal computer, completely uninstalled Twinkle Tray and restarted the computer, I successfully installed and started it in non-administrator mode.
（If someone has encountered the same problem as me and found that the permissions cannot be modified, this Zhihu answer may help you 如果有人遇到了和我类似的问题，并且卡在了修改权限这一步，或许可以参考下面这个知乎回答:
![image](https://cdn.staticaly.com/gh/IzayoiAster/-@master/Other/image.1bvxa2zfh41s.webp)
）
