### ISSUE TITLE
brightness slider not showing

### ISSUE THREAD

**Issue by shafayetejaman** [xanderfrangos/twinkle-tray#624]
brightness slider not showing when watching a video in full screen mode, the smaller one that appears when the shortcut key is used.

**Comment by xanderfrangos** [comment]
Hi @shafayetejaman, 
That's the intended behavior. The overlay does not display over windows that mark themselves as "always on top" (like when watching a video) or exclusive fullscreen applications (like many games). Forcing the overlay to display over those causes a number of unwanted side effects (input/window focus loss, games minimizing, performance issues, anti-cheat false flags, etc). An upcoming version of Twinkle Tray (v1.16.0) will allow for you to override that on a per-app basis, but the default behavior will not change.

**Comment by shafayetejaman** [comment]
Thanks.

**Comment by ZhuangQu** [comment]
This makes me look forward to `v1.16.0`.

**Comment by ZhuangQu** [comment]
> This makes me look forward to `v1.16.0`.

**Comment by ZhuangQu** [comment]
> Hi @shafayetejaman, That's the intended behavior. The overlay does not display over windows that mark themselves as "always on top" (like when watching a video) or exclusive fullscreen applications (like many games). Forcing the overlay to display over those causes a number of unwanted side effects (input/window focus loss, games minimizing, performance issues, anti-cheat false flags, etc). An upcoming version of Twinkle Tray (v1.16.0) will allow for you to override that on a per-app basis, but the default behavior will not change.

This makes me look forward to `v1.16.0`.

**Comment by ZhuangQu** [comment]
> Hi @shafayetejaman, That's the intended behavior. The overlay does not display over windows that mark themselves as "always on top" (like when watching a video) or exclusive fullscreen applications (like many games). Forcing the overlay to display over those causes a number of unwanted side effects (input/window focus loss, games minimizing, performance issues, anti-cheat false flags, etc). An upcoming version of Twinkle Tray (v1.16.0) will allow for you to override that on a per-app basis, but the default behavior will not change.

Windows11's built-in sound adjustment panel can be displayed in full screen, like this:
![image](https://github.com/xanderfrangos/twinkle-tray/assets/89310792/7d703ee4-baa4-4754-ae8c-4ab25515f061)
So I think you're overworried.
