### ISSUE TITLE
changing volume 

### ISSUE THREAD

**Issue by serekAlmette** [xanderfrangos/twinkle-tray#629]
when I use the scroll on tray icon to change brightness it changes my brightness alongside volume, I tried uninstalling it or using older version but it didn't worked

**Comment by xanderfrangos** [comment]
Do you happen to use EarTrumpet too? It also supports scrolling over the tray icon and could be interfering.

**Comment by serekAlmette** [comment]
yeah I do, without it twinkle tray works fine its just started doing it recently so I don't know what could it be

**Comment by serekAlmette** [comment]
ok never mind, I forgor I have windhawk installed
