### ISSUE TITLE
Translation status widgets on website

### ISSUE THREAD

**Issue by milotype** [xanderfrangos/twinkle-tray#63]
It would be great if you would add one of those translation status widgets at: https://hosted.weblate.org/widgets/twinkle-tray/#multi on your website https://twinkletray.com/

BTW, I've just translated the app into Croatian at Weblate.

Cheers,
Milo

**Comment by xanderfrangos** [comment]
Good suggestion. 😀 I'm planning to update the website to outline more of the app's features. I'll be sure to include one of those Weblate widgets when I mention localization. In the meantime, I've tossed one of the larger widgets into the GitHub readme.

And thanks for the translation!
