### ISSUE TITLE
Since last update Twinkle Tray dissapeared in Taskbar

### ISSUE THREAD

**Issue by dareooe** [xanderfrangos/twinkle-tray#630]
Tried to manually re-install beta2, but still TT wont show up in tasklbar. Process is running in TaskManager thou

**Comment by xanderfrangos** [comment]
Try this version: https://github.com/xanderfrangos/twinkle-tray/suites/14678330692/artifacts/833106826

**Comment by xanderfrangos** [comment]
Also, please post issues about the v1.16.0 beta here: https://github.com/xanderfrangos/twinkle-tray/issues/626
