### ISSUE TITLE
Monitor does not turn on anymore, black screen

### ISSUE THREAD

**Issue by ozanmikael** [xanderfrangos/twinkle-tray#647]
### Discussed in https://github.com/xanderfrangos/twinkle-tray/discussions/646

<div type='discussions-op-text'>

<sup>Originally posted by **ozanmikael** August 27, 2023</sup>
Hi,

I've been using TwinkleTray for a very long time now and never had issues.
Back then, a couple of months ago, I turned off every monitor with the "turn off Monitors" option inside of TwinkleTray:

![image](https://github.com/xanderfrangos/twinkle-tray/assets/58893898/318c2f4a-68b6-478b-955b-c0e10cd27abd)

One of my monitors didnt turn on anymore and I do not remember how, but I fixed it somehow and it worked again.

Now.. yesterday I did the same. I turned my monitor screens off with that option and one of my monitors are not turning back on anymore.

I tried so much different stuff but I am just not able to turn it back on again and its really frustrating.
The screen is just black and nothing works.

The monitor itself works with different inputs but I cant use it with my PC anymore.

Is there anything I could do to solve this issue?

</div>

**Comment by ozanmikael** [comment]
When I unplug my monitor from my GPU and plug the cable back in, it does turn on for a short period but I do not have any picture.
My monitor just displays, that there is no signal and turns back off.

It definitely recognizes that I plugged out the cable or plug it back in, but I just cant get any picture anymore... this is so frustrating.

**Comment by ozanmikael** [comment]
More Info:
Device-Manager doesnt recognize my monitor anymore.
I also tried "ControlMyMonitor (https://www.nirsoft.net/utils/control_my_monitor.html)" but it also doesnt recognize my dead monitor anymore.

**Comment by ozanmikael** [comment]
Case closed.
It works again now.

I did a factory reset and it works now :) I should have done that way earlier.

**Comment by xanderfrangos** [comment]
This is why I have warnings on the DDC/CI power state features. Any issues I've heard off are recoverable, but users tend to (understandably) freak out when their monitor doesn't turn back on. Glad a reset worked for you. 👍
