### ISSUE TITLE
weblate error

### ISSUE THREAD

**Issue by maboroshin** [xanderfrangos/twinkle-tray#68]
An error occurs when editing on weblate. It may be a temporary error on the site, but I report it.

Because I choose japanese, The error message is Japanese, and contains the English word "checksum".

error message:
```パラメータ checksum 内でエラー: この項目は必須です。```

**Comment by xanderfrangos** [comment]
Weird, I'm not seeing anything like that. I'm guessing it was a temporary problem on their end?

**Comment by maboroshin** [comment]
It's fixed. Thank you for your concern.
