### ISSUE TITLE
When will HDR brightness control be added?

### ISSUE THREAD

**Issue by Askejm** [xanderfrangos/twinkle-tray#687]
Works fine on my SDR monitor, but on my HDR monitor the brightness slider does nothing

**Comment by xanderfrangos** [comment]
HDR in Windows is a mess, and HDR brightness control over DDC/CI seems to vary per monitor (if it's even supported on a given monitor at all). There's unlikely to ever to be a one-size-fits-all solution. I don't own a true HDR monitor, so I don't have a good device to test with. It's also not a huge priority for me at the moment. Maybe once I finally get v1.16.0 I can give it another look. 

See issue https://github.com/xanderfrangos/twinkle-tray/issues/97 for more info.

I'm going to close this issue in favor of the issue linked above.

**Comment by Askejm** [comment]
alright the monitor I got is aw3423dwf id be willing to test if needed

**Comment by xanderfrangos** [comment]
@Askejm The most useful thing would be to see if there's a VCP code for your monitor that controls HDR brightness using a tool like [ControlMyMonitor](https://www.nirsoft.net/utils/control_my_monitor.html). `0x10` is likely SDR brightness. If your monitor supports adjusting HDR brightness over DDC/CI, I can add your model to it as a feature eventually. And at the bare minimum, you would be able to add support yourself in v1.16.0, since custom VCP code sliders are a feature there.

**Comment by Askejm** [comment]
Actually, after messing around with the manufacturer specific sliders. It seems E0 is a toggle between normal and reduced brightness. 
Here is what the others do if you or anyone else would be curious: 
- E1 starts pixel refresh
- E2 does nothing 
- E3 does nothing
- E5 does nothing 
- E6 does nothing
- E7 does nothing
- EC changes toggles presets 
- ED does nothing
- F0 changes color preset mode (unavailable in HDR)
- F1 does nothing 
- F2 does nothing 
- F4 toggles a bunch of modes like 1 hour timer, display alignment, displaying Hz etc. 
- FD does nothing
I imagine most of these don't do anything because I have HDR enabled.

**Comment by xanderfrangos** [comment]
@Askejm That's unfortunately not surprising. I don't think many monitors will offer HDR brightness over DDC. And from the PDF you linked, it doesn't seem like the OSD even has HDR brightness controls (like with SDR). Unless it shares the SDR slider.

**Comment by Askejm** [comment]
@xanderfrangos Rip, that sucks. I will just have to make do with E0 then when 1.16 releases

**Comment by Askejm** [comment]
@xanderfrangos I just realized
![image](https://github.com/xanderfrangos/twinkle-tray/assets/55248977/998b1d0d-afde-4ab3-81a7-dc9445033c3b)
This setting is what controls the brightness on my HDR monitor. The HDR monitor just gets told by windows how many nits to display. So would it be possible to have the sliders change this value? That would be really practical. It's in system>display>hdr>SDR content brightness

**Comment by Askejm** [comment]
@xanderfrangos Hello again. I see that 1.16 was released and as I mentioned above I see that E0 triggers low brightness. I added the DDI/CI feature, but how do I toggle it? I don't see it in the menu even after restarting the app. Thank you
