### ISSUE TITLE
hope support for the Apple Studio Display

### ISSUE THREAD

**Issue by kikiacc** [xanderfrangos/twinkle-tray#713]
hope support for the Apple Studio Display

**Comment by alex2430lol** [comment]
Same!

**Comment by xanderfrangos** [comment]
From what I can see online, the Apple Studio Display doesn't use DDC/CI. So Twinkle Tray is unable to control that monitor. If someone were to contribute code (a C++ Node module) specifically for this display, I'd be happy to include it.
