### ISSUE TITLE
ROG PG27UQR display does not support DDC/CI

### ISSUE THREAD

**Issue by Altria17388** [xanderfrangos/twinkle-tray#715]
After updating to v1.16.0-beta5.1, my ROG PG27UQR display does not support DDC/CI. But when I rolled back to v1.16.0-beta4, The Twinkle Tray can be used normally

**Comment by xanderfrangos** [comment]
Hi @Altria17388, thanks for the bug report! Please post any beta-related bugs in the [this stickied "v1.16.0 beta" issue](https://github.com/xanderfrangos/twinkle-tray/issues/626) only, so I can more easily keep track of what is a bug for the beta or stable versions.

Take a look at [this comment](https://github.com/xanderfrangos/twinkle-tray/issues/626#issuecomment-1880202123) I just made regarding a similar issue another user is having.

I'm going to close this in favor of the main stickied issue.
