### ISSUE TITLE
100 in twinkle-tray is only about 20% of the maximum brightness of display

### ISSUE THREAD

**Issue by Zixssia** [xanderfrangos/twinkle-tray#72]
The monitor is ASUS PG27UQ. The peak brightness in SDR is 600nit, but 100 in twinkle-tray is only about 120nit.（approximately, compared with LG UK850)
LG UK850 has no problem.

![image](https://user-images.githubusercontent.com/69361562/89673438-4f8cd800-d921-11ea-888a-5dc0ea38c64b.png)
![image](https://user-images.githubusercontent.com/69361562/89673173-de4d2500-d920-11ea-82ce-0c75a6b41e2a.png)
![image](https://user-images.githubusercontent.com/69361562/89673183-e3aa6f80-d920-11ea-8f39-5c2a77ad7337.png)

**Comment by xanderfrangos** [comment]
@Zixssia Odd. There may be an alternative VCP code that needs to be modified, or maybe the max brightness value goes above 100. It's tough to tell without the VCP info. Could you run ControlMyMonitor ([website](https://www.nirsoft.net/utils/control_my_monitor.html), [download](https://www.nirsoft.net/utils/controlmymonitor.zip)) and take a screenshot of the list of VCP codes for that monitor? Try to include the "Maximum Value" and "Possible Values" columns.

It should look like this:

![Annotation 2020-08-07 140612](https://user-images.githubusercontent.com/33106561/89675189-84644500-d8b7-11ea-9636-788fbfc9c471.png)

**Comment by Zixssia** [comment]
The list of PG27UQ looks quite different from uk850. Weird.
![image](https://user-images.githubusercontent.com/69361562/89704367-2c4c4200-d98e-11ea-8cc4-319e2797306b.png)
![image](https://user-images.githubusercontent.com/69361562/89704370-30785f80-d98e-11ea-817f-3b1c05362ca4.png)

**Comment by xanderfrangos** [comment]
Thanks for the screenshots! That answers it. The "brightness" goes up to 500. Twinkle Tray currently assumes the max value is 100. I'll make it use the actual max value in the next update.

**Comment by xanderfrangos** [comment]
@Zixssia Could you test out this version and let me know if it fixes the issue?

https://1drv.ms/u/s!AiWKFpjcSKRQhdMpr8qVfzHMvmU6KA?e=SaBFDQ

**Comment by Zixssia** [comment]
https://1drv.ms/u/s!AiWKFpjcSKRQhdMpr8qVfzHMvmU6KA?e=SaBFDQ 
It worked! 
But every time when click the icon or use the hotkey, both of the display goes up to max brightness at once. 
![image](https://user-images.githubusercontent.com/69361562/89725377-e9e83b00-da49-11ea-959c-caf332500b35.png)

I'll use 1.11.4 for the moment and wait for the next update. Thanks a lot!

**Comment by xanderfrangos** [comment]
@Zixssia It took a bit longer than expected to get the update out, but everything should be working now. Give v1.12.0 a try and let me know if it fixes your issue. Thanks!

**Comment by Zixssia** [comment]
Now it works perfectly in v1.12.0 .

**Comment by xanderfrangos** [comment]
Great! Thanks for letting me know. Closing the issue.
