### ISSUE TITLE
Change brightness according to sunrise/sunset information of local area

### ISSUE THREAD

**Issue by udobehm** [xanderfrangos/twinkle-tray#73]
Good day,

I would like to configure Twinkle Tray to change the display brightness not to a specific time but according to sunrise and sunset information in the area where I currently am. Could you implement this function in the UWP app version?? It was very handy if Twinkle tray would look automatically in what area I am and if it could update the sunset/sunrise time information on a maybe daily basis and then changes the brightness according to when the sun rises or goes down.

Hope you may implement this! Thanks!

**Comment by thomasthebear** [comment]
**I second this request.** Currently, I know of a few specific services that offer what would be needed to accomplish this. [**Sunrise-Sunset.org**](https://www.sunrise-sunset.org/api) offers the needed APIs for determining if its` Day or Night` Time at a specific Geo-Location. Obtaining the Geo-Location through converting a `Address, City or ZIP Code` could be done through several services such as [**Google's** Map Places API](https://developers.google.com/maps/documentation/), [**OpenCage's** Geocoding API](https://opencagedata.com/api), [**PositionStack's** API](https://positionstack.com/documentation), [**ipapi's** API](https://ipapi.com/documentation). I'm sure that **OpenStreetMap** even has a few options scattered around similar to **Overpass API**. Even the **United States Census Bureau** has a [Geocoding API](https://geocoding.geo.census.gov/), as do many Weather Services _(Weather Services could also give Sunrise/Sunset data most likely)_ . Also, though I've not looked it up, I'm sure that **Adsense** can most likely give a generalized location based off of `IP address` & obtaining location based off of `IP` shouldn't be very hard either. All the services I've mentioned have relatively generous _"Free"_ Plans available, or are outright Free period.

**Comment by carbonox-infernox** [comment]
Searched issues just for this. I third the request.

**Comment by DEdeVilliers** [comment]
I fourth this request.

**Comment by mkroiss** [comment]
Yes please (5th)

**Comment by gthrow** [comment]
There's a page on Wikipedia for an [equation to calculate the sunrise and sunset](https://en.wikipedia.org/wiki/Sunrise_equation), though I can't speak for its accuracy. I also found many mentions of the book "Astronomical Algorithms" by Jean Meeus when looking at how other programs (such as popular red tint apps) implement this, at a glance the wiki page seems derived from it and presented in a more digestible format. Though it feels likely an npm library for this should already exist?

Anyway this feature should not require hitting an API.

**Comment by TheSlicingSword** [comment]
Hey, would you have any idea on how I could implement this into my current version of Twinkle Tray? (v1.14.0-beta1)

**Comment by aqt** [comment]
The npm package suncalc works well, I'd suggest using that. Just provide time and geo coordinates, it does the calculations offline and you get an object with sun position and times back.

I'm unable to build Twinkle Tray because of node-gyp issues I've now given up on solving... And just uprooting all dependencies on it for the sake of getting development started didn't seem to be the way to go.

Since I wanted this feature I wrote a program that interfaces with Twinkle Tray's CLI instead. Has been working well for me the past few days. It's not user friendly as it requires some technical knowhow, but maybe it can still be of use to someone else in the wait for an official feature: https://github.com/aqt/twinkle-tray-sunscreen

**Comment by xanderfrangos** [comment]
Closing this, as the feature has been implemented. 👍
