### ISSUE TITLE
Won´t change the brightness of 1 of 3 monitors

### ISSUE THREAD

**Issue by hochi93** [xanderfrangos/twinkle-tray#745]
I have three times the same monitor (ASUS VG32VQ1B) and 1 of them won´t change its brightness. All 3 of them have the same monitor settings and get recognized by the app
![grafik](https://github.com/xanderfrangos/twinkle-tray/assets/48092507/599906b7-9dca-4d9c-adff-a853579f5626)
It worked well for a few months, but since 3 weeks Nr 3 doesn´t work anymore

**Comment by hochi93** [comment]
I guess i figured it out now. Most of the time I only use 1 or 2 of them. But if i turn on the 3rd one, my pc is already running, and so i can't set the brightness. Only after closing TwinkleTray with Taskmanager an reopen it, I can set the brightness.
But yes, all 3 have the same firmware version as it was delivered to me. 
To be fair i never installed any driver cause i didn't know, that monitor need drivers, but i will do this now.

**Comment by rzfzr** [comment]
The manufacturer may provide the drivers, tbh I don't if it really makes a difference, it would just be something to investigate the potential issue.
Downloading the color grading profile (.icm file) might be worth your time though, either provided by the manufacturer or community.

**Comment by xanderfrangos** [comment]
When this happens, have you tried manually refreshing the displays in Twinkle Tray? You can quickly do that by right-clicking on the Twinkle Tray system tray icon and selecting "Refresh displays".

**Comment by hochi93** [comment]
With refreshing the displays, it works for me, so i am happy with this solution, thanks a lot.
Also thanks for the tip with the .icm file
