### ISSUE TITLE
Detect monitor specific brightness range automatically

### ISSUE THREAD

**Issue by Swonkie** [xanderfrangos/twinkle-tray#75]
Not all monitors can be set from 0-100. Mine goes from 0-20 for example. You added a user setting for this, which is ok if you know your monitor's range, but it would be better if the app would read this automatically (this information is available when reading the monitor properties via DDC/CI).

By the way, I like the interface of this app a lot. I just replaced ClickMonitorDDC, which I was using for a long time.

**Comment by xanderfrangos** [comment]
Hi @Swonkie an update should be coming soon with a fix. I've had other users report the opposite problem (range goes beyond 100), and the fix for that should work for you as well. I'll post here again when the update is out.

**Comment by xanderfrangos** [comment]
@Swonkie It took a bit longer than expected, but v1.12.0 is out now. Let me know if it fixes your issue. Thanks!

**Comment by xanderfrangos** [comment]
This issue appears to be fixed, as reported in https://github.com/xanderfrangos/twinkle-tray/issues/72. If this isn't the case, please let me know by opening a new issue.

**Comment by Swonkie** [comment]
@xanderfrangos well I guess it's sort of fixed. I'm a bit confused why you did it this way, to be honest.

As mentioned, I previously had to set my monitor's max value to 20, now with the update it's the wrong setting and I needed to set it back to 100 manually.

I suppose for new users, it now works "out of the box" without making any adjustments, but I don't see the point of even having the manual sliders now and I don't understand why you didn't remove them. Isn't it the case that everybody has to set the range to 0 - 100 now, and the sliders should never be touched?
