### ISSUE TITLE
Lithuanian translation completed!

### ISSUE THREAD

**Issue by dziugas1959** [xanderfrangos/twinkle-tray#756]
Hello,

I have completed the Lithuanian translation („Weblate“) for this amazing program, hopefully in the coming days, a small patch will be made to include support for it, thanks!

**Comment by dziugas1959** [comment]
Has been done.

**Comment by xanderfrangos** [comment]
@dziugas1959 Thank you! I believe your translations have been included in v1.15.5 and v1.16.0-beta7. 👍
