### ISSUE TITLE
Separate monitor display not being detected on laptop

### ISSUE THREAD

**Issue by chessboards** [xanderfrangos/twinkle-tray#76]
When using a Windows 10 Home laptop along-side of an Acer monitor connected using an HDMI cable, twinkle tray fails to detect the second monitor.

**Comment by xanderfrangos** [comment]
Hi, sorry for taking so long to reply.

I've put together a page outlining why you may be having monitor detection issues with Twinkle Tray: https://github.com/xanderfrangos/twinkle-tray/wiki/Display-Detection-&-Support-Issues

I'll be closing this issue in favor of the centralized, pinned issue here: #81
