### ISSUE TITLE
[Bug] Laptop display not showing up under shortcuts to set custom controls [Beta Version]

### ISSUE THREAD

**Issue by madgoatz** [xanderfrangos/twinkle-tray#768]
This is currently the latest beta version. It was also an issues in the previous beta version as well.
![image](https://github.com/xanderfrangos/twinkle-tray/assets/88365986/d292d1dc-1270-45a0-bbb3-1c2766cf9fbd)

Both the laptop display and the external monitor are detected.
However, there isn't an option to **select/set** a dedicated **hotkey/shortcut** for the laptop display.  _(See images below)_

![image](https://github.com/xanderfrangos/twinkle-tray/assets/88365986/debe616b-50b3-4bbd-b147-87247c8b9b2c)

![image](https://github.com/xanderfrangos/twinkle-tray/assets/88365986/e8948cdd-c08f-40b9-80c4-59914a4aa159)

**Comment by xanderfrangos** [comment]
Thanks for the bug report. 👍 I've fixed it in this build: https://github.com/xanderfrangos/twinkle-tray/actions/runs/9375679058/artifacts/1568948859
