### ISSUE TITLE
help, npm ci failure

### ISSUE THREAD

**Issue by 284324096** [xanderfrangos/twinkle-tray#78]
8649 verbose lifecycle twinkle-tray@1.11.4~postinstall: CWD: E:\download\iedeown\twinkle-tray-1.11.4
8650 silly lifecycle twinkle-tray@1.11.4~postinstall: Args: [ '/d /s /c', 'electron-builder install-app-deps' ]
8651 silly lifecycle twinkle-tray@1.11.4~postinstall: Returned: code: 1  signal: null
8652 info lifecycle twinkle-tray@1.11.4~postinstall: Failed to exec postinstall script
8653 verbose teardown shutting down workers.
8654 info teardown Done in 0s
8655 verbose stack Error: twinkle-tray@1.11.4 postinstall: `electron-builder install-app-deps`
8655 verbose stack Exit status 1
8655 verbose stack     at EventEmitter.<anonymous> (C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
8655 verbose stack     at EventEmitter.emit (events.js:315:20)
8655 verbose stack     at ChildProcess.<anonymous> (C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
8655 verbose stack     at ChildProcess.emit (events.js:315:20)
8655 verbose stack     at maybeClose (internal/child_process.js:1021:16)
8655 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
8656 verbose pkgid twinkle-tray@1.11.4
8657 verbose cwd E:\download\iedeown\twinkle-tray-1.11.4
8658 verbose Windows_NT 10.0.18362
8659 verbose argv "E:\\p_x86\\nodejs\\node.exe" "C:\\Users\\zimu2\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "ci"
8660 verbose node v12.17.0
8661 verbose npm  v6.14.8
8662 error code ELIFECYCLE
8663 error errno 1
8664 error twinkle-tray@1.11.4 postinstall: `electron-builder install-app-deps`
8664 error Exit status 1
8665 error Failed at the twinkle-tray@1.11.4 postinstall script.
8665 error This is probably not a problem with npm. There is likely additional logging output above.
8666 verbose exit [ 1, true ]

**Comment by xanderfrangos** [comment]
Have you installed `node-gyp`? That might be where it's failing. If you haven't, the instructions are here:
https://github.com/nodejs/node-gyp#installation

**Comment by 284324096** [comment]
> gyp



E:\download\iedeown\twinkle-tray-1.11.4>npm -g list|findstr gyp
  +-- node-gyp@5.1.0
  | +-- node-gyp@5.1.0 deduped

E:\download\iedeown\twinkle-tray-1.11.4>npm list|findstr gyp
| `-- node-gyp@5.0.2
|   | `-- node-pre-gyp@0.14.0

E:\download\iedeown\twinkle-tray-1.11.4>dir /s node-gyp
 驱动器 E 中的卷是 LENOVO
 卷的序列号是 98DD-4A88

 E:\download\iedeown\twinkle-tray-1.11.4\node_modules 的目录

2020/09/14  16:33    <DIR>          node-gyp
               0 个文件              0 字节

 E:\download\iedeown\twinkle-tray-1.11.4\node_modules\.bin 的目录

2020/09/14  16:35               334 node-gyp
               1 个文件            334 字节

     所列文件总数:
               1 个文件            334 字节
               1 个目录 84,393,136,128 可用字节

E:\download\iedeown\twinkle-tray-1.11.4>dir node_modules\node-gyp\
 驱动器 E 中的卷是 LENOVO
 卷的序列号是 98DD-4A88

 E:\download\iedeown\twinkle-tray-1.11.4\node_modules\node-gyp 的目录

2020/09/14  16:33    <DIR>          .
2020/09/14  16:33    <DIR>          ..
1985/10/26  16:15                75 .eslintrc.yaml
2020/09/14  16:33    <DIR>          .github
1985/10/26  16:15                91 .jshintrc
1985/10/26  16:15             1,343 .travis.yml
1985/10/26  16:15             4,728 addon.gypi
2020/09/14  16:33    <DIR>          bin
1985/10/26  16:15            34,481 CHANGELOG.md
1985/10/26  16:15             1,381 CONTRIBUTING.md
2020/09/14  16:33    <DIR>          gyp
2020/09/14  16:33    <DIR>          lib
1985/10/26  16:15             1,102 LICENSE
1985/10/26  16:15             1,397 package.json
1985/10/26  16:15             8,894 README.md
2020/09/14  16:33    <DIR>          src
2020/09/14  16:33    <DIR>          test
               9 个文件         53,492 字节
               8 个目录 84,393,136,128 可用字节

E:\download\iedeown\twinkle-tray-1.11.4>

**Comment by xanderfrangos** [comment]
I've made some changes that should make building easier. Try deleting your `node_modules` and `npm i` again.

**Comment by 284324096** [comment]
already failure as following


E:\download\iedeown\twinkle-tray-master>npm ci

> wmi-client@0.5.0 install E:\download\iedeown\twinkle-tray-master\node_modules\wmi-client
> node scripts/install.js


> win32-displayconfig@0.1.0 install E:\download\iedeown\twinkle-tray-master\node_modules\win32-displayconfig
> npm run rebuild


> win32-displayconfig@0.1.0 rebuild E:\download\iedeown\twinkle-tray-master\node_modules\win32-displayconfig
> node-gyp rebuild


E:\download\iedeown\twinkle-tray-master\node_modules\win32-displayconfig>if not defined npm_config_node_gyp (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  win32-displayconfig.cc
  win_delay_load_hook.cc
    正在创建库 E:\download\iedeown\twinkle-tray-master\node_modules\win32-displayconfig\build\Release\win32_displayconfig.li
  b 和对象 E:\download\iedeown\twinkle-tray-master\node_modules\win32-displayconfig\build\Release\win32_displayconfig.exp
  win32_displayconfig.vcxproj -> E:\download\iedeown\twinkle-tray-master\node_modules\win32-displayconfig\build\Release
  \\win32_displayconfig.node

> global-mouse-events@1.0.3 install E:\download\iedeown\twinkle-tray-master\node_modules\global-mouse-events
> npm run rebuild


> global-mouse-events@1.0.3 rebuild E:\download\iedeown\twinkle-tray-master\node_modules\global-mouse-events
> node-gyp rebuild


E:\download\iedeown\twinkle-tray-master\node_modules\global-mouse-events>if not defined npm_config_node_gyp (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  global-mouse-events.cc
  win_delay_load_hook.cc
    正在创建库 E:\download\iedeown\twinkle-tray-master\node_modules\global-mouse-events\build\Release\global_mouse_events.li
  b 和对象 E:\download\iedeown\twinkle-tray-master\node_modules\global-mouse-events\build\Release\global_mouse_events.exp
  global_mouse_events.vcxproj -> E:\download\iedeown\twinkle-tray-master\node_modules\global-mouse-events\build\Release
  \\global_mouse_events.node

> @nodert-win10-au/windows.applicationmodel@0.4.4 install E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel
> node-gyp rebuild


E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel>if not defined npm_config_node_gyp (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel\_nodert_generated.cpp :
fatal error C1107: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tray-maste
r\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel\NodeRtUtils.cpp : fatal
error C1107: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tray-master\node
_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel\OpaqueWrapper.cpp : fata
l error C1107: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tray-master\no
de_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
  win_delay_load_hook.cc
E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel\CollectionsConverterUtil
s.cpp : fatal error C1107: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tr
ay-master\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C110
7: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tray-master\node_modules\@
nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `e:\p_x86\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "E:\\p_x86\\nodejs\\node.exe" "C:\\Users\\zimu2\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> setwindowpos-binding@1.0.0 install E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding
> npm run rebuild


> setwindowpos-binding@1.0.0 rebuild E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding
> node-gyp rebuild


E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding>if not defined npm_config_node_gyp (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  setwindowpos.cc
  win_delay_load_hook.cc
E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding\setwindowpos.cc(13,59): warning C4312: “类型 强制转
换”: 从“int32_t”转换到更大的“HWND” [E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding\build\setwindowpo
s.vcxproj]
E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding\setwindowpos.cc(13,90): warning C4312: “类型 强制转
换”: 从“int32_t”转换到更大的“HWND” [E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding\build\setwindowpo
s.vcxproj]
    正在创建库 E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding\build\Release\setwindowpos.lib 和对象
  E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding\build\Release\setwindowpos.exp
  setwindowpos.vcxproj -> E:\download\iedeown\twinkle-tray-master\node_modules\setwindowpos-binding\build\Release\\setw
  indowpos.node

> electron-acrylic-window@0.4.3 install E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window
> node-gyp rebuild


E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window>if not defined npm_config_node_gyp (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  main.cc
  win_delay_load_hook.cc
E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\src\main.cc(37,9): warning C4530: 使用了 C++
异常处理程序，但未启用展开语义。请指定 /EHsc [E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\build\vibrancy-
wrapper.vcxproj]
E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\src\main.cc(76,26): warning C4101: “ex”: 未
引用的局部变量 [E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\build\vibrancy-wrapper.vcxproj]
E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\src\main.cc(109,26): warning C4101: “ex”:
未引用的局部变量 [E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\build\vibrancy-wrapper.vcxproj]
    正在创建库 E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\build\Release\vibrancy-wrapper.l
  ib 和对象 E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\build\Release\vibrancy-wrapper.ex
  p
  vibrancy-wrapper.vcxproj -> E:\download\iedeown\twinkle-tray-master\node_modules\electron-acrylic-window\build\Releas
  e\\vibrancy-wrapper.node

> @hensm/ddcci@0.0.4 install E:\download\iedeown\twinkle-tray-master\node_modules\@hensm\ddcci
> node-gyp rebuild


E:\download\iedeown\twinkle-tray-master\node_modules\@hensm\ddcci>if not defined npm_config_node_gyp (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> E:\download\iedeown\twinkle-tray-master\node_modules\@hensm\ddcci\build\Release\\nothing.lib
  ddcci.cc
  win_delay_load_hook.cc
    正在创建库 E:\download\iedeown\twinkle-tray-master\node_modules\@hensm\ddcci\build\Release\ddcci.lib 和对象 E:\download\ied
  eown\twinkle-tray-master\node_modules\@hensm\ddcci\build\Release\ddcci.exp
  ddcci.vcxproj -> E:\download\iedeown\twinkle-tray-master\node_modules\@hensm\ddcci\build\Release\\ddcci.node

> fsevents@1.2.13 install E:\download\iedeown\twinkle-tray-master\node_modules\fsevents
> node install.js


Skipping 'fsevents' build as platform win32 is not supported

> deasync@0.1.20 install E:\download\iedeown\twinkle-tray-master\node_modules\deasync
> node ./build.js

`win32-x64-node-12` exists; testing
Binary is fine; exiting

> core-js@2.6.11 postinstall E:\download\iedeown\twinkle-tray-master\node_modules\parcel-bundler\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall E:\download\iedeown\twinkle-tray-master\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> parcel-bundler@1.12.4 postinstall E:\download\iedeown\twinkle-tray-master\node_modules\parcel-bundler
> node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"

Love Parcel? You can now donate to our open collective:
 > https://opencollective.com/parcel/donate

> core-js@3.6.5 postinstall E:\download\iedeown\twinkle-tray-master\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> electron@10.1.2 postinstall E:\download\iedeown\twinkle-tray-master\node_modules\electron
> node install.js


> twinkle-tray@1.12.1 postinstall E:\download\iedeown\twinkle-tray-master
> electron-builder install-app-deps

  • electron-builder  version=22.8.1
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=@hensm/ddcci@0.0.4, @nodert-win10-au/windows.applicationmodel@0.4.4, electron-acrylic-window@0.4.3, global-mouse-events@1.0.3, setwindowpos-binding@1.0.0, win32-displayconfig@0.1.0
                                    platform=win32
                                    arch=x64
  ⨯ cannot execute  cause=exit status 1
                    out=
    > @hensm/ddcci@0.0.4 install E:\download\iedeown\twinkle-tray-master\node_modules\@hensm\ddcci
    > node-gyp rebuild


    E:\download\iedeown\twinkle-tray-master\node_modules\@hensm\ddcci>if not defined npm_config_node_gyp (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

                    errorOut=gyp WARN install got an error, rolling back install
    gyp ERR! configure error
    gyp ERR! stack Error: read ECONNRESET
    gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
    gyp ERR! System Windows_NT 10.0.18362
    gyp ERR! command "E:\\p_x86\\nodejs\\node.exe" "C:\\Users\\zimu2\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd E:\download\iedeown\twinkle-tray-master\node_modules\@hensm\ddcci
    gyp ERR! node -v v12.17.0
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! @hensm/ddcci@0.0.4 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the @hensm/ddcci@0.0.4 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\zimu2\AppData\Roaming\npm-cache\_cacache\_logs\2020-09-28T07_54_10_536Z-debug.log

                    command='E:\p_x86\nodejs\node.exe' 'C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js' rebuild @hensm/ddcci@0.0.4 @nodert-win10-au/windows.applicationmodel@0.4.4 electron-acrylic-window@0.4.3 global-mouse-events@1.0.3 setwindowpos-binding@1.0.0 win32-displayconfig@0.1.0
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twinkle-tray@1.12.1 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twinkle-tray@1.12.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zimu2\AppData\Roaming\npm-cache\_logs\2020-09-28T07_54_10_710Z-debug.log

E:\download\iedeown\twinkle-tray-master>

**Comment by xanderfrangos** [comment]
It looks like it's failing on `@hensm/ddcci`, which only requires `node-gyp` be properly installed. There may be something wrong with your global install of `node-gyp`. Make sure you have Python and the correct C++ stuff installed for it. Also, I don't think `npm ci` plays nice with Twinkle Tray. It seems to get caught on optional dependencies. You may have to use `npm install` instead to get it to skip over the optional dependencies.

**Comment by 284324096** [comment]
npm install --global --production windows-build-tools
npm config set python python2.7
npm config set msvs_version 2019
`
E:\download\iedeown\twinkle-tray-master>npm install

> deasync@0.1.20 install E:\download\iedeown\twinkle-tray-master\node_modules\deasync
> node ./build.js

`win32-x64-node-10` exists; testing
Binary is fine; exiting

> @nodert-win10-au/windows.applicationmodel@0.4.4 install E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel
> node-gyp rebuild


E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel>if not defined npm_config_node_gyp (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel\_nodert_generated.cpp :
fatal error C1107: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tray-maste
r\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel\NodeRtUtils.cpp : fatal
error C1107: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tray-master\node
_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel\OpaqueWrapper.cpp : fata
l error C1107: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tray-master\no
de_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel\CollectionsConverterUtil
s.cpp : fatal error C1107: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tr
ay-master\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
  win_delay_load_hook.cc
C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C110
7: 未能找到程序集“platform.winmd”: 请使用 /AI 或通过设置 LIBPATH 环境变量指定程序集搜索路径 [E:\download\iedeown\twinkle-tray-master\node_modules\@
nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `e:\p_x86\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zimu2\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "E:\\p_x86\\nodejs\\node.exe" "C:\\Users\\zimu2\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\download\iedeown\twinkle-tray-master\node_modules\@nodert-win10-au\windows.applicationmodel
gyp ERR! node -v v10.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
`


maybe msvs-tool has wrong?
win10 too too be wrong, jump to linux as following 
`
root@/mnt/e/download/iedeown/twinkle-tray-master# npm install

> @nodert-win10-au/windows.applicationmodel@0.4.4 install /mnt/e/download/iedeown/twinkle-tray-master/node_modules/@nodert-win10-au/windows.applicationmodel
> node-gyp rebuild

make: Entering directory '/mnt/e/download/iedeown/twinkle-tray-master/node_modules/@nodert-win10-au/windows.applicationmodel/build'
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/mnt/e/download/iedeown/twinkle-tray-master/node_modules/@nodert-win10-au/windows.applicationmodel/build'

> win32-displayconfig@0.1.0 install /mnt/e/download/iedeown/twinkle-tray-master/node_modules/win32-displayconfig
> npm run rebuild


> win32-displayconfig@0.1.0 rebuild /mnt/e/download/iedeown/twinkle-tray-master/node_modules/win32-displayconfig
> node-gyp rebuild

make: Entering directory '/mnt/e/download/iedeown/twinkle-tray-master/node_modules/win32-displayconfig/build'
  SOLINK_MODULE(target) Release/obj.target/win32_displayconfig.node
  COPY Release/win32_displayconfig.node
make: Leaving directory '/mnt/e/download/iedeown/twinkle-tray-master/node_modules/win32-displayconfig/build'
npm WARN lifecycle twinkle-tray@1.12.1~postinstall: cannot run in wd twinkle-tray@1.12.1 electron-builder install-app-deps (wd=/mnt/e/download/iedeown/twinkle-tray-master)
npm WARN twinkle-tray@1.12.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 14 packages from 78 contributors in 17.197s

45 packages are looking for funding
  run `npm fund` for details

root@/mnt/e/download/iedeown/twinkle-tray-master# npm start

> twinkle-tray@1.12.1 start /mnt/e/download/iedeown/twinkle-tray-master
> wait-on http://localhost:3000/index.html && electron .`


what question is on linux ?

**Comment by xanderfrangos** [comment]
@284324096 I tested the build process on a clean installation of Windows 10. With just Node 12 and the included build tools, I was able to install and build Twinkle Tray without issue. There seems to be something wrong with your environment that I can't help you with. FYI, this app doesn't work and cannot be built with Linux. It's Windows only.

**Comment by 284324096** [comment]
thank you very much! i known , my environment is very complex. exist vs2019  and vs2017, maybe vstool can not do.
