### ISSUE TITLE
Improve flyout closing

### ISSUE THREAD

**Issue by Armin2208** [xanderfrangos/twinkle-tray#80]
Thanks for the App, Twinkle Tray looks great, works great and the additional settings are really useful! Great to see well mantained software.

I only have one problem with Twinkle Tray: the flyout doesn't close reliable in some situations. Especially when playing a video game and trying to quickly switch the brightness. Going back into the game Twinkle Tray stays open. 

Maybe you could improve the behaviour, how Twinkle Tray recognizes being out of focus or closing Twinkle Tray if the user clicks again on the Icon on the taskbar.

**The easiest fix**: implement a keyboard listener which closese the flyout when pressing the "esc" key. Every Windows Flyout supports this.

Thanks!

**Comment by xanderfrangos** [comment]
Thanks for the feedback! I have some ideas on how I can make that more reliable, but I'll toss in the escape key idea as well.

**Comment by xanderfrangos** [comment]
v1.12.1 is out and should improve the reliability of the brightness panel closing. Clicking anywhere but the panel itself (or the icon) should always close it. I've also added your suggestion of the Escape key. Let me know if you continue to see the panel not closing properly.

**Comment by Armin2208** [comment]
working very well now and esc is always a good solution. Thanks!

**Comment by Seo-Rii** [comment]
As you said, this error was completely corrected in 1.12.1, but the update to 1.12.2 caused the problem to recur.

**Comment by xanderfrangos** [comment]
@Seo-Rii Do you have steps that I can use to recreate it? I'm having trouble getting it stuck open.

**Comment by Seo-Rii** [comment]
@xanderfrangos  Tap the icon again after the animation that opens the screen is complete. If you click the icon while the screen is open, it closes well, but after the animation ends (after the screen is fully open), tap the icon to reopen it without closing.

**Comment by xanderfrangos** [comment]
@Seo-Rii Oh I see. That wasn't something that I specifically fixed. It had more to do with the panel not closing when clicking away. There are a lot of events firing when clicking that icon that cause it to unintentionally re-open, but I'll see what I can do.

**Comment by Seo-Rii** [comment]
@xanderfrangos  Oh, sorry. I misunderstood the subject of this issue. Thank you for correcting the error anyway. BTW, after the recent upgrade to the latest version (probably 1.12.1), the animation with the panel closed seems to be missing, is it intended?

**Comment by xanderfrangos** [comment]
@Seo-Rii That's as of v1.12.0. It was intentional but not really what I wanted. I got fed up with trying to get the Acrylic version to animate well, so I mostly restored the old animation and shipped it. The missing "closed" animation is a side-effect of that. The other panels (volume, network, etc) animate out so quickly that I can hardly see them at 144Hz, so I don't consider it a huge loss.

**Comment by Seo-Rii** [comment]
@xanderfrangos I see.
