### ISSUE TITLE
Winget: No package found

### ISSUE THREAD

**Issue by nikolai-in** [xanderfrangos/twinkle-tray#800]
I was trying to install this app as documented in README, but Winget threw `No package found matching input criteria`
Using *id* instead of a name resolved this issue
https://github.com/xanderfrangos/twinkle-tray/blob/a9a72edfe3d1123b15a03d8b7245e11e12264bfe/README.md?plain=1#L38
```powershell
winget install xanderfrangos.twinkletray
```

![image](https://github.com/user-attachments/assets/daa0c70f-dd29-42b0-9bb8-9c85425892df)

Winget v1.8.1911 Windows 11 21H2

PS thanks for this great software

**Comment by xanderfrangos** [comment]
PR merged. Much appreciated!
