### ISSUE TITLE
Microsoft store version isn't up to date

### ISSUE THREAD

**Issue by cpo-ux** [xanderfrangos/twinkle-tray#803]
I did a fresh install on Windows 11 system and it works however I noticed that Microsoft Store installed 1.15.4 and MS Store doesn't update.  I look at the MS Store description and it says "New in v1.15.5..." so that's strange.  Easy to fix since I'll just install manually from github website however I wanted to let you know about this issue.  Cheers.

**Comment by xanderfrangos** [comment]
It's been rolling out to the MS store very slowly. I wanted to be sure there weren't any new issues before rolling it out to everyone. It's been several weeks now, so it's about time it for everyone to get it. I'll flip the switch today. Thanks for the reminder. 👍
