### ISSUE TITLE
[Bug] JavaScript error when clicking "Power off" for monitor button [Beta Version]

### ISSUE THREAD

**Issue by madgoatz** [xanderfrangos/twinkle-tray#807]
This is current the latest beta version.
![image](https://github.com/user-attachments/assets/2ae54aed-4542-4a11-b3ea-7ed63e8dd81f)

I get this error when clicking the **"Power off"** button. It doesn't matter which option I have selected for the **"Power State Signal"** setting.
If I remember correctly, this was also an issue in the previous beta version as well.
![image](https://github.com/user-attachments/assets/3c3d9f90-381a-4528-8cd8-9d4eef21c9b8)

**Comment by xanderfrangos** [comment]
Thanks for the bug report! I've fixed it in this build: https://github.com/xanderfrangos/twinkle-tray/actions/runs/10548040173/artifacts/1851917749
