### ISSUE TITLE
[BUG!] If the display auto turns off then the set brightness does not persist.

### ISSUE THREAD

**Issue by shafayetejaman** [xanderfrangos/twinkle-tray#825]
After the display is inactive for a certain period of time the os shuts the monitor down. but when this happens the the display changes the brightness to the monitor set brightness, not the brightness set in the Ttwinkle tray software.

**Comment by xanderfrangos** [comment]
This isn't a Twinkle Tray bug, but the intended behavior of some monitors. If you use the "Idle Detection" feature, it can help restore the previous brightness. Just be sure to set it so the Twinkle Tray idle detection kicks in _before_ Windows turns off the displays.

**Comment by shafayetejaman** [comment]
Thanks for the response.
