### ISSUE TITLE
Using brightness hotkeys minimizes some exclusive fullscreen games

### ISSUE THREAD

**Issue by kylejohnsonkj** [xanderfrangos/twinkle-tray#83]
As of the 1.12.0 update, I'm having an issue where using the brightness hotkeys in Rocket League (running in exclusive fullscreen mode), causes the game to minimize each time a brightness hotkey is pressed. I went back to 1.11.4 and confirmed this doesn't happen. Unfortunately I couldn't recreate in other games, but RL is free on Epic Games if you need it for testing.

**Comment by xanderfrangos** [comment]
Thanks for letting me know. I think I know why it's happening. I'll check it out. 👍

**Comment by kylejohnsonkj** [comment]
Looks like you fixed it!
