### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by PowerPCFan** [xanderfrangos/twinkle-tray#834]
So I'm still using v1.15.4 because I don't like the new scrolling thing introduced in v1.15.5, any way I can update to 1.15.5 or 1.16.0 without changing the scrolling behavior?

Looks like you can download the source code, not sure how to do this but would I be able to modify the source code of v1.16 with 1.15.4 as a reference to add the old scrolling to the new version? Or is there a simpler method?

**Comment by xanderfrangos** [comment]
Are you referring to the slightly increased increments when scrolling or the larger scroll area?

**Comment by PowerPCFan** [comment]
@xanderfrangos not really sure since when I tested 1.15.5 when it came out, i downgraded back to 1.15.4 about an hour later, but I'm pretty sure the increased/variable increments were messing me up

i like having 'static increments' so 5 scroll wheel clicks will move the slider down 5 'notches.' With the new scrolling I noticed that it was more loose and variable, and from what I remember the increments would change depending on how fast I scrolled, making it harder to do precise and fine adjustments with the scroll wheel. For example, if I scrolled up 5 clicks on my mouse wheel and down two clicks, I would end up on a different number than what I started on.

**Comment by xanderfrangos** [comment]
I've added in a (hidden) option to adjust the scroll amount. Grab this build: https://github.com/xanderfrangos/twinkle-tray/actions/runs/11043914054/artifacts/1979998240

And then in the "Debug" tab, set "Flyout scroll amount" to 1:
![image](https://github.com/user-attachments/assets/967c28ab-5458-4526-b5d5-6679e4f002ad)

That should make it scroll the same amount as in v1.15.4.

**Comment by PowerPCFan** [comment]
I can't open the zip without Windows Defender freaking out and deleting it, but I trust it so i'll just disable defender temporarily i guess

**Comment by PowerPCFan** [comment]
Thanks, that seemed to work! Once installed Defender isn't screaming at me anymore, and the brightness controls are exactly how I like them to be. I'll close this issue now.
