### ISSUE TITLE
Twinkle tray causing full screen apps to minimise

### ISSUE THREAD

**Issue by dreamerscot** [xanderfrangos/twinkle-tray#835]
After a recent update to v1.16.0, I've noticed that applications such as games launched in full screen (exclusive mode) often minimise, returning to desktop frequently.

Often when applications are minimised there are a number of instances of Twinkle tray that appear in the taskbar and sometimes the taskbar icon disappears and reappears like it's relaunching. I've noticed that it doesn't appear to have the minimising behaviour when the settings dialogue is open. The minimising issue also doesn't occur when Twinkle tray is exited, which seems to narrow the behaviour down to this application.

**Comment by xanderfrangos** [comment]
Is it happening randomly, or when you're using hotkeys? Also, could you generate and upload a debugging report (in the "Settings" window, at the end of the "General" page)?

**Comment by dreamerscot** [comment]
It seems to happen at random intervals when using the full screen application, there's no regular pattern to it and it doesn't depend on any input as it minimises when the application is left idle. I've generated a debugging report and added it here for you.

[tt-report-1727376101352.txt](https://github.com/user-attachments/files/17154287/tt-report-1727376101352.txt)

**Comment by dreamerscot** [comment]
It seems to be the Use Win32 hardware events option toggled on that's causing this issue.

The Use Electron hardware events toggled on itself doesn't seem to have this behaviour.

**Comment by sugoinaman** [comment]
Same here. All of my games keep alt tabbing out after exactly 5 seconds.

**Comment by adrianriyadi** [comment]
any update on this problem? Counter-Strike 2 game seems to be affected

**Comment by dreamerscot** [comment]
The Use Electron hardware events toggled on itself hasn't seemed to resolve it, it repeatedly did it with another game with just this option toggled on.

I also tried toggling on Use Win32 hardware events option on it's own and it still did it. Like sugoinaman mentioned above, it's like it's Alt-Tabbing out of the game repeatedly.

When I disable both Use Win32 hardware events and Use Electron hardware events options it doesn't happen.

**Comment by xanderfrangos** [comment]
To clarify, if you're encountering this issue you should try turning those settings off, not on. 

Twinkle Tray is receiving a message from Windows that your monitor configuration changed, and then does a few things:
1. Refreshes the detected displays
2. Reapplies brightness
3. Recreates the tray icon (not new, but more obvious as of v1.16.0)
4. Recreates the flyout/overlay (new as of v1.16.0)

Both the "Win32" and "Electron" events trigger these, just using different messages from Windows.

3 and 4 are to address visual bugs ([example](https://github.com/xanderfrangos/twinkle-tray/issues/828)) that can happen when displays are added/removed, or the resolution/DPI changes. 4 is what's causing full screen apps to minimize. I'm going to make this functionality optional and am looking into other options for detecting display changes. However, the fact that these messages are being sent to Twinkle Tray in the first place indicates that there's something weird going on with your PC. Windows shouldn't be sending these messages unless displays are changing. You may want to check other apps (and hardware) to see if they're triggering this. It's likely been happening for a while and you didn't notice, as it wasn't as visually obvious.

**Comment by adrianriyadi** [comment]
> To clarify, if you're encountering this issue you should try turning those settings off, not on.
> 
> Twinkle Tray is receiving a message from Windows that your monitor configuration changed, and then does a few things:
> 
>     1. Refreshes the detected displays
> 
>     2. Reapplies brightness
> 
>     3. Recreates the tray icon (not new, but more obvious as of v1.16.0)
> 
>     4. Recreates the flyout/overlay (new as of v1.16.0)
> 
> 
> Both the "Win32" and "Electron" events trigger these, just using different messages from Windows.
> 
> 3 and 4 are to address visual bugs ([example](https://github.com/xanderfrangos/twinkle-tray/issues/828)) that can happen when displays are added/removed, or the resolution/DPI changes. 4 is what's causing full screen apps to minimize. I'm going to make this functionality optional and am looking into other options for detecting display changes. However, the fact that these messages are being sent to Twinkle Tray in the first place indicates that there's something weird going on with your PC. Windows shouldn't be sending these messages unless displays are changing. You may want to check other apps (and hardware) to see if they're triggering this. It's likely been happening for a while and you didn't notice, as it wasn't as visually obvious.

this solution seems like a temporary fix for me

**Comment by dreamerscot** [comment]
> this solution seems like a temporary fix for me

Is it a double or triple monitor setup you have? I have a triple monitor setup which all use Displayport connections. I don't have a lot installed in this setup either as I primarily use it for gaming. I just have a minimal install of Steam, EA App, Steelseries GG, Spotify, Epic Games launcher installed. I exited all other applications so that only Steam and Twinkle Tray were showing in the tray icons. That had no effect, the minimising issue was still there. I also tried disabling G-SYNC which had no effect either.

However, I just had a thought and changed my desktop refresh rate from the previous 2560 x 1440, 120Hz to match the game refresh rate 2560 x 1440, 165Hz on the primary DELL G2724D monitor I have. I usually keep the desktop refresh rate lower as it seems unnecessary to have it so high when not playing games. With both Use Win32 hardware events and Use Electron hardware events toggled on with both resolution and refresh rate settings the same (2560 x 1440, 165Hz) between the desktop and full screen game, it didn't cause the minimisation issue at all.

I even changed the resolution to lower 1920 x 1080, 60Hz and refresh rate of the desktop different to the game settings (2560 x 1440, 165Hz) and the minimisation issue came back. I wonder if this could be a conflict between the refresh rates between desktop and full screen applications causing this?

**Comment by xanderfrangos** [comment]
I believe I've narrowed down the conditions for this happening. Give this build a try and let me know if it helps: https://github.com/xanderfrangos/twinkle-tray/actions/runs/11096476769/artifacts/1993070459

**Comment by dreamerscot** [comment]
On one device the new build installed fine but as a note, it seemed to trigger a false positive virus detection on my gaming device with:

![image](https://github.com/user-attachments/assets/3aea960b-2701-4ef7-87ce-c60ab16d0cdd)

It installed fine though so I'll put my desktop resolution and refresh rate back to 2560 x 1440, 120Hz which triggered the minimisation issue and see what it's like with a couple of games at 2560 x 1440, 165Hz for now. I'll leave all settings in Twinkle Tray at their default values and report the results afterwards.

**Comment by dreamerscot** [comment]
Looks good. I've tried the new build on a couple of games in full screen for roughly 10 minutes each and it looks like they don't have the minimisation issue anymore!

**Comment by xanderfrangos** [comment]
v1.16.1 is out with this fix. 👍

To follow up on some of my comments from earlier: there was a legitimate bug where Twinkle Tray would steal focus in "exclusive fullscreen" games 5 seconds after the game took focus, changed the resolution, or changed the refresh rate. However, if you were encountering this issue randomly, you may want to check for any other weirdness (outside of Twinkle Tray). A bad/loose cable or app that adjusts the resolution/refresh rate could be causing unnecessary hardware events to trigger in Windows. I don't think it's a huge issue, but it could cause random lag in games.
