### ISSUE TITLE
Visual bug: Display toggle button in hotkeys settings not showing correctly when display has too long a name

### ISSUE THREAD

**Issue by jeregon1** [xanderfrangos/twinkle-tray#837]
**Steps to reproduce:**
1. Name a monitor with a long enough name that in the hotkeys settings the name right to the toggle button occupies two lines.
2. Activate the toggle button.

![image](https://github.com/user-attachments/assets/2a0e14f2-9386-48fe-8768-68546e8dfb21)

Look at the active toggle button of the first hotkey, then at the active toggle button of the second hotkey, the one for Q27G2WG4.

I think that toggle button has a visual bug since the small black circle should be inside the blue area, or maybe it's the display's name which shouldn't be moving left, or the blue area which shouldn't be shrinking.

**Comment by xanderfrangos** [comment]
Should be fixed in the next update. Thanks for the bug report. 👍

**Comment by xanderfrangos** [comment]
Fixed in v1.16.1. Also fixed a similar visual bug with the "power off" option in the flyout getting squished.
