### ISSUE TITLE
Visual bug: Golden hour is disordered

### ISSUE THREAD

**Issue by jeregon1** [xanderfrangos/twinkle-tray#838]
**Steps to reproduce:**
1. Go to Time adjustments settings
2. Add a time and toggle sun position
3. Display all the times of the day

![image](https://github.com/user-attachments/assets/b56d2f7b-13af-443a-be10-3131982963d4)

Golden hour (7:15 PM) should be after solar noon based on the time, I guess.

Thank you for this amazing update :)

**Comment by xanderfrangos** [comment]
Just to confirm: it's only the order in the list, not the functionality that's incorrect?

**Comment by jeregon1** [comment]
Haven't tried it sorry, doesn't it appear to you in that order?

**Comment by xanderfrangos** [comment]
It does, I just wanted to make sure it was only a superficial UI bug. I've fixed the order for the next update. 👍

**Comment by xanderfrangos** [comment]
Fixed in v1.16.1!
