### ISSUE TITLE
[Request] Change contrast

### ISSUE THREAD

**Issue by hacchi-kh** [xanderfrangos/twinkle-tray#84]
The app is very useful, but currently the contrast cannot be changed. I'm eagerly looking forward to the addition of the ability to change the contrast with the slider. I like this app so much that I will pay for it if the ability to change the contrast is added.

**Comment by xanderfrangos** [comment]
@hacchi-kh I don't quite understand the need for frequent changes to contrast, so I have a few questions. Could you elaborate on how you'd be using the contrast control? Do you need it to replace the brightness slider on one or more monitors, or do you need it in addition to the brightness control? Is it just for one monitor, or multiple? Is it for managing eye strain, professional color work, or just personal preference?

**Comment by hacchi-kh** [comment]
I would like to have the ability to control contrast in addition to brightness control on multiple monitors. The reason I want that feature is due to the characteristics of my LG monitor. My LG monitor is dark at low contrast, even at full brightness. On the other hand, if the contrast is high, the monitor is brighter at the lowest brightness level.

I feel that the brightness setting alone is not enough for LG monitors. However, on the two ASUS monitors that I own, the brightness setting alone is sufficient.

With the LG monitor, I feel the need to change the contrast frequently to adjust the viewability. However, this may not be the case with other brands of monitors, such as ASUS. So I think it would be best to be able to switch the display of the contrast slider to different monitors.

I'm not an English speaker, so I use a translation tool. Please let me know if you don't understand any part of my English.

**Comment by xanderfrangos** [comment]
@hacchi-kh Thanks, that information helps a lot. 👍 I'll put it on my to-do list, but I can't promise when I'll add it. I'll leave this issue open until I add the feature.

In the meantime, I encourage anyone who is interested in the contrast control feature to describe why/how it would be useful to them so I can implement it in an optimal way.

**Comment by shadaxv** [comment]
I am for this functionality! My monitor is very bright, most often I have the brightness set to 0 and operate with a contrast that dims the image accordingly, I will love it if there will be possibility to change the contrast

**Comment by LakeishaKowalczyk** [comment]
+1
Contrast is another kind of brightness in some ways

**Comment by carbonox-infernox** [comment]
I made it here by googling for this feature. Since you asked about how it would be useful in order to implement it (albeit months ago), I'll try to pitch in.

I agree with others that contrast is necessary to get a full range of real brightness. When fumbling around through my monitor's clunky menu, I always increase or decrease them in tandem. 

The most straightforward implementation would be to add an extra slider for it, But a cooler way to do it would be to couple contrast to brightness. The user could specify a desired contrast level for 0% brightness and 100% brightness, and have the contrast be interpolated at other values. For example, I set my contrast to 10% at 0% brightness and 70% at 100% brightness. Sliding brightness up to 75% would put contrast at 55%.

**Comment by jasonesiegel** [comment]
Agreed, I would like contrast as well! The Lunar app for Mac (https://lunar.fyi/) adjusts brightness and contrast together, and I've found it helpful. When it's bright out, my Dell P2720QM, which I believe is the best 4k 27" external display currently available, is much easier to see when the contrast is turned up together with the brightness.

**Comment by xanderfrangos** [comment]
Thanks for all of the feedback, everyone! I will be including this as part of a larger feature in a future update. You can read more about it [here](https://github.com/xanderfrangos/twinkle-tray/issues/123). If anyone has suggestions/feedback about adjusting contrast over DDC/CI, please leave a comment there. Thanks!

**Comment by rizkhan7** [comment]
Thank you I am looking forward to an additional contrast slider!!!!! :) Twinkle tray is a very handy app!!!!

**Comment by normie555** [comment]
brightness without contrast is only half toe solution.Dont understand the authors confusion
