### ISSUE TITLE
multiple exe spawnes on ui open

### ISSUE THREAD

**Issue by Elendiar** [xanderfrangos/twinkle-tray#841]
After toggle `windows 11` taskbar option `automatically hide the taskbar`, new `Twinkle Tray.exe` always spawned when UI opened (after click on the tray icon).

![image](https://github.com/user-attachments/assets/9dc73300-ded2-4580-852f-dda50b916edc)

**Comment by xanderfrangos** [comment]
Thanks for the bug report!

Could you try this build and let me know if it solves the bug?
https://github.com/xanderfrangos/twinkle-tray/actions/runs/11096476769/artifacts/1993070459

**Comment by Elendiar** [comment]
> Could you try this build and let me know if it solves the bug? 

Yes, bug fixed, thanks.
