### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by jorgereymartinez** [xanderfrangos/twinkle-tray#847]
Version Number Data Type | Metadata

![image](https://github.com/user-attachments/assets/ca7022fd-a3ab-4fdd-950d-fcfb3edcf74e)
![image](https://github.com/user-attachments/assets/8f08732a-d02f-47ff-b997-f301bda97fd1)

Winget/UnigetUI confused with update.

**Comment by xanderfrangos** [comment]
Hi @jorgereymartinez,

I'm not sure which package manager this is referring to, as UnigetUI can reference several. Most of which are unofficially managed. However, according to this screenshot, the version number is being correctly identified as "1.16.1". The string that includes the build ID ("1.16.1+680c...") isn't shown in the winget repository. 

![Screenshot 2024-10-06 131037](https://github.com/user-attachments/assets/172866ba-db5d-4c40-a137-02c336cf5f2f)

As far as I can tell, there's no problem. That build string being displayed on the EXE "product version" is intentional.

**Comment by jorgereymartinez** [comment]
Hello again.

Not sure what's changed, but this is what I'm seeing on my end when I download the .exe when trying to figure out why UnigetUI and Winget get confused that it wants to download and update to the latest version when my machine already has the latest version.

![image](https://github.com/user-attachments/assets/062c7942-3f9d-4e25-b31f-b3259e9c6467)

I was thinking it is because of the version number being picked up from the .exe file, see above.

![image](https://github.com/user-attachments/assets/2d4b07e3-c04e-4628-aedb-5082878f87b5)

From UnigetUI, when I check for updates, the above is what is displayed and shown. IT still thinks it needs an update.

**Comment by jorgereymartinez** [comment]
Hello again.

Not sure what's changed, but this is what I'm seeing on my end when I download the .exe when trying to figure out why UnigetUI and Winget get confused that it wants to download and update to the latest version when my machine already has the latest version.

![image](https://github.com/user-attachments/assets/83c5cc49-51a0-404e-9a54-a90b209a4b36)

I thought it was because of the version number being picked up from the .exe file, see above.

![image](https://github.com/user-attachments/assets/f8b1458a-9901-4df1-8788-f3122595f48a)

From UnigetUI, when I check for updates, the above is what is displayed and shown. It still thinks it needs an update.

![image](https://github.com/user-attachments/assets/0f3fb46a-cd83-4e6c-8364-c792e7ba064d)

**Comment by jorgereymartinez** [comment]
Oh, I downloaded Twinkle.Tray.v1.16.2.exe from here, your GitHub releases by the way, and compared it with UnigetUI/winget to ensure it was getting the same package.

**Comment by guimil248** [comment]
Hello!

In [ci.yml](https://github.com/xanderfrangos/twinkle-tray/blob/master/.github/workflows/ci.yml), the **build ID** is appended to the **version number** and the data is passed to the `--config.extraMetadata.version` parameter.

After removing the ID from the `Build Win32 installer` block and building an executable, Twinkle Tray no longer appears in the **update list** and shows the **up-to-date version** in the **installed package list**:

![list_expected](https://github.com/user-attachments/assets/1147a306-57aa-4644-870e-245bc3b22502)

Compared to:

![update_actual](https://github.com/user-attachments/assets/f3969574-e8eb-495b-aa8f-38add252eca0)

**Comment by xanderfrangos** [comment]
The next update should have a product version that plays nice with winget. 👍

**Comment by xanderfrangos** [comment]
![Screenshot 2024-10-24 200258](https://github.com/user-attachments/assets/47681591-2492-4a3b-ac8a-950541f751a6)
Looks like it's happy with the version number again as of v1.16.3, so I'm going to close this.
