### ISSUE TITLE
[BUG!] v l.16.1 crash after sleep

### ISSUE THREAD

**Issue by shafayetejaman** [xanderfrangos/twinkle-tray#848]
![image](https://github.com/user-attachments/assets/29c4a7d3-e78c-4992-b32b-47c03190ec73)

systray icon is not showing and the mini pop window in the middle of the screen is not showing

**Comment by bluin4308** [comment]
Same. Got crash after sleep.
Acer Nitro AN515-46, Windows 11 Pro 23H2.

**Comment by bluin4308** [comment]
![Screenshot 2024-10-01 200911](https://github.com/user-attachments/assets/c82c6a1b-c3d5-48d7-a223-6198927b86b4)

**Comment by xanderfrangos** [comment]
I believe I've solved the issue. Can you give this build a try?

https://github.com/xanderfrangos/twinkle-tray/actions/runs/11203408539/artifacts/2020962451

**Comment by xanderfrangos** [comment]
Actually meant this build, whoops: https://github.com/xanderfrangos/twinkle-tray/actions/runs/11203745164/artifacts/2021022621

**Comment by xanderfrangos** [comment]
@shafayetejaman I'm not sure I follow. Can you provide more details?

**Comment by shafayetejaman** [comment]
https://drive.google.com/file/d/1-P5IJlkLFVUGrR9FVhHk8XPyaCV_Dzhk/view?usp=sharing
I meant the brightness level, goes 33 to 66

**Comment by FabianLoRs** [comment]
![a25s6das](https://github.com/user-attachments/assets/953439ce-9756-46ee-b165-edaff00f7145)


Same here
