### ISSUE TITLE
Brightness does not change after uninstall

### ISSUE THREAD

**Issue by KrishnaMusicc** [xanderfrangos/twinkle-tray#850]
Hey there! How come when I uninstall the program, my brightness levels on all monitors remain? Say if I put it to 0%, when I uninstall the brightness will stay at 0%

**Comment by xanderfrangos** [comment]
If you've uninstalled Twinkle Tray, it can no longer change the brightness level. You'll have to adjust the brightness using the hardware controls on your monitor (or use a different DDC/CI app).

**Comment by KrishnaMusicc** [comment]
What % is the default brightness? I think that's my only concern tbh

**Comment by xanderfrangos** [comment]
There's no universal default brightness. If you're referring to the out-of-the-box settings for you monitor, you can try using the built-in presets (if it offers them) or do a factory reset.

**Comment by KrishnaMusicc** [comment]
Understood. Thanks!
