### ISSUE TITLE
Animate between times awakening the monitor

### ISSUE THREAD

**Issue by brunoosti** [xanderfrangos/twinkle-tray#854]
v 1.16.1
monitor LG ultrawide  34GP63A-B

After going standby (Windows power settings), monitor constantly and randomly awakes briefly (showing  only "no image" message) and goes back to standby if twinkle tray is set to animate between times. 

Additionally, if animate is off and the monitor was on standby, twinkle tray is not capable of adjusting brightness anymore after the  monitor is turned on again. This does not happen if the whole PC goes to sleep (because twinkle tray applies settings at startup I imagine). 

Thank you! The app is GREAT!

**Comment by xanderfrangos** [comment]
This build might help with your first issue: https://github.com/xanderfrangos/twinkle-tray/actions/runs/11225895557/artifacts/2026769702

As for the second, does adjusting the brightness work again if you right-click the tray icon and hit "Refresh displays"?

**Comment by brunoosti** [comment]
Thank you very much! : ) 
Sorry, forgot to describe that. Yes, if i refresh displays Twinkle Tray grabs the current brightness from the monitor but does not automatically sets the current time brightness adjustment. It works if I manually adjust . I can imagine It will automatically set a future time adjustment, also.

**Comment by brunoosti** [comment]
The build works perfectly. Thank you! I'll close the issue now. 

If there is a way, it would be useful the app detecting the monitor coming back from standby and run a refresh / apply the closest time brightness setting. 
Animating between times is a better config in my opinion, as it soothes the transition and your eyes accommodate better. Can also be used as a good workaround if you set close times to instantly change brightness (5:59 and 6PM, lets say), at the cost of no manual adjustment.

Thanks!

**Comment by brunoosti** [comment]
On recent update, v 1.16.7, Twinkle Tray sometimes can't update brightness after waking the PC up from sleep. Even if refreshing monitors.
