### ISSUE TITLE
It just doesn't turn on

### ISSUE THREAD

**Issue by redwan-demo** [xanderfrangos/twinkle-tray#857]
Installed fresh windows 10 in my device recently. In previous windows, it worked fine. But after installing a fresh windows 10, the software doesn't open and let me change the brightness. More specifically, it does show up in notification tray, when I want to open it. It does render me to settings when clicking on settings. But it just don't show up when I am trying to change the brightness. I mean, in notification tray, when you click on the app, a small window is gonna pop up where you may higher or lower the brightness, right? It doesn't show to me. Other software similar to this - are working fine, but not this. Tried uninstalling then reinstalling couple of times, but failed anyways.

**Comment by xanderfrangos** [comment]
Hi @redwan-demo, are you using the version from the Microsoft Store or the installer from GitHub/twinkletray.com?

**Comment by redwan-demo** [comment]
I tried using from Microsoft store and from GitHub both. But currently I installed from Microsoft Store.

**Comment by xanderfrangos** [comment]
I recommend uninstalling both versions and then installing only the GitHub version. Don't have both installed at the same time.

If it's still not working, go into the settings and generate a report for me to take a look at:
<img src="https://github.com/user-attachments/assets/e852d8be-2034-4862-8281-5768cc5d3d0e" width="1000">

**Comment by redwan-demo** [comment]
{
	"type": "getReport",
	"report": {
		"lastDDCCIList": [
			{
				"ddcciSupported": true,
				"hlBrightnessSupported": true,
				"hlContrastSupported": true,
				"handleIsValid": true,
				"name": "\\\\.\\DISPLAY1",
				"fullName": "\\\\.\\DISPLAY1\\Monitor0",
				"physicalName": "\\\\.\\DISPLAY1\\Monitor0",
				"deviceKey": "\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257",
				"deviceID": "\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
				"capabilities": {
					"0x02": [],
					"0x04": [],
					"0x05": [],
					"0x06": [],
					"0x08": [],
					"0x10": [],
					"0x12": [],
					"0x14": [
						5,
						8,
						11,
						12
					],
					"0x16": [],
					"0x18": [],
					"0x1A": [],
					"0x52": [],
					"0x60": [
						1,
						17
					],
					"0x62": [],
					"0xAC": [],
					"0xAE": [],
					"0xB2": [],
					"0xB6": [],
					"0xC6": [],
					"0xC8": [],
					"0xC9": [],
					"0xD6": [
						1,
						4,
						5
					],
					"0xDC": [
						0,
						2,
						3,
						5
					],
					"0xDF": [],
					"0xE0": [],
					"0xE1": [],
					"0xE2": [
						0,
						1,
						2,
						4,
						25,
						14,
						18,
						20
					],
					"0xF0": [
						0,
						8
					],
					"0xF1": [
						1
					],
					"0xF2": [
						0,
						1
					],
					"0xFD": []
				},
				"capabilitiesRaw": "(prot(monitor)type(LCD)model(S2216H)cmds(01 02 03 07 0C E3 F3)vcp(02 04 05 06 08 10 12 14(05 08 0B 0C) 16 18 1A 52 60(01 11) 62 AC AE B2 B6 C6 C8 C9 D6(01 04 05) DC(00 02 03 05) DF E0 E1 E2(00 01 02 04 19 0E 12 14) F0(00 08) F1(01) F2(00 01) FD)mswhql(1)asset_eep(40)mccs_ver(2.1))"
			}
		],
		"lastWMI": {},
		"lastWin32": {
			"5&28e4fc6d&0&UID257": {
				"id": "\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257",
				"key": "5&28e4fc6d&0&UID257",
				"connector": "hdmi",
				"hwid": [
					"\\\\?\\DISPLAY",
					"DELD07A",
					"5&28e4fc6d&0&UID257",
					"{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}"
				],
				"sourceID": 0,
				"scaling": "identity",
				"bounds": {
					"width": 1920,
					"height": 1080,
					"pixelFormat": 32,
					"position": {
						"x": 0,
						"y": 0
					}
				},
				"name": "DELL S2216H"
			}
		},
		"monitorsAppleStudio": {},
		"monitorReports": {
			"\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257": {
				"0x02": [],
				"0x04": [],
				"0x05": [],
				"0x06": [],
				"0x08": [],
				"0x10": [],
				"0x12": [],
				"0x14": [
					5,
					8,
					11,
					12
				],
				"0x16": [],
				"0x18": [],
				"0x1A": [],
				"0x52": [],
				"0x60": [
					1,
					17
				],
				"0x62": [],
				"0xAC": [],
				"0xAE": [],
				"0xB2": [],
				"0xB6": [],
				"0xC6": [],
				"0xC8": [],
				"0xC9": [],
				"0xD6": [
					1,
					4,
					5
				],
				"0xDC": [
					0,
					2,
					3,
					5
				],
				"0xDF": [],
				"0xE0": [],
				"0xE1": [],
				"0xE2": [
					0,
					1,
					2,
					4,
					25,
					14,
					18,
					20
				],
				"0xF0": [
					0,
					8
				],
				"0xF1": [
					1
				],
				"0xF2": [
					0,
					1
				],
				"0xFD": []
			}
		},
		"monitorReportsRaw": {},
		"lastRefresh": {
			"5&28e4fc6d&0&UID257": {
				"id": "\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257",
				"key": "5&28e4fc6d&0&UID257",
				"num": 0,
				"brightness": 100,
				"brightnessMax": 100,
				"brightnessRaw": 100,
				"type": "ddcci",
				"connector": "hdmi",
				"min": 0,
				"max": 100,
				"hwid": [
					"\\\\?\\DISPLAY",
					"DELD07A",
					"5&28e4fc6d&0&UID257"
				],
				"name": "DELL S2216H",
				"serial": "VJRF75973RGT",
				"sourceID": 0,
				"scaling": "identity",
				"bounds": {
					"width": 1920,
					"height": 1080,
					"pixelFormat": 32,
					"position": {
						"x": 0,
						"y": 0
					}
				},
				"path": "\\\\.\\DISPLAY1\\Monitor0",
				"ddcciSupported": true,
				"highLevelSupported": {
					"brightness": true,
					"contrast": true
				},
				"features": {
					"0x10": [
						100,
						100,
						0
					],
					"0x13": false,
					"0x12": [
						93,
						100
					],
					"0xD6": [
						1,
						5
					],
					"0x62": [
						100,
						100
					]
				},
				"vcpCodes": {
					"0x02": [],
					"0x04": [],
					"0x05": [],
					"0x06": [],
					"0x08": [],
					"0x10": [],
					"0x12": [],
					"0x14": [
						5,
						8,
						11,
						12
					],
					"0x16": [],
					"0x18": [],
					"0x1A": [],
					"0x52": [],
					"0x60": [
						1,
						17
					],
					"0x62": [],
					"0xAC": [],
					"0xAE": [],
					"0xB2": [],
					"0xB6": [],
					"0xC6": [],
					"0xC8": [],
					"0xC9": [],
					"0xD6": [
						1,
						4,
						5
					],
					"0xDC": [
						0,
						2,
						3,
						5
					],
					"0xDF": [],
					"0xE0": [],
					"0xE1": [],
					"0xE2": [
						0,
						1,
						2,
						4,
						25,
						14,
						18,
						20
					],
					"0xF0": [
						0,
						8
					],
					"0xF1": [
						1
					],
					"0xF2": [
						0,
						1
					],
					"0xFD": []
				},
				"brightnessType": 16,
				"brightnessValues": [
					100,
					100,
					0
				]
			}
		},
		"settings": {
			"isDev": false,
			"settingsVer": "v1.16.2",
			"settingsBuild": "d93d7c4b4c982544e0d7364df769b7ce56e8db6c",
			"userClosedIntro": true,
			"theme": "default",
			"icon": "icon",
			"updateInterval": 500,
			"openAtLogin": true,
			"brightnessAtStartup": true,
			"killWhenIdle": false,
			"remaps": {},
			"hotkeys": [],
			"hotkeyPercent": 10,
			"adjustmentTimes": [],
			"adjustmentTimeIndividualDisplays": false,
			"adjustmentTimeSpeed": "normal",
			"adjustmentTimeAnimate": false,
			"adjustmentTimeLongitude": 0,
			"adjustmentTimeLatitude": 0,
			"checkTimeAtStartup": true,
			"order": [],
			"monitorFeatures": {},
			"monitorFeaturesSettings": {
				"DELD07A": {
					"0x12": {
						"icon": "e897",
						"iconType": "windows",
						"iconText": "",
						"iconPath": "",
						"min": 0,
						"max": 100,
						"maxVisual": 100,
						"linked": false
					},
					"0x62": {
						"icon": "e897",
						"iconType": "windows",
						"iconText": "",
						"iconPath": "",
						"min": 0,
						"max": 100,
						"maxVisual": 100,
						"linked": false
					},
					"0xD6": {
						"icon": "e897",
						"iconType": "windows",
						"iconText": "",
						"iconPath": "",
						"min": 0,
						"max": 100,
						"maxVisual": 100,
						"linked": false
					}
				}
			},
			"hideDisplays": {},
			"checkForUpdates": true,
			"dismissedUpdate": "",
			"language": "system",
			"names": {},
			"analytics": true,
			"scrollShortcut": true,
			"scrollShortcutAmount": 2,
			"scrollFlyoutAmount": 2,
			"useAcrylic": false,
			"useNativeAnimation": false,
			"sleepAction": "ps",
			"hotkeysBreakLinkedLevels": true,
			"enableSunValley": true,
			"isWin11": false,
			"windowsStyle": "system",
			"hideClosedLid": false,
			"getDDCBrightnessUpdates": false,
			"detectIdleTimeEnabled": false,
			"detectIdleTimeSeconds": 0,
			"detectIdleTimeMinutes": 5,
			"detectIdleCheckFullscreen": false,
			"detectIdleMedia": false,
			"idleRestoreSeconds": 0,
			"wakeRestoreSeconds": 0,
			"hardwareRestoreSeconds": 0,
			"checkVCPWaitMS": 20,
			"overrideTaskbarPosition": false,
			"overrideTaskbarGap": false,
			"disableAppleStudio": false,
			"disableHighLevel": false,
			"disableWMIC": false,
			"disableWMI": false,
			"disableWin32": false,
			"enableHDR": false,
			"autoDisabledWMI": false,
			"useWin32Event": true,
			"useElectronEvents": true,
			"useWmDisplayChangeEvent": true,
			"useScMonitorPowerEvent": true,
			"useGuidPresenceEvent": true,
			"useGuidBrightnessEvent": true,
			"recreateTray": false,
			"recreateFlyout": false,
			"defaultOverlayType": "safe",
			"disableMouseEvents": false,
			"disableThrottling": false,
			"userDDCBrightnessVCPs": {},
			"userSkipReapply": [],
			"preferredDDCCIMethod": "accurate",
			"lastDetectedDDCCIMethod": "none",
			"forceLowPowerGPU": false,
			"ddcPowerOffValue": 5,
			"disableAutoRefresh": false,
			"disableAutoApply": false,
			"udpEnabled": false,
			"udpRemote": false,
			"udpPortStart": 14715,
			"udpPortActive": 14715,
			"udpKey": "19df3c09-8c9d-4398-a35a-a766432c79c7",
			"showConsole": false,
			"profiles": [],
			"uuid": "aade3671-e71f-46c7-bdc6-c170216a73e2",
			"branch": "master"
		}
	}
}

[tt-report-1728568901667.txt](https://github.com/user-attachments/files/17329307/tt-report-1728568901667.txt)

**Comment by redwan-demo** [comment]
[tt-report-1728568901667.txt](https://github.com/user-attachments/files/17329314/tt-report-1728568901667.txt)

{
	"type": "getReport",
	"report": {
		"lastDDCCIList": [
			{
				"ddcciSupported": true,
				"hlBrightnessSupported": true,
				"hlContrastSupported": true,
				"handleIsValid": true,
				"name": "\\\\.\\DISPLAY1",
				"fullName": "\\\\.\\DISPLAY1\\Monitor0",
				"physicalName": "\\\\.\\DISPLAY1\\Monitor0",
				"deviceKey": "\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257",
				"deviceID": "\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
				"capabilities": {
					"0x02": [],
					"0x04": [],
					"0x05": [],
					"0x06": [],
					"0x08": [],
					"0x10": [],
					"0x12": [],
					"0x14": [
						5,
						8,
						11,
						12
					],
					"0x16": [],
					"0x18": [],
					"0x1A": [],
					"0x52": [],
					"0x60": [
						1,
						17
					],
					"0x62": [],
					"0xAC": [],
					"0xAE": [],
					"0xB2": [],
					"0xB6": [],
					"0xC6": [],
					"0xC8": [],
					"0xC9": [],
					"0xD6": [
						1,
						4,
						5
					],
					"0xDC": [
						0,
						2,
						3,
						5
					],
					"0xDF": [],
					"0xE0": [],
					"0xE1": [],
					"0xE2": [
						0,
						1,
						2,
						4,
						25,
						14,
						18,
						20
					],
					"0xF0": [
						0,
						8
					],
					"0xF1": [
						1
					],
					"0xF2": [
						0,
						1
					],
					"0xFD": []
				},
				"capabilitiesRaw": "(prot(monitor)type(LCD)model(S2216H)cmds(01 02 03 07 0C E3 F3)vcp(02 04 05 06 08 10 12 14(05 08 0B 0C) 16 18 1A 52 60(01 11) 62 AC AE B2 B6 C6 C8 C9 D6(01 04 05) DC(00 02 03 05) DF E0 E1 E2(00 01 02 04 19 0E 12 14) F0(00 08) F1(01) F2(00 01) FD)mswhql(1)asset_eep(40)mccs_ver(2.1))"
			}
		],
		"lastWMI": {},
		"lastWin32": {
			"5&28e4fc6d&0&UID257": {
				"id": "\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257",
				"key": "5&28e4fc6d&0&UID257",
				"connector": "hdmi",
				"hwid": [
					"\\\\?\\DISPLAY",
					"DELD07A",
					"5&28e4fc6d&0&UID257",
					"{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}"
				],
				"sourceID": 0,
				"scaling": "identity",
				"bounds": {
					"width": 1920,
					"height": 1080,
					"pixelFormat": 32,
					"position": {
						"x": 0,
						"y": 0
					}
				},
				"name": "DELL S2216H"
			}
		},
		"monitorsAppleStudio": {},
		"monitorReports": {
			"\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257": {
				"0x02": [],
				"0x04": [],
				"0x05": [],
				"0x06": [],
				"0x08": [],
				"0x10": [],
				"0x12": [],
				"0x14": [
					5,
					8,
					11,
					12
				],
				"0x16": [],
				"0x18": [],
				"0x1A": [],
				"0x52": [],
				"0x60": [
					1,
					17
				],
				"0x62": [],
				"0xAC": [],
				"0xAE": [],
				"0xB2": [],
				"0xB6": [],
				"0xC6": [],
				"0xC8": [],
				"0xC9": [],
				"0xD6": [
					1,
					4,
					5
				],
				"0xDC": [
					0,
					2,
					3,
					5
				],
				"0xDF": [],
				"0xE0": [],
				"0xE1": [],
				"0xE2": [
					0,
					1,
					2,
					4,
					25,
					14,
					18,
					20
				],
				"0xF0": [
					0,
					8
				],
				"0xF1": [
					1
				],
				"0xF2": [
					0,
					1
				],
				"0xFD": []
			}
		},
		"monitorReportsRaw": {},
		"lastRefresh": {
			"5&28e4fc6d&0&UID257": {
				"id": "\\\\?\\DISPLAY#DELD07A#5&28e4fc6d&0&UID257",
				"key": "5&28e4fc6d&0&UID257",
				"num": 0,
				"brightness": 100,
				"brightnessMax": 100,
				"brightnessRaw": 100,
				"type": "ddcci",
				"connector": "hdmi",
				"min": 0,
				"max": 100,
				"hwid": [
					"\\\\?\\DISPLAY",
					"DELD07A",
					"5&28e4fc6d&0&UID257"
				],
				"name": "DELL S2216H",
				"serial": "VJRF75973RGT",
				"sourceID": 0,
				"scaling": "identity",
				"bounds": {
					"width": 1920,
					"height": 1080,
					"pixelFormat": 32,
					"position": {
						"x": 0,
						"y": 0
					}
				},
				"path": "\\\\.\\DISPLAY1\\Monitor0",
				"ddcciSupported": true,
				"highLevelSupported": {
					"brightness": true,
					"contrast": true
				},
				"features": {
					"0x10": [
						100,
						100,
						0
					],
					"0x13": false,
					"0x12": [
						93,
						100
					],
					"0xD6": [
						1,
						5
					],
					"0x62": [
						100,
						100
					]
				},
				"vcpCodes": {
					"0x02": [],
					"0x04": [],
					"0x05": [],
					"0x06": [],
					"0x08": [],
					"0x10": [],
					"0x12": [],
					"0x14": [
						5,
						8,
						11,
						12
					],
					"0x16": [],
					"0x18": [],
					"0x1A": [],
					"0x52": [],
					"0x60": [
						1,
						17
					],
					"0x62": [],
					"0xAC": [],
					"0xAE": [],
					"0xB2": [],
					"0xB6": [],
					"0xC6": [],
					"0xC8": [],
					"0xC9": [],
					"0xD6": [
						1,
						4,
						5
					],
					"0xDC": [
						0,
						2,
						3,
						5
					],
					"0xDF": [],
					"0xE0": [],
					"0xE1": [],
					"0xE2": [
						0,
						1,
						2,
						4,
						25,
						14,
						18,
						20
					],
					"0xF0": [
						0,
						8
					],
					"0xF1": [
						1
					],
					"0xF2": [
						0,
						1
					],
					"0xFD": []
				},
				"brightnessType": 16,
				"brightnessValues": [
					100,
					100,
					0
				]
			}
		},
		"settings": {
			"isDev": false,
			"settingsVer": "v1.16.2",
			"settingsBuild": "d93d7c4b4c982544e0d7364df769b7ce56e8db6c",
			"userClosedIntro": true,
			"theme": "default",
			"icon": "icon",
			"updateInterval": 500,
			"openAtLogin": true,
			"brightnessAtStartup": true,
			"killWhenIdle": false,
			"remaps": {},
			"hotkeys": [],
			"hotkeyPercent": 10,
			"adjustmentTimes": [],
			"adjustmentTimeIndividualDisplays": false,
			"adjustmentTimeSpeed": "normal",
			"adjustmentTimeAnimate": false,
			"adjustmentTimeLongitude": 0,
			"adjustmentTimeLatitude": 0,
			"checkTimeAtStartup": true,
			"order": [],
			"monitorFeatures": {},
			"monitorFeaturesSettings": {
				"DELD07A": {
					"0x12": {
						"icon": "e897",
						"iconType": "windows",
						"iconText": "",
						"iconPath": "",
						"min": 0,
						"max": 100,
						"maxVisual": 100,
						"linked": false
					},
					"0x62": {
						"icon": "e897",
						"iconType": "windows",
						"iconText": "",
						"iconPath": "",
						"min": 0,
						"max": 100,
						"maxVisual": 100,
						"linked": false
					},
					"0xD6": {
						"icon": "e897",
						"iconType": "windows",
						"iconText": "",
						"iconPath": "",
						"min": 0,
						"max": 100,
						"maxVisual": 100,
						"linked": false
					}
				}
			},
			"hideDisplays": {},
			"checkForUpdates": true,
			"dismissedUpdate": "",
			"language": "system",
			"names": {},
			"analytics": true,
			"scrollShortcut": true,
			"scrollShortcutAmount": 2,
			"scrollFlyoutAmount": 2,
			"useAcrylic": false,
			"useNativeAnimation": false,
			"sleepAction": "ps",
			"hotkeysBreakLinkedLevels": true,
			"enableSunValley": true,
			"isWin11": false,
			"windowsStyle": "system",
			"hideClosedLid": false,
			"getDDCBrightnessUpdates": false,
			"detectIdleTimeEnabled": false,
			"detectIdleTimeSeconds": 0,
			"detectIdleTimeMinutes": 5,
			"detectIdleCheckFullscreen": false,
			"detectIdleMedia": false,
			"idleRestoreSeconds": 0,
			"wakeRestoreSeconds": 0,
			"hardwareRestoreSeconds": 0,
			"checkVCPWaitMS": 20,
			"overrideTaskbarPosition": false,
			"overrideTaskbarGap": false,
			"disableAppleStudio": false,
			"disableHighLevel": false,
			"disableWMIC": false,
			"disableWMI": false,
			"disableWin32": false,
			"enableHDR": false,
			"autoDisabledWMI": false,
			"useWin32Event": true,
			"useElectronEvents": true,
			"useWmDisplayChangeEvent": true,
			"useScMonitorPowerEvent": true,
			"useGuidPresenceEvent": true,
			"useGuidBrightnessEvent": true,
			"recreateTray": false,
			"recreateFlyout": false,
			"defaultOverlayType": "safe",
			"disableMouseEvents": false,
			"disableThrottling": false,
			"userDDCBrightnessVCPs": {},
			"userSkipReapply": [],
			"preferredDDCCIMethod": "accurate",
			"lastDetectedDDCCIMethod": "none",
			"forceLowPowerGPU": false,
			"ddcPowerOffValue": 5,
			"disableAutoRefresh": false,
			"disableAutoApply": false,
			"udpEnabled": false,
			"udpRemote": false,
			"udpPortStart": 14715,
			"udpPortActive": 14715,
			"udpKey": "19df3c09-8c9d-4398-a35a-a766432c79c7",
			"showConsole": false,
			"profiles": [],
			"uuid": "aade3671-e71f-46c7-bdc6-c170216a73e2",
			"branch": "master"
		}
	}
}

**Comment by redwan-demo** [comment]
Any update?

**Comment by xanderfrangos** [comment]
I haven't been able to work out any reason why this would happen. It seems to be something particular to your PC or monitor configuration. I'm unfortunately away from home for a few days and can't look into it more until then.

**Comment by redwan-demo** [comment]
I installed freshly windows 10 once again.. It is working now.

**Comment by xanderfrangos** [comment]
Glad to hear you eventually got it working. Sounds like maybe it was a driver issue.
