### ISSUE TITLE
[Feature request] Change installation directory when installing the application

### ISSUE THREAD

**Issue by Ptilopsis01** [xanderfrangos/twinkle-tray#858]
As the title said, I personally don't like applications installed into %userdata% path, and I hope that the installation path can be chosen in the future versions.

**Comment by xanderfrangos** [comment]
You can set the installation directory by running the installer with the the `/D` parameter, like so: 
```
Twinkle.Tray.v1.16.2.exe /D="C:\Custom\Install\Path"
```

**Comment by Ptilopsis01** [comment]
It works, thanks
