### ISSUE TITLE
Monitor Restart

### ISSUE THREAD

**Issue by Bribbo38** [xanderfrangos/twinkle-tray#863]
I have a Samsung Odyssey G5 as my main monitor and an old HP as secondary. My HP works just fine but the Samsung it just reboot every time a signal is send, and it doesn't change the brightness. I managed to make it work a couple of time but I don't know how or make it work again.
I also installed the newest driver that I could find for the monitor and that didn't help.

If you need any other information I can give them no problem.

**Comment by Bribbo38** [comment]
[tt-report-1729423282848.txt](https://github.com/user-attachments/files/17450013/tt-report-1729423282848.txt)

Here is the report if you need

**Comment by xanderfrangos** [comment]
Hmm, it seems like a weird monitor. However, nothing looks wrong in the report. Maybe try turning off "DDC/CI HL" under `General -> Troubleshooting -> Enabled monitor detection methods` and restarting Twinkle Tray. 

If it's still not playing nice, I'd recommend trying [ControlMyMonitor](https://www.nirsoft.net/utils/control_my_monitor.html) ([ZIP download](https://www.nirsoft.net/utils/controlmymonitor.zip)). Let me know if you're able to adjust the brightness with that (VCP code "10") without issues.

**Comment by Bribbo38** [comment]
Thank you for your help.
Unfortunately it does the same thing, with DDC/CI disabled and with ControlMyMonitor. It just reboots and doesn't change the brightness.

**Comment by xanderfrangos** [comment]
Unfortunately, it sounds like Samsung didn't implement DDC/CI in this model properly. It's possible that there are settings on the display that may help, but it ultimately may not be compatible with any DDC/CI apps.

**Comment by Bribbo38** [comment]
Ok, thank you anyway
