### ISSUE TITLE
Trinkle Tray spawns many processes

### ISSUE THREAD

**Issue by toftware** [xanderfrangos/twinkle-tray#875]
Sometimes Twinkle Tray spawns many processes of itself and makes everything rather slow. Is it cryptomining or what's going on 🤣

I couldn't make it do a dump because my system wasn't responding well.

![image](https://github.com/user-attachments/assets/54fbee2b-807f-4d35-b4a3-b76a52f2ac7b)

**Comment by xanderfrangos** [comment]
Yikes! There should only be 5. I think I know what's going on, but can you check two things for me?

1. Let me know which version of Twinkle Tray you're using.
2. In the Task Manager "Details" tab, can you enable the "Command Line" column and take a screenshot of the extra processes? It'll look like this:

![Screenshot 2024-10-29 162100](https://github.com/user-attachments/assets/0cdb3bab-8e8a-453b-aaf7-747e8bd85c41)

(I need to see at least a little bit of what comes after `Twinkle Tray.exe` in the command line column.)

**Comment by xanderfrangos** [comment]
Oh, I had fixed a bug that caused this as v1.16.1. The latest version is v1.16.3: https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.16.3

**Comment by toftware** [comment]
Ahh ok, i was just about to update it, i saw it began happening again, although not so crazy as of yet.

![image](https://github.com/user-attachments/assets/899f23f0-8813-4a3a-9b07-a7982adafac7)

**Comment by toftware** [comment]
If this bug was fixed then i'll just close this issue, i haven't seen it since the update.
