### ISSUE TITLE
Flyout opens off screen when taskbar is on top of screen.

### ISSUE THREAD

**Issue by ruifung** [xanderfrangos/twinkle-tray#88]
When the taskbar is on the top of the screen, the flyout doesn't appear. I suspect it is opening off screen as when the taskbar is on the side / bottom of the display, it opens just fine.

**Comment by xanderfrangos** [comment]
You are correct. I'll get that fixed. Thanks for the bug report! 👍

**Comment by xanderfrangos** [comment]
@ruifung I've released an update (v1.12.3) which fixes the issue. The non-Windows Store version is available now and the Windows Store version should be available soon. Let me know if for some reason the issue hasn't been fixed in v1.12.3. Thanks!

**Comment by ruifung** [comment]
Just saw this and yeah, it's fixed now.
