### ISSUE TITLE
BenQ GW2480 not supported - although the monitor supports DDC/CI and it's enabled in osd

### ISSUE THREAD

**Issue by notworthyguy** [xanderfrangos/twinkle-tray#91]
I just discovered this awesome app and and I ran into a small problem with the second monitor.
The monitor is connected with HDMI cable, running latest AMD Adrenalin 20.9.1 WHQL driver.
Here is the monitor manual: https://images-eu.ssl-images-amazon.com/images/I/C1rf83w6VZS.pdf

![Untitled](https://user-images.githubusercontent.com/72736339/95732048-9203c580-0c80-11eb-9bc3-6de7a59ef1dd.png)

**Comment by notworthyguy** [comment]
Here is another example. 

This is on my PC at work. Both monitors are BenQ GW2480, they support DDC/CI and it's enabled in osd. One monitor is connected with HDMI cable and the other one with VGA cable.

![Untitled](https://user-images.githubusercontent.com/72736339/95846812-2d15a180-0d4c-11eb-8e20-d9966c2ea6a4.png)

**Comment by xanderfrangos** [comment]
@notworthyguy Could you check if Dynamic Contrast Range (DCR) is enabled on your display? Apparently it's known to interfere with brightness control over DDC/CI on that monitor. And just to confirm you do have DDC/CI enabled on the monitor, per the manual?

**Comment by notworthyguy** [comment]
@xanderfrangos DCR is disabled. Yes, DDC/CI is enabled since I got the monitor year ago.
![IMG_20201016_225207](https://user-images.githubusercontent.com/72736339/96307865-932b4e80-1002-11eb-9275-2cc24d2dd710.jpg)
![IMG_20201016_225243](https://user-images.githubusercontent.com/72736339/96307939-b2c27700-1002-11eb-9323-dbfcf4adb283.jpg)

**Comment by galaxy9064** [comment]
My LG W2253TQ has an similar issue。
Yesterday I connect my laptop to my LG monitor， twinkle tray（TT）worked very well，and it said my LG support DDC/CI.
However, today TT lost the sliderbar to my LG monitor, TT says my LG monitor support NONE communication method.
I've restarted TT, LG monitor and my laptop several times, still TT cannot retrieve control to my LG monitor.
Confused,
![QQ拼音截图20201109200723](https://user-images.githubusercontent.com/16928950/98539411-3d775880-22c7-11eb-8b8b-d0a484a5be4d.png)

**Comment by xanderfrangos** [comment]
Could you guys check if [ControlMyMonitor](https://www.nirsoft.net/utils/control_my_monitor.html) works with these displays? If so, could you take a screenshot of the monitor's values? I'm guessing VCP code 0x10 ("luminance") isn't working, but another (ex. 0x13) is.

**Comment by notworthyguy** [comment]
![image](https://user-images.githubusercontent.com/72736339/99108050-11214c00-25e7-11eb-80c2-1b6b03c3bd60.png)
![image](https://user-images.githubusercontent.com/72736339/99108109-27c7a300-25e7-11eb-8eaf-923fdabd25e1.png)

**Comment by xanderfrangos** [comment]
@notworthyguy Thanks for the screenshots. 👍

According to the second screenshot, ControlMyMonitor can't communicate with your BenQ GW2480. Since neither Twinkle Tray nor ControlMyMonitor can communicate with the monitor, it's not a problem with either DDC/CI software. It's most likely either:
- A setting on the monitor preventing DDC/CI from working properly.
- An AMD driver issue.
- Or a hardware issue.

All I can suggest is that you try toggling options on the monitor and in the AMD drivers, and see if connecting to different HDMI/DisplayPort ports helps.

**Comment by notworthyguy** [comment]
@xanderfrangos thanks bro for the fast reply, I will test everything and let you know.

**Comment by notworthyguy** [comment]
@xanderfrangos issue is solved, I've swapped the cables and now DDC/CI works on both monitors.

![image](https://user-images.githubusercontent.com/72736339/99145546-23939800-2670-11eb-831a-fbf63e28ec8e.png)

**Comment by xanderfrangos** [comment]
@notworthyguy Glad to hear you got it working, and thanks for sharing the solution! I'll add it to the wiki. 👍

**Comment by notworthyguy** [comment]
@notworthyguy you're welcome 🤙
