### ISSUE TITLE
WMIC and hanging after update

### ISSUE THREAD

**Issue by ninjaguardian** [xanderfrangos/twinkle-tray#914]
Hello! Because WMIC is a security risk, I blocked it using AppLocker, but WMI can still run fine. In my event logs, whenever I interact with Twinkle Tray, I see many WMIC executions blocked. Does Twinkle Tray use WMI or WMIC?

Update:
I just realized that you can turn it off. It seems to be fine now.

Also, after I updated Twinkle Tray from the MS store, I got this error:
<details>
<summary> Error</summary>
Description

A problem caused this program to stop interacting with Windows.

Faulting Application Path: C:\Program Files\WindowsApps\38002AlexanderFrangos.TwinkleTray_1.15.5.0_x64__m7qx9dzpwqaze\app\Twinkle Tray.exe

Problem signature
Problem Event Name:	MoAppHang
Package Full Name:	38002AlexanderFrangos.TwinkleTray_1.15.5.0_x64__m7qx9dzpwqaze
Application Name:	praid:TwinkleTray
Application Version:	1.15.5.0
Application Timestamp:	63e3c5b4
Hang Signature:	2a93
Hang Type:	2097152
OS Version:	10.0.22635.2.0.0.256.48
Locale ID:	1033
Additional Hang Signature 1:	2a9320fdfb79da20e9650a8639979fad
Additional Hang Signature 2:	180c
Additional Hang Signature 3:	180c9eef293a03916f3a7ba477cef2c2
Additional Hang Signature 4:	2a93
Additional Hang Signature 5:	2a9320fdfb79da20e9650a8639979fad
Additional Hang Signature 6:	180c
Additional Hang Signature 7:	180c9eef293a03916f3a7ba477cef2c2

Extra information about the problem
Bucket ID:	cad70dd4c69026c757e755d0997f2d3b (1722439736909311291)
</details>

Also, I can't change the brightness of my monitor. Is that normal with HDR?

**Comment by xanderfrangos** [comment]
Hi @ninjaguardian,

Twinkle Tray uses both WMIC and the regular WMI API, depending on what's available/enabled. You can disable WMIC from `General -> Troubleshooting -> Enabled monitor detection methods`. 

The error unfortunately isn't telling me much about the issue, but it's saying it's for v1.15.5. It might have just been the old version closing to update to v1.16.4.

Many monitors stop responding to brightness/contrast DDC/CI commands when HDR is active. It may also depend on the color preset selected on your monitor. There will eventually be an update to adjust the Windows "SDR brightness" value in Twinkle Tray, but currently it's a WIP. You can read more about it towards the end of [this issue](https://github.com/xanderfrangos/twinkle-tray/issues/97).

**Comment by ninjaguardian** [comment]
Ok! Thank you!
