### ISSUE TITLE
[Help wanted]Unable to set theme(light/dark)

### ISSUE THREAD

**Issue by ClokMuch** [xanderfrangos/twinkle-tray#95]
**I can't find the switch for app theme changing(light/dark).**

It happened like this:
    I used an old ver.1.11.4, and set a light app theme, so i got used to its appearance. But after I update ver.1.12.3, app theme changed to dark background, then I tried to find the switch, but I failed.

Then, I closed the app and tried to edit file: _%userprofile%\AppData\Roaming\twinkle-tray\settings.json_:
```
    "theme":"default"
   ↓
    "theme":"light"
```
Relaunch app, but nothing changed(still dark background), and I read the file(settings.json) again, it restored.

So, that all, could you please provide help?

Looking forward to your replay.

raw user configs in Debug page:
```
{
  "isDev": false,
  "userClosedIntro": true,
  "theme": "default",
  "icon": "icon",
  "updateInterval": 500,
  "openAtLogin": true,
  "killWhenIdle": false,
  "remaps": {
    "DISPLAY\\BOE0747\\4&amp;8a52dc4&amp;0&amp;UID265988_0": {
      "min": 0,
      "max": 25
    }
  },
  "hotkeys": {},
  "hotkeyPercent": 10,
  "adjustmentTimes": [],
  "adjustmentTimeIndividualDisplays": false,
  "checkTimeAtStartup": false,
  "order": [],
  "checkForUpdates": false,
  "dismissedUpdate": "",
  "language": "system",
  "settingsVer": "v1.12.3",
  "names": {
    "DISPLAY\\BOE0747\\4&amp;8a52dc4&amp;0&amp;UID265988_0": "Twinkle ☆"
  },
  "analytics": true,
  "scrollShortcut": false,
  "useAcrylic": false,
  "useNativeAnimation": false,
  "uuid": "d2464a07-95c2-45cb-ac76-40b1c7a114d8",
  "branch": "master"
}

```
image about system color settings and app page(couldn't find dark/light switch in app pages):
![notittle](https://user-images.githubusercontent.com/13744203/96334993-6f6e1400-10a7-11eb-8f10-331be3d65774.jpg)

**Comment by xanderfrangos** [comment]
Hi @ClokMuch, I removed the ability to manually select the theme in 1.12.0. I didn't see a reason to keep it, as I couldn't see why users would want the brightness panel to be a different color than the others (volume, network, etc). Twinkle Tray now automatically selects the light/dark theme based off of the Windows preference, not app preference (so the 1st option in your screen shot, not the 2nd). I do realize now that it does make things a bit inconsistent when comparing with the Settings window. I'll update it so that the Settings window uses the app preference, not Windows. If I do that, is there a reason why you would still need to manually pick the light or dark theme?

**Comment by ClokMuch** [comment]
Dear @xanderfrangos ,
  Surely, auto-theme based on system config provide a same color, usually. But my theme config is a little different: 

- My wallpaper is dark, and my taskbar is fully transparent, so I prefer white icons(volum, network icons…) on bar.
![i1](https://user-images.githubusercontent.com/13744203/96403654-77df5f80-120b-11eb-948a-9fba92723741.jpg)

- In order to keep white icons, I have to select dark menu in system preference. But I don't like a black menu, so I also check on "color the menu background by theme color", so when I change volum or select a net, the menu is colored by my theme color(a light blue like Windows 8.1), not black, and I get used to this light color. 
![i2](https://user-images.githubusercontent.com/13744203/96403738-b1b06600-120b-11eb-9864-4753fc7c135e.jpg)

  So compared with auto-dark according system config, I prefer a light Twinkle Tray. 
  Above reasons cause my problem: dark menu config, but prefer a light menu.

Thanks for your response :D

**Comment by xanderfrangos** [comment]
I'll restore this functionality in a future update. 👍

**Comment by ClokMuch** [comment]
> I'll restore this functionality in a future update. 👍

Thanks for your quick response :D

**Comment by xanderfrangos** [comment]
@ClokMuch It took a lot longer than expected, but I've restored the Theme option to Twinkle Tray as of v1.13.0.

**Comment by ClokMuch** [comment]
> @ClokMuch It took a lot longer than expected, but I've restored the Theme option to Twinkle Tray as of v1.13.0.

No, it's useful program, and I'd like to witness it's development :D

**Comment by ClokMuch** [comment]
> @ClokMuch It took a lot longer than expected, but I've restored the Theme option to Twinkle Tray as of v1.13.0.

Excuse me, this feature doesn't work like I thought:
When I turn off "dyeing start menu, taskbar and notification center", theme option worked;
![屏幕截图(2267)](https://user-images.githubusercontent.com/13744203/107136686-824f7180-6940-11eb-8c3d-8f5eaca0776c.png)

However, when I turn on "dyeing start menu, taskbar and notification center", theme always dark...
![屏幕截图(2266)](https://user-images.githubusercontent.com/13744203/107136671-5b913b00-6940-11eb-8a57-72f96edee9ff.png)

Is it a new feature? Or any other options?  (((o(*ﾟ▽ﾟ*)o)))

**Comment by xanderfrangos** [comment]
@ClokMuch Did you want Twinkle Tray to be light, even with "dyeing start menu, taskbar and notification center" turned on in Windows?

**Comment by xanderfrangos** [comment]
Try out v1.13.1 and let me know if that's what you meant.

**Comment by ClokMuch** [comment]
Yes, it looks more suitable for my color settings like ver.1.11.4 (oﾟvﾟ)

Thanks for your quickly respond and update :D
