### ISSUE TITLE
Function suggestions

### ISSUE THREAD

**Issue by wsspsb** [xanderfrangos/twinkle-tray#98]
Function suggestions
Great app, thank you!
I hope to add a feature: turn off the display. I don't want to turn on the display when I connect to the computer remotely.

**Comment by xanderfrangos** [comment]
I'm looking into this feature, but it's dependent on each monitor supporting "power state" over DDC/CI. So even if/when the feature is added, there's no guarantee it will work for your monitor(s).

**Comment by xanderfrangos** [comment]
I will be including this as part of a larger feature in a future update. You can read more about it [here](https://github.com/xanderfrangos/twinkle-tray/issues/123). If anyone has suggestions/feedback about turning off displays over DDC/CI, please leave a comment there. Thanks!
