### ISSUE TITLE
Fee-free Sponsorship alternative: Paypal takes 1 USD

### ISSUE THREAD

**Issue by corneliusroemer** [xanderfrangos/twinkle-tray#99]
I wanted to donate a dollar to your project (thanks!) but then I saw that Paypal would take 1 USD in fees, which seemed totally disproportionate.

Not sure what the best alternative would be, but crypto could be a good place to start? Maybe with XRP, Bitcoin Cash or TRON to have low transaction costs?

**Comment by xanderfrangos** [comment]
Thanks for the interest in donating. 😀 I'll look into non-PayPal options, but I'm not particularly interested in crypto. I'd just be cashing out small amounts and getting hit with fees there. Fees will have to be paid somewhere, no matter the currency/platform. I'm sure I can find something that works better for non-US donations.

**Comment by corneliusroemer** [comment]
I don't have much experience with cashing out, but I don't think the fees would be high. Not 50% for sure. If you cash out say $100, I don't think it'd be more than a couple of $, or a few percent. If you don't want to cash out, you can always forward to another project you want to donate to yourself.

I'm not suggesting Crypto because I'm in any way crazy about crypto, I just did some research on other options in this case (small donations) and it seemed the best. Actually a really good use case.

In this case, the problem is not that there *are* fees, sure there'll be fees everywhere. The issue is that it's fixed $1. If I donate $1, fees are 100%. That's just bad. Clearly not feasible in this case.

An alternative is to not use paypal.me, but just give out your Paypal email, then people could transfer you *as a friend* which is fee-free. You're basically saying you're a merchant, and that's where Paypal makes its money.

**Comment by xanderfrangos** [comment]
The PayPal.me page is set up for personal use, so it's functionally the same as sending via email as a friend. I'm pretty sure the $1 you're seeing is related to international transactions. [PayPal has a minimum fee of 0.99 USD for all international transactions.](https://www.paypal.com/us/webapps/mpp/paypal-fees#SendAndReceiveMoney). Most Twinkle Tray users aren't from the US, so this is definitely something I want to address. 

I just saw that PayPal is rolling out crypto support, so I'll join their waitlist and see if that's any good. The fees look reasonable. If it's all centralized there, I don't mind it as much.

**Comment by nagromc** [comment]
You guys are talking about a donation page, but I cannot see any link. Any information about that?

**Comment by corneliusroemer** [comment]
@nagromc See here: http://paypal.me/xanderfrangos
![image](https://user-images.githubusercontent.com/25161793/103015768-4d7a8d00-4541-11eb-9679-5f2d01e7a38a.png)

@xanderfrangos I've come across Libera Pay, which helps open source projects accept recurring donations through Paypal and Stripe at lower fees. Maybe check it out, it's quite a cool community, I'm donating to a number of projects that way: https://liberapay.com/

**Comment by nagromc** [comment]
Oh thanks; I missed this one.

**Comment by xanderfrangos** [comment]
Hey all, I've updated the sponsor links in the repo to include Liberapay, Ko-Fi, and crypto options. Thanks for all of the suggestions and support. 👍

**Comment by corneliusroemer** [comment]
That's great! I've just donated through Liberapay. Let me know how it works out!

**Comment by xanderfrangos** [comment]
@corneliusroemer It isn't displaying in Liberapay yet, but it came through on PayPal. Thanks for the donation!

**Comment by corneliusroemer** [comment]
Oh cool! Just for the sake of calculating fees, I donated 2 Eur as $2.53.
How much arrived on your end after fees taken?

I think Liberapay sometimes doesn't act as intermediary at all. Could you
select how often you want to be paid out? Maybe that setting is just for
payments through Stripe, though.

**Comment by xanderfrangos** [comment]
@corneliusroemer I received €1.56 EUR after fees. I don't see any options in Liberapay for payment frequency. I think that's a Stripe-related feature. I'm hesitant to create a Stripe account because I'd have to register as a non-profit or business... which I'm not. 

To be honest, Ko-Fi looks like a better option for individual creators. Liberapay seems better for non-profits. They don't appear to do much unless you connect with Stripe.

**Comment by corneliusroemer** [comment]
But that's already better than the previous Paypal option I had. Now they took only 40 cent plus 3%. That's ok!
